In [1]:
import re
import pandas as pd
import datetime

# https://www.kaggle.com/datasets/imoisharma/uspatentsdata?resource=download 
# https://developer.uspto.gov/product/patent-grant-full-text-dataxml
# https://github.com/imoisharma/U.S.-Patents-Claims
# https://www.linkedin.com/pulse/text-parsing-python-us-patent-data-mohit-sharma/
# https://pypi.org/project/pypatent/

# ambiente python no Anaconda

In [2]:
#file = open(file="uspto_dataset.txt",mode='r')
#file = open(file="ipg221018.xml",mode='r')
revista = 2703
filename = f'Patente_{revista}.xml'
filename = 'Patente_2707_22112022.xml'
print(filename)
file = open(file=filename,mode='r',encoding="utf8")
#file = open(file="Patente_2703.xml",mode='r',encoding="utf8")

Patente_2707_22112022.xml

In [3]:
file_content_raw=file.read()

In [4]:
file.close()

In [5]:
text1=re.compile("<despacho>")

In [6]:
file_content=text1.split(file_content_raw)

In [7]:
while '' in file_content:
    file_content.remove('')
print("Número de patentes",len(file_content))

Número de patentes 2913

In [8]:
texto = f'<revista numero="{revista}" dataPublicacao="25/10/2022" diretoria="Patente">'
# buscar cpf \d{3}[.-]?\d{3}[.-]?\d{3}[.-]?\d{2}
p = re.compile(r'<revista numero=\"\d{4}\" dataPublicacao=\"../../\d{4}\" diretoria="Patente">')
m = p.match(texto)
print(m.group())

<revista numero="2703" dataPublicacao="25/10/2022" diretoria="Patente">

In [9]:
def ConverteData(data):
    d=datetime.datetime.strptime(data, "%d/%m/%Y")
    return f'{d.year:04}-{d.month:02}-{d.day:02}'

texto=file_content[0]
#texto = "05/10/2022"
t = re.compile(r'\d{2}/../\d{4}')
check = t.findall(texto)
data = ''.join(check)
print(data)
d=datetime.datetime.strptime(data, "%d/%m/%Y")
print("{}/{}/{}".format(d.day,d.month,d.year))
print("{}-{}-{}".format(d.year,d.month,d.day))
print(f'{d.year:04}-{d.month:02}-{d.day:02}')
data_revista=ConverteData(data)
print(data_revista)
# https://docs.python.org/pt-br/3.8/howto/regex.html
# https://pt.stackoverflow.com/questions/330458/como-formatar-datas-em-python
# https://stackoverflow.com/questions/339007/how-do-i-pad-a-string-with-zeroes

22/11/2022
22/11/2022
2022-11-22
2022-11-22
2022-11-22

In [10]:

# https://pythex.org/
# \"[U][S]\d{6}-\d{8}\.XML\"
# <?xml version="1.0" encoding="UTF-8"?>
# <us-patent-grant lang="EN" dtd-version="v4.5 2014-04-03" file="US864516-20191029.XML" status="PRODUCTION" id="us-patent-grant" country="US" date-produced="20191014" date-publ="20191029">
# </us-patent-grant>
# </xml>

codigo_tag = re.compile('<codigo>(.*?)</codigo>')
titulo_tag = re.compile('<titulo>(.*?)</titulo>')
comentario_tag = re.compile("<comentario inid=\"co\">(.*?)</comentario>") 
nome_completo_tag = re.compile("<nome-completo>(.*?)</nome-completo>") 
data_deposito_tag = re.compile("<data-deposito inid=\"22\">(.*?)</data-deposito>") 
numero_tag = re.compile("<numero inid=\"21\">(.*?)</numero>") 
numero_a2_tag = re.compile("<numero inid=\"21\" kindcode=\"A2\">(.*?)</numero>") 
numero_e2_tag = re.compile("<numero inid=\"21\" kindcode=\"E2\">(.*?)</numero>") 
numero_u2_tag = re.compile("<numero inid=\"21\" kindcode=\"U2\">(.*?)</numero>") 
numero_a8_tag = re.compile("<numero inid=\"21\" kindcode=\"A8\">(.*?)</numero>") 
numero_u8_tag = re.compile("<numero inid=\"21\" kindcode=\"U8\">(.*?)</numero>") 
numero_21b1_tag = re.compile("<numero inid=\"21\" kindcode=\"B1\">(.*?)</numero>") 
numero_21b8_tag = re.compile("<numero inid=\"21\" kindcode=\"B8\">(.*?)</numero>") 
numero_21y1_tag = re.compile("<numero inid=\"21\" kindcode=\"Y1\">(.*?)</numero>") 
numero_21y8_tag = re.compile("<numero inid=\"21\" kindcode=\"Y8\">(.*?)</numero>") 
numero_b1_tag = re.compile("<numero inid=\"11\" kindcode=\"B1\">(.*?)</numero>") 
numero_b8_tag = re.compile("<numero inid=\"11\" kindcode=\"B8\">(.*?)</numero>") 
numero_y1_tag = re.compile("<numero inid=\"11\" kindcode=\"Y1\">(.*?)</numero>") 
numero_y8_tag = re.compile("<numero inid=\"11\" kindcode=\"Y8\">(.*?)</numero>") 
numero_c8_tag = re.compile("<numero inid=\"11\" kindcode=\"C8\">(.*?)</numero>") 
numero_f1_tag = re.compile("<numero inid=\"11\" kindcode=\"F1\">(.*?)</numero>") 
data_fase_nacional_tag = re.compile("<data-fase-nacional inid=\"85\">(.*?)</data-fase-nacional>") 
titulo_pedido_tag = re.compile("<titulo inid=\"54\">(.*?)</titulo>") 
titular_lista_tag = re.compile("<titular-lista>[\s\S]*</titular-lista>")

codigo_list, titulo_list, comentario_list, nome_completo_list, data_deposito_list, numero_list, uf_list, sigla_list, numero_pct_list, data_pct_list, publicacao_internacional_list, numero_ompi_list, data_ompi_list, classe_internacional_list, classe_nacional_list, sigla_prioridade_list, numero_prioridade_list, data_prioridade_list, prioridade_list, prioridade_interna_list, data_fase_nacional_list, titulo_pedido_list, inventor_nome_completo_list, divisao_pedido_list, data_divisao_pedido_list, data_rpi_list, data_concessao_list = ([] for i in range(27))

for line in file_content:
    
    codigo=codigo_tag.findall(line)
    titulo=titulo_tag.findall(line)
    comentario=comentario_tag.findall(line)
    comentario = ', '.join(comentario)

    #to find inventors
    data_deposito=None
    data_fase_nacional=None
    numero=None
    nome_completo=None
    inventor_nome_completo=None
    titulo_pedido=""
    uf=None
    sigla=None
    numero_pct=" "
    data_pct=" "
    numero_ompi=" "
    data_ompi=" "
    classe_internacional=None
    str_classe = ''
    classe_nacional=None
    str_classe_nacional = ''
    sigla_prioridade=" "
    numero_prioridade=" "
    data_prioridade=" "
    str_prioridade=''
    numero_prioridade_interna=" "
    data_prioridade_interna=" "
    str_prioridade_interna=''
    numero_divisao_pedido=" "
    data_divisao_pedido=" "
    data_rpi=" "
    data_concessao=" "
    
    processos=re.findall("<processo-patente>[\s\S]*</processo-patente>",line)
    for processo in processos:
        data_deposito=data_deposito_tag.findall(processo)
        data_deposito=', '.join(data_deposito) # converte lista em string
        numero=numero_tag.findall(processo)
        if len(numero)==0:
            numero=numero_a2_tag.findall(processo)
            if len(numero)==0:
                numero=numero_u2_tag.findall(processo)
                if len(numero)==0:
                    numero=numero_a8_tag.findall(processo)
                    if len(numero)==0:
                        numero=numero_u8_tag.findall(processo)
                        if len(numero)==0:
                            numero=numero_b1_tag.findall(processo)
                            if len(numero)==0:
                                numero=numero_b8_tag.findall(processo)
                                if len(numero)==0:
                                    numero=numero_y1_tag.findall(processo)
                                    if len(numero)==0:
                                        numero=numero_y8_tag.findall(processo)
                                        if len(numero)==0:
                                            numero=numero_e2_tag.findall(processo)
                                            if len(numero)==0:
                                                numero=numero_21b1_tag.findall(processo)
                                                if len(numero)==0:
                                                    numero=numero_21b8_tag.findall(processo)
                                                    if len(numero)==0:
                                                        numero=numero_21y1_tag.findall(processo)
                                                        if len(numero)==0:
                                                            numero=numero_21y8_tag.findall(processo)
                                                            if len(numero)==0:
                                                                numero=numero_c8_tag.findall(processo)
                                                                if len(numero)==0:
                                                                    numero=numero_f1_tag.findall(processo)
        numero = ', '.join(numero)
        data_fase_nacional=data_fase_nacional_tag.findall(processo)
        data_fase_nacional = ', '.join(data_fase_nacional)
        titulo_pedido=titulo_pedido_tag.findall(processo)
        titulo_pedido = ', '.join(titulo_pedido)

        #concessao (16.3)
        concessoes_lista=re.findall("<concessao inid=\"45\">[\s\S]*</concessao>",processo)
        for concessao_lista in concessoes_lista:
            data_concessao=re.findall("<data>(.*?)</data>",concessao_lista)
            
        #publicacao_nacional (16.1)
        publicacoes_nacional_lista=re.findall("<publicacao-nacional inid=\"43\">[\s\S]*</publicacao-nacional>",processo)
        for publicacao_nacional_lista in publicacoes_nacional_lista:
            data_rpi=re.findall("<data-rpi>(.*?)</data-rpi>",publicacao_nacional_lista)
            
        #divisao_pedido
        divisao_pedidos_lista=re.findall("<divisao-pedido inid=\"62\">[\s\S]*</divisao-pedido>",processo)
        for divisao_pedido_lista in divisao_pedidos_lista:
            data_divisao_pedido=re.findall("<data-deposito>(.*?)</data-deposito>",divisao_pedido_lista)
            numero_divisao_pedido=re.findall("<numero>(.*?)</numero>",divisao_pedido_lista)
            
        #titular_lista
        titulares_lista=re.findall("<titular-lista>[\s\S]*</titular-lista>",processo)
        for titular_lista in titulares_lista:
            titulares=re.findall("<titular sequencia=\"1\" inid=\"71\">[\s\S]*</titular>",titular_lista)
            for titular in titulares:
                nome_completo=nome_completo_tag.findall(titular)
                nome_completo = '; '.join(nome_completo)
                enderecos=re.findall("<endereco>[\s\S]*</endereco>",titular)
                for endereco in enderecos:
                    uf=re.findall("<uf>(.*?)</uf>",endereco)
                    uf = '; '.join(uf)
                    paises=re.findall("<pais>[\s\S]*</pais>",endereco)
                    for pais in paises:
                        sigla=re.findall("<sigla>(.*?)</sigla>",pais)
                        sigla = '; '.join(sigla)
                        
            titulares=re.findall("<titular sequencia=\"1\" inid=\"73\">[\s\S]*</titular>",titular_lista)
            for titular in titulares:
                nome_completo=nome_completo_tag.findall(titular)
                nome_completo = '; '.join(nome_completo)
                enderecos=re.findall("<endereco>[\s\S]*</endereco>",titular)
                for endereco in enderecos:
                    uf=re.findall("<uf>(.*?)</uf>",endereco)
                    uf = '; '.join(uf)
                    paises=re.findall("<pais>[\s\S]*</pais>",endereco)
                    for pais in paises:
                        sigla=re.findall("<sigla>(.*?)</sigla>",pais)
                        sigla = '; '.join(sigla)

        #inventor_lista
        inventores_lista=re.findall("<inventor-lista>[\s\S]*</inventor-lista>",processo)
        for inventor_lista in inventores_lista:
            #print(inventor_lista)
            inventores=re.findall("<inventor sequencia=\"1\" inid=\"72\">[\s\S]*</inventor>",inventor_lista)
            for inventor in inventores:
                inventor_nome_completo=nome_completo_tag.findall(inventor)
                inventor_nome_completo = '; '.join(inventor_nome_completo)
                        
        #pedido_internacional
        pedidos_internacional_lista=re.findall("<pedido-internacional inid=\"86\">[\s\S]*</pedido-internacional>",processo)
        for pedido_internacional_lista in pedidos_internacional_lista:
            #print(pedido_internacional_lista)
            numeros_pct=re.findall("<numero-pct>[\s\S]*</numero-pct>",pedido_internacional_lista)
            for numero_pct_lista in numeros_pct:
                numero_pct=re.findall("<numero-pct>(.*?)</numero-pct>",numero_pct_lista)
            datas_pct=re.findall("<data-pct>[\s\S]*</data-pct>",pedido_internacional_lista)
            for data_pct_lista in datas_pct:
                data_pct=re.findall("<data-pct>(.*?)</data-pct>",data_pct_lista)

        #publicacao_internacional
        publicacoes_internacional_lista=re.findall("<publicacao-internacional inid=\"87\">[\s\S]*</publicacao-internacional>",processo)
        for publicacao_internacional_lista in publicacoes_internacional_lista:
            numeros_ompi=re.findall("<numero-ompi>[\s\S]*</numero-ompi>",publicacao_internacional_lista)
            for numero_ompi_lista in numeros_ompi:
                numero_ompi=re.findall("<numero-ompi>(.*?)</numero-ompi>",numero_ompi_lista)
            datas_ompi=re.findall("<data-ompi>[\s\S]*</data-ompi>",publicacao_internacional_lista)
            for data_ompi_lista in datas_ompi:
                data_ompi=re.findall("<data-ompi>(.*?)</data-ompi>",data_ompi_lista)

        #classificacao_internacional
        classificacoes_internacional_lista=re.findall("<classificacao-internacional-lista>[\s\S]*</classificacao-internacional-lista>",processo)
        for classificacao_internacional_lista in classificacoes_internacional_lista:
            for i in range(1,20):
                #print(f"<classificacao-internacional inid=\"51\" sequencia=\"{i}\" ano=\"2006.01\" >[\s\S]*</classificacao-internacional>")
                classificacoes_internacional=re.findall(f"<classificacao-internacional inid=\"51\" sequencia=\"{i}\" ano=\"2006.01\">[\s\S]*</classificacao-internacional>",classificacao_internacional_lista)
                for classificacao_internacional in classificacoes_internacional:
                    classe_internacional=re.findall(f"<classificacao-internacional inid=\"51\" sequencia=\"{i}\" ano=\"2006.01\">(.*?)</classificacao-internacional>",classificacao_internacional)
                    if i==1:
                        str_classe = ', '.join(classe_internacional) # converte lista em string
                    else:
                        str_classe = str_classe+'; '+', '.join(classe_internacional) # converte lista em string
                    #print(', '.join(numero)+' '+str_classe)

        #classificacao_nacional
        classificacoes_nacional_lista=re.findall("<classificacao-nacional-lista>[\s\S]*</classificacao-nacional-lista>",processo)
        for classificacao_nacional_lista in classificacoes_nacional_lista:
            for i in range(1,20):
                #print(f"<classificacao-nacional inid=\"52\" sequencia=\"{i}\" >[\s\S]*</classificacao-nacional>")
                classificacoes_nacional=re.findall(f"<classificacao-nacional inid=\"52\" sequencia=\"{i}\">[\s\S]*</classificacao-nacional>",classificacao_nacional_lista)
                for classificacao_nacional in classificacoes_nacional:
                    classe_nacional=re.findall(f"<classificacao-nacional inid=\"52\" sequencia=\"{i}\">(.*?)</classificacao-nacional>",classificacao_nacional)
                    if i==1:
                        str_classe_nacional = ', '.join(classe_nacional) # converte lista em string
                    else:
                        str_classe_nacional = str_classe_nacional+'; '+', '.join(classe_nacional) # converte lista em string
                    #print(', '.join(numero)+' '+str_classe)
                    
        #prioridade_unionista
        prioridades_unionista_lista=re.findall("<prioridade-unionista-lista>[\s\S]*</prioridade-unionista-lista>",processo)
        for prioridade_unionista_lista in prioridades_unionista_lista:
            for i in range(1,5):
                prioridades_unionista=re.findall(f"<prioridade-unionista sequencia=\"{i}\" inid=\"30\">[\s\S]*</prioridade-unionista>",prioridade_unionista_lista)
                for prioridade_unionista in prioridades_unionista:
                    #print(prioridade_unionista)
                    sigla_prioridade=re.findall("<sigla-pais inid=\"33\">(.*?)</sigla-pais>",prioridade_unionista)
                    numero_prioridade=re.findall("<numero-prioridade inid=\"32\">(.*?)</numero-prioridade>",prioridade_unionista)
                    data_prioridade=re.findall("<data-prioridade inid=\"31\">(.*?)</data-prioridade>",prioridade_unionista)
                    sigla_prioridade_str=sigla_prioridade[0]
                    numero_prioridade_str=numero_prioridade[0]
                    data_prioridade_str=data_prioridade[0]
                    if i==1:
                        str_prioridade = sigla_prioridade_str+numero_prioridade_str+' '+data_prioridade_str # converte lista em string
                    else:
                        str_prioridade = str_prioridade+'; '+sigla_prioridade_str+numero_prioridade_str+' '+data_prioridade_str

                    numero_str = ', '.join(numero)
                    if numero_str=='BR 11 2022 020312-8':
                        print(f"<prioridade-unionista sequencia=\"{i}\" inid=\"30\">[\s\S]*</prioridade-unionista>")
                        print(sigla_prioridade)
                        print(numero_prioridade)
                        print(data_prioridade)
                        print(str_prioridade)
 
        #prioridade_interna
        prioridades_interna_lista=re.findall("<prioridade-interna-lista>[\s\S]*</prioridade-interna-lista>",processo)
        for prioridade_interna_lista in prioridades_interna_lista:
            for i in range(1,5):
                prioridades_interna=re.findall(f"<prioridade-interna sequencia=\"{i}\" inid=\"66\">[\s\S]*</prioridade-interna>",prioridade_interna_lista)
                for prioridade_interna in prioridades_interna:
                    numero_prioridade_interna=re.findall("<numero-prioridade>(.*?)</numero-prioridade>",prioridade_interna)
                    data_prioridade_interna=re.findall("<data-prioridade>(.*?)</data-prioridade>",prioridade_interna)
                    numero_prioridade_interna_str=numero_prioridade_interna[0]
                    data_prioridade_interna_str=data_prioridade_interna[0]
                    if i==1:
                        str_prioridade_interna = numero_prioridade_interna_str+' '+data_prioridade_interna_str # converte lista em string
                    else:
                        str_prioridade_interna = str_prioridade_interna+'; '+numero_prioridade_interna_str+' '+data_prioridade_interna_str

                
    # checking length of gid is not equal to 0 then do append to all the lists
    if len(codigo)!=0:                             
        codigo_list.append(codigo[0])
        titulo_list.append(titulo[0])
        comentario_list.append(comentario)
        data_deposito_list.append(data_deposito)
        numero_list.append(numero)
        data_fase_nacional_list.append(data_fase_nacional)
        titulo_pedido_list.append(titulo_pedido)
        nome_completo_list.append(nome_completo)
        inventor_nome_completo_list.append(inventor_nome_completo)
        uf_list.append(uf)
        sigla_list.append(sigla)
        numero_pct_list.append(numero_pct[0])
        data_pct_list.append(data_pct[0])
        numero_ompi_list.append(numero_ompi[0])
        data_ompi_list.append(data_ompi[0])
        classe_internacional_list.append(str_classe)
        classe_nacional_list.append(str_classe_nacional)
        prioridade_list.append(str_prioridade)
        sigla_prioridade_list.append(sigla_prioridade[0])
        numero_prioridade_list.append(numero_prioridade[0])
        data_prioridade_list.append(data_prioridade[0])
        prioridade_interna_list.append(str_prioridade_interna)
        divisao_pedido_list.append(numero_divisao_pedido[0])
        data_divisao_pedido_list.append(data_divisao_pedido[0])
        data_rpi_list.append(data_rpi[0])
        data_concessao_list.append(data_concessao[0])

In [11]:
data_frame = pd.DataFrame(
    {'despacho': codigo_list,
     'numero': numero_list,
     'data_deposito': data_deposito_list,
     'data_fase_nacional': data_fase_nacional_list,
     'data_publicacao_nacional': data_rpi_list,
     'data_concessao': data_concessao_list,
     'numero_divisao': divisao_pedido_list,
     'data_divisao': data_divisao_pedido_list,
     'titulo': titulo_pedido_list,
     'depositante': nome_completo_list,
     'uf': uf_list,
     'sigla': sigla_list,
     'inventor': inventor_nome_completo_list,
     'numero_pct': numero_pct_list,
     'data_pct': data_pct_list,
     'numero_ompi': numero_ompi_list,
     'data_ompi': data_ompi_list,
     'classe_internacional': classe_internacional_list,
     'classe_nacional': classe_nacional_list,
     'prioridade': prioridade_list,
     'sigla_prioridade': sigla_prioridade_list,
     'numero_prioridade': numero_prioridade_list,
     'data_prioridade': data_prioridade_list,
     'prioridade_interna': prioridade_interna_list,
     'comentario': comentario_list,
     'texto_despacho': titulo_list
    })

In [12]:
data_frame.isnull().sum()

despacho                       0
numero                         0
data_deposito                  0
data_fase_nacional             0
data_publicacao_nacional       0
data_concessao                 0
numero_divisao                 0
data_divisao                   0
titulo                         0
depositante                  336
uf                           336
sigla                        336
inventor                    2120
numero_pct                     0
data_pct                       0
numero_ompi                    0
data_ompi                      0
classe_internacional           0
classe_nacional                0
prioridade                     0
sigla_prioridade               0
numero_prioridade              0
data_prioridade                0
prioridade_interna             0
comentario                     0
texto_despacho                 0
dtype: int64

In [13]:
#data_frame[["numero_list","codigo_list","data_deposito_list","uf_list","sigla_list","numero_pct_list","data_pct_list"]]
#data_frame[["numero_list","codigo_list","data_deposito_list","uf_list","sigla_list","numero_ompi_list","data_ompi_list"]]
#data_frame[["numero_list","codigo_list","data_deposito_list","uf_list","numero_ompi_list","classe_internacional_list"]]
#data_frame[["numero_list","codigo_list","data_deposito_list","uf_list","sigla_prioridade_list","numero_prioridade_list","data_prioridade_list"]]
def ConverteNumero2(x):
    s = str(x)
    s = s.replace("BR","")
    s = s.replace(" ","")
    pos = s.find('-')
    return s[0:pos]

def ConverteNumero(x):
    if x is None or pd.isna(x):
        return None

    s = str(x)
    s = s.replace("BR", "")
    s = s.replace(" ", "")
    pos = s.find('-')
    return s[0:pos]
    
data_frame["numero_new2"] = data_frame["numero"].str.replace(" ", "")
data_frame["numero_new3"] = data_frame["numero"].apply(ConverteNumero)
# https://stackoverflow.com/questions/52673285/performance-of-pandas-apply-vs-np-vectorize-to-create-new-column-from-existing-c
# https://pt.stackoverflow.com/questions/570986/atualizar-coluna-de-dataframe-no-python/571012#571012

list_dados = []
for i, infos in data_frame.iterrows():
    numero_convertido = ConverteNumero(infos.numero)
    list_dados.append(numero_convertido)

data_frame["numero_new"]=list_dados
data_frame[["numero","despacho","numero_new","numero_new2","numero_new3"]]

#data_frame[["numero"]].values.tolist()
#data_frame[["numero_new"]]=ConverteNumero(data_frame[["numero"]])
#data_frame[["numero","despacho","numero_new"]]
#numero = "BR 10 2013 014368-5"
#print(ConverteNumero(numero))

,numero,despacho,numero_new,numero_new2,numero_new3
0,BR 11 2022 018138-8,1.1,112022018138,BR112022018138-8,112022018138
1,BR 11 2022 020175-3,1.1,112022020175,BR112022020175-3,112022020175
2,BR 11 2022 022774-4,1.1,112022022774,BR112022022774-4,112022022774
3,BR 11 2022 022775-2,1.1,112022022775,BR112022022775-2,112022022775
4,BR 11 2022 022779-5,1.1,112022022779,BR112022022779-5,112022022779
...,...,...,...,...,...
2907,BR 11 2022 007455-7,25.8,112022007455,BR112022007455-7,112022007455
2908,BR 20 2019 011052-5,25.8,202019011052,BR202019011052-5,202019011052
2909,PI 0620420-1,25.8,PI0620420,PI0620420-1,PI0620420
2910,BR 10 2016 019325-7,25.9,102016019325,BR102016019325-7,102016019325
2911,BR 10 2021 013875-0,28.30,102021013875,BR102021013875-0,102021013875

In [14]:
# pip install mysql-connector-python
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

In [15]:
numero = "PI0808715"
# atualiza no localhost as tres tabelas: carga, anterioridades e anterioridades_desc
comando = f"SELECT * FROM arquivados WHERE numero='{numero}'"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
print(resultado)

[(1011532, '1.1', 'PI0808715', datetime.date(2011, 8, 9), 'dialp', 0, 0), (1475660, '1.3', 'PI0808715', datetime.date(2014, 8, 12), 'dialp', 0, 0), (1501853, '6.6', 'PI0808715', datetime.date(2014, 9, 16), 'dialp', 0, 0), (2788968, '7.1', 'PI0808715', datetime.date(2017, 4, 18), 'dialp', 0, 1), (2790019, '15.11', 'PI0808715', datetime.date(2017, 4, 18), 'dialp', 0, 0), (2956330, '9.2', 'PI0808715', datetime.date(2017, 9, 19), 'dialp', 0, 2), (3015281, '12.2', 'PI0808715', datetime.date(2017, 12, 19), 'dialp', 0, 0)]

In [16]:
# pule este comando
for i, infos in data_frame.iterrows():
    numero = infos.numero_new
    despacho = infos.despacho
    #print(numero,despacho,data_rpi)
    comando = f"INSERT INTO arquivadosxml (id, despacho, numero, data, divisao, anulado, prmexame) VALUES (NULL, '{despacho}', '{numero}', '{data_revista}', '', 0, 0);"
    #cursor.execute(comando)
    #conexao.commit()
    
# https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlconnection-commit.html
# https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-executemany.html

In [113]:
#data_frame.loc[0:6,'data_deposito']
df1 = data_frame.loc[data_frame['despacho']=='19.1']
df1.head(1)
#df2 = data_frame.loc[data_frame['numero']=='']
#df2.head(1)

Empty DataFrame
Columns: [despacho, numero, data_deposito, data_fase_nacional, data_publicacao_nacional, data_concessao, numero_divisao, data_divisao, titulo, depositante, uf, sigla, inventor, numero_pct, data_pct, numero_ompi, data_ompi, classe_internacional, classe_nacional, prioridade, sigla_prioridade, numero_prioridade, data_prioridade, prioridade_interna, comentario, texto_despacho, numero_new2]
Index: []

[0 rows x 27 columns]

In [114]:
#data_frame["depositante"][4]
print(len(data_frame.index)) # Apesar de super simples, porém esta versão conta valores NaN (Not a Number) da primeira coluna
print(data_frame[data_frame.columns[0]].count())
print(len(df1.index))

2912
2912
0

In [115]:
df1 = data_frame.loc[data_frame['numero']=='BR 11 2015 013307-0']
df1.head(1)

Empty DataFrame
Columns: [despacho, numero, data_deposito, data_fase_nacional, data_publicacao_nacional, data_concessao, numero_divisao, data_divisao, titulo, depositante, uf, sigla, inventor, numero_pct, data_pct, numero_ompi, data_ompi, classe_internacional, classe_nacional, prioridade, sigla_prioridade, numero_prioridade, data_prioridade, prioridade_interna, comentario, texto_despacho, numero_new2]
Index: []

[0 rows x 27 columns]

In [116]:
data_frame.iloc[1480]
#data_frame.iloc[14,2]
#df2 = data_frame.loc[data_frame['numero']=='BR 11 2022 007677-0']
#df2.head(1)

despacho                                                                  8.7
numero                                                    BR 10 2018 001097-2
data_deposito                                                      18/01/2018
data_fase_nacional
data_publicacao_nacional
data_concessao
numero_divisao
data_divisao
titulo
depositante                 FUNDACAO UNIVERSIDADE FEDERAL DE RONDONIA; INS...
uf                                                                     RO; RO
sigla                                                                  BR; BR
inventor                                                                 None
numero_pct
data_pct
numero_ompi
data_ompi
classe_internacional
classe_nacional
prioridade
sigla_prioridade
numero_prioridade
data_prioridade
prioridade_interna
comentario
texto_despacho                                                    Restauração
numero_new2                                                  BR102018001097-2
Name: 1480, dtype: object

In [117]:
data_frame.head(1)

,despacho,numero,data_deposito,data_fase_nacional,data_publicacao_nacional,data_concessao,numero_divisao,data_divisao,titulo,depositante,...,classe_internacional,classe_nacional,prioridade,sigla_prioridade,numero_prioridade,data_prioridade,prioridade_interna,comentario,texto_despacho,numero_new2
0,1.1,BR 11 2022 018138-8,,,,,,,,None,...,C08L 71/02; B01D 53/14; B31F 1/26; C09K 3/18; ...,,"US62/987,972 11/03/2020",US,"62/987,972",11/03/2020,,,Publicação Internacional – PCT. Apresentação d...,BR112022018138-8

In [118]:
# https://www.freepatentsonline.com/
#!pip install pypatent

In [ ]:
comentarios = """
rode xampp local
limpe tabela carga e depois faça o import carga.csv
Anaconda ambiente python rode patentbr.ipynb

1. SALVA PARECERES DE INDEFERIMENTO E SALVA PETIÇÕES 214
# Armazena os pareceres de indeferimento localmente de todos os pedidos que estão na carga e que tem indeferimento

2. CRIA NOVOS REGISTROS EM ANTERIORIDADES_DESC E ATUALIZA CAMPO DESCRICAO COM DISCUSSÃO SOBRE ATIVIDADE INVENTIVA
comando = f"select * from carga where numero<>'NUMERO' and numero not in (select numero from anterioridades_desc) and numero in (select numero from arquivados where despacho='12.2')"
# ******************************************INSERT ANTERIORIDADES_DESC CAMPO DESCRICAO COM DISCUSSÃO DA ATIVIDADE INVENTIVA

3. ATUALIZA CAMPO INCOERENCIA
comando = f"select * from anterioridades_desc where incoerencia='' and numero in (select numero from carga);"
## UPDATE anterioridades_desc campo incoerencia

4. ATUALIZA CAMPO CONCLUSOES com o texto literal da conclusao do parecer de indeferimento
comando = f"select * from anterioridades_desc where conclusao='';"
## UPDATE anterioridades_desc campo conclusao
procure por: SELECT * FROM `anterioridades_desc` WHERE conclusao like '%Código:%'
e apague o lixo, bem como caracteres especiais

5. ATUALIZA CAMPO RAZOES COM A CONCLUSAO DE INDEFERIMENTO CITANDO OS DOCUMENTOS DE ATIVIDADE INVENTIVA
comando = f"select * from anterioridades_desc where razoes='' AND numero in (select numero from carga) and numero in (select numero from arquivados where despacho='12.2')"
erros:
102015012164 tem D3 NPL ignorado
122020019318 artigo 25 (D1)
Não achei parecer de indeferimento 112012028948 
112013019574 documentos mencionados no 7.1
112013023949 citou todos os artigos mas é apenas artigo 25
BR112017023256 cita no quadro 4 D1 a D6 mas corretamente se baseia apenas em D3 e D4
122018076834 nao pegou D4 US5,226,943
122019015933 alegou falta de novidade, citou artigo 6 da lei 11.105
122019021564 alegou falta novidade quando tinha
122019022733 lei 11.105 e lei 10.814
122020007845 lei 11.105
PI1004183 falta de atividade inventiva mas nao cita documento
PI1005131 cita D1 a D4 mas não os usa
PI0708406 alegou falta clareza e novidade
122019012495 alegou artigo 10 ma e´so dupla porteção
122020024655 alegou falta de ativ. inventiv ms nao é
PI1102208 nao tem nenhum documento cadastrado mas citou D3, D4
BR112012029457 citou D1 que não existe
122021009061 ao inves de dizer artigo 6 por dupla proteção, disse por incider nele
122019027002 fala de um unico documento mas diz pelos documentos D1
112020006283 fala de artigo 212
122019008317 dupla proteção cita D1
MU9100581 cita atividade inventiva
202014013398 indeferido por falta de atividade inventiva
PI1015976 falta de unidade nao mencionada cito apenas artigo 22
122023002765 citou artigo 36
PI1015976 por não estar de acordo com os requisitos legais
PI1106311 citou D1 e D2 quando só tem D6

6. ATUALIZA CAMPO RESUMO_RECURSO COM A ROTINA RESUMIR_PETICAO_214.IPYNB

Obs: procure incompatilibildades entre razoes e conclusao

fazer rotina em php que analise as tabelas anterioridades_desc e verifique se o campo conclusao esta compativel com razoes. 
Se houver diferenças mostre os dois.
"""

In [64]:
#import pypatent
# https://github.com/daneads/pypatent
# https://pypi.org/project/patent-client/
# https://pypi.org/project/patzilla/
# OPS https://www.epo.org/searching-for-patents/data/web-services/ops.html
# DPMA https://depatisnet.dpma.de/DepatisNet/depatisnet?window=1&space=menu&content=index&action=index
#

In [65]:
#pypatent.Search('microsoft')

In [66]:
#from selenium import webdriver

In [67]:
#driver = webdriver.Firefox()

In [17]:
# Inicie aqui
import json
import requests

def conectar_siscap(url,return_json=False):
    headers = {
        "Accept": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    response = requests.get(url,headers=headers,verify=False)
    if response.status_code == 200:
        if return_json:
            data = response.json()
            json_data = json.dumps(data, indent=4)
            return(json_data)
        else:
            return response.text
    else:
        return(f"Erro: {response.status_code}")

    
numero='PI0905487'
numero='102020022082'
numero='112013005558'
#numero='102012010730' # este teve indeferimneto técnico 9.2, não tem 'indeferimento'
# https://cientistaspatentes.com.br/apiphp/menu_api.php
# https://cientistaspatentes.com.br/apiphp/patents/query/?q={%22application_number%22:%22C10000061%22}
# https://cientistaspatentes.com.br/apiphp/patents/query/?q={%22mysql_query%22:%22%20*%20FROM%20arquivados%20where%20numero=%27PI0905487%27%22}
# https://cientistaspatentes.com.br/apiphp/patents/query/?q={%22mysql_query%22:%22%20*%20FROM%20pedido%20where%20numero=%27PI0905487%27%22}
# https://cientistaspatentes.com.br/apiphp/patents/query/?q={%22mysql_query%22:%22%20*%20FROM%20pedido%20where%20decisao=%27indeferimento%27%20and%20numero=%27PI0905487%27%22}
# https://cientistaspatentes.com.br/apiphp/patents/query/?q={"mysql_query":" * FROM pedido where decisao='indeferimento' and numero='PI0905487'"}
# https://cientistaspatentes.com.br/apiphp/patents/query/?q={"mysql_query":" * FROM carga where divisao='direp'"}
# https://cientistaspatentes.com.br/apiphp/patents/query/?q={%22mysql_query%22:%22%20*%20FROM%20carga%20where%20divisao=%27direp%27%22}

query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
json_data = conectar_siscap(url,return_json=True)
    
#json_data='{"patents": [{"numero":"PI0905487","prioridade":"BR","instancia":"2 exame","decisao":"indeferimento","prioritario":"0","cc1":"4","anulado":"0","codigo":"1340921","rpi":"2020-12-29","divisao":"dicel","etapa":"2"}]}'
data = json.loads(json_data)
codigo = data["patents"][0]["codigo"]
divisao = data["patents"][0]["divisao"]
print(f"Código: {codigo}")
print(f"Divisão: {divisao}")

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Código: 1360866
Divisão: dicel

In [18]:
numero='112013005558'
query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM titulo where numero='{numero}'" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
json_data = conectar_siscap(url,return_json=True)
data = json.loads(json_data)
resumo = data["patents"][0]["resumo_cepit"]
print(f"{resumo}")

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Gerenciar listas reprodução, compreendendo: exibir a lista de reprodução atual e uma ou mais listas de reprodução que interceptam a lista de reprodução atual em um item de mídia atual, selecionar um dos seguintes: (1) quando um comando de mudar para mudar a partir da lista de reprodução atual para uma lista de reprodução mudada é recebido, primeiro mover para um próximo item de mídia da lista de reprodução que interceptam a lista de reprodução mudada no próximo item de mídia da lista de reprodução mudad, (2) por outro lado quando nenhum comando de mudar é recebido, primeiro mover para um próximo item de mídia da lista de reprodução atual, e exibir a lista de reprodução atual e uma ou mais listas de reprodução que interceptam a lista de reprodução atual no próximo item de mídia da lista de reprodução atual

In [70]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

# https://patents.google.com/patent/BR112012018157A2/pt?oq=BR112012018157
numero_pedido = '112012018157'
numero_pedido = '112013005558'
url = f"https://patents.google.com/patent/BR{numero_pedido}A2/pt?oq=BR{numero_pedido}"
data = conectar_siscap(url,return_json=False)
#print(data)
html = urlopen(url)
#print(html.read())
bs = BeautifulSoup(html.read(),'html.parser')
#print(bs.title)
nameList = bs.findAll("div", {"class":"abstract"})
for name in nameList:
    print(name.getText())
texto_pedido = name.getText()

D:\Users\abrantes\.conda\envs\python_inpi\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'patents.google.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

método de gerenciar listar de reprodução, dispositivo de mídia portátil, e, meio de armazenamento não transitório. gerenciar listas reprodução, compreendendo: exibir a lista de reprodução atual e uma ou mais listas de reprodução que interceptam a lista de reprodução atual em um item de mídia atual; selecionar um dos seguintes: (1) quando um comando de mudar para mudar a partir da lista de reprodução atual para uma lista de reprodução mudada é recebido, primeiro mover para um próximo item de mídia da lista de reprodução que interceptam a lista de reprodução mudada no próximo item de mídia da lista de reprodução mudad; (2) por outro lado quando nenhum comando de mudar é recebido, primeiro mover para um próximo item de mídia da lista de reprodução atual, e exibir a lista de reprodução atual e uma ou mais listas de reprodução que interceptam a lista de reprodução atual no próximo item de mídia da lista de reprodução atual.

D:\Users\abrantes\AppData\Local\Temp\ipykernel_30832\747014247.py:14: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  nameList = bs.findAll("div", {"class":"abstract"})

In [19]:
# conecte na VPN
url = 'https://siscap.inpi.gov.br/adm/pareceres/dicel/1120130055581360866.txt'  # 2 docs
url = 'https://siscap.inpi.gov.br/adm/pareceres/dicel/1020200220821721943.txt'  # 1 doc'
url = 'https://siscap.inpi.gov.br/adm/pareceres/dicel/1120210212831794461.txt'  # 2 docs
url = 'https://siscap.inpi.gov.br/adm/pareceres/dicel/PI10014121312416.txt' # 1 doc
url = 'https://siscap.inpi.gov.br/adm/pareceres/dicel/PI11069651379807.txt' # 1 doc
url = 'https://siscap.inpi.gov.br/adm/pareceres/dicel/1120120181571338559.txt' # 1 doc
url = f"https://siscap.inpi.gov.br/adm/pareceres/{divisao}/{numero}{codigo}.txt"
print(url)
texto_relatorio = conectar_siscap(url,return_json=False)
print(texto_relatorio)
caminho_do_arquivo=f"pareceres/{divisao}/{numero}{codigo}.txt"
with open(caminho_do_arquivo, 'w', encoding='utf-8') as arquivo:
    arquivo.write(texto_relatorio)

https://siscap.inpi.gov.br/adm/pareceres/dicel/1120130055581360866.txt
                                      SERVIÇO PÚBLICO FEDERAL
                                       MINISTÉRIO DA ECONOMIA
                           INSTITUTO NACIONAL DA PROPRIEDADE INDUSTRIAL

                                             RELATÓRIO DE EXAME TÉCNICO

 N.° do Pedido:                      BR112013005558-8            N.° de Depósito PCT:US2011/051262
 Data de Depósito:                   12/09/2011
 Prioridade Unionista:               US 12879982 (10/09/2010)
 Depositante:                        Sony Computer Entertainment America Llc (US)
 Inventor:                           Steve Schneider
 Título:                             Método de gerenciar listar de reprodução, dispositivo de mídia
                                     portátil, e, meio de armazenamento não transitório 

                                                                PARECER

Em 04/01/2020, por meio da petição 870210000611, a Requerente apresentou modificações no
pedido em resposta ao parecer emitido, notificado na RPI 2596 de 06/10/2020 (despacho 7.1).
Estas modificações estão consideradas no Quadro 1.

                                      Quadro 1  Páginas do pedido examinadas
                Elemento                               Páginas               n.o da Petição           Data

Relatório Descritivo                                    1 a 16               870210000611           04/01/2020
Quadro Reivindicatório                                   1a5                 870210000611           04/01/2020
Desenhos                                                 1a4                 020130019061           07/03/2013
Resumo                                                      1                870210000611           04/01/2020


  Quadro 2  Considerações referentes aos Artigos 10, 18, 22 e 32 da Lei n.o 9.279 de 14 de
                                  maio de 1996  LPI
Artigos da LPI                                                                                Sim       Não
A matéria enquadra-se no art. 10 da LPI (não se considera invenção)                            x
A matéria enquadra-se no art. 18 da LPI (não é patenteável)                                              x
O pedido apresenta Unidade de Invenção (art. 22 da LPI)                                        x
O pedido está de acordo com disposto no art. 32 da LPI                                         x
Comentários/Justificativas

         Mantém-se o posicionamento exarado em parecer de 1º exame técnico publicado na RPI
2596 de 06/10/2020, no qual considera-se que o presente pedido infringe o disposto no Art.
10(VI), por pleitear detalhes de exibição da interface gráfica do aplicativo de reprodução de uma
playlist, não sendo tais características passíveis de serem patenteadas.




Código:5975ce1e23737deeb22c88e902a79153versão1.3 19/04/12@MODELO_SISCAP@                               Página 1
                                           BR112013005558-8


               Quadro 3  Considerações referentes aos Artigos 24 e 25 da LPI

Artigos da LPI                                                           Sim               Não
O relatório descritivo está de acordo com disposto no art. 24 da LPI      x
O quadro reivindicatório está de acordo com disposto no art. 25 da LPI    x
Comentários/Justificativas

        Em petição 870210000611 de resposta ao parecer de 1º exame técnico exarado na RPI
2596 de 06/10/2020, a Requerente atendeu satisfatoriamente às exigências formuladas acerca
do não enquadramento do pedido no Art. 25 da LPI, assim como elucidou eventuais dúvidas que
o texto do quadro reivindicatório tenha suscitado.


                           Quadro 4  Documentos citados no parecer

 Código                                  Documento                             Data de publicação
    D1                                 US 2010153846                                  17/06/2010
    D2                                 US 2009327349                                  31/12/2009


    Quadro 5  Análise dos Requisitos de Patenteabilidade (Arts. 8.º, 11, 13 e 15 da LPI)
        Requisito de Patenteabilidade              Cumprimento           Reivindicações
                                                         Sim                    1-11
            Aplicação Industrial
                                                        Não                       -
                                                         Sim                    1-11
                 Novidade
                                                        Não                       -

                                                         Sim                      -
             Atividade Inventiva
                                                        Não                     1-11
Comentários/Justificativas

         Os argumentos apresentados pela Requerente foram levados em consideração e
julgados não persuasivos. Reitera-se a posição de que, apesar de dotado de novidade, o
presente pedido não possui atividade inventiva quando confrontado com os ensinamentos de D1
e D2.



Conclusão

        Assim sendo, de acordo com o Art. 37, indefiro o presente pedido, uma vez que não
atende ao requisito de atividade inventiva (Art. 8º combinado com Art. 13 da LPI) e não é
considerado invenção, incidindo no Art. 10 da LPI.

        De acordo com o Art. 212 da LPI, o depositante tem prazo de 60 (sessenta) dias, a partir
da data de publicação na RPI, para interposição de recurso.



                                                                                            Página 2
                                    BR112013005558-8


                                                            Publique-se o indeferimento (9.2).



                                                       Rio de Janeiro, 5 de fevereiro de 2021.




Bruna Marques Mazoco
Pesquisador/ Mat. Nº 2316562
DIRPA / CGPAT III/DICEL
Deleg. Comp. - Port. INPI/DIRPA Nº 001/18




                                                                                     Página 3

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [ ]:
#######################################################
# Armazena os pareceres de indeferimento localmente de todos os pedidos que estão na carga e que tem indeferimento
import os
import json
import requests

def conectar_siscap3(url,return_json=False):
    headers = {
        "Accept": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    response = requests.get(url, headers=headers, verify=False, timeout=60)

    if response.status_code != 200:
        return f"Erro: {response.status_code}"

    if return_json:
        text = response.text
    
        # 1️⃣ extrai apenas o JSON (remove lixo antes/depois)
        start = text.find('{')
        end = text.rfind('}') + 1
        text = text[start:end]
    
        # 2️⃣ remove TODOS os caracteres de controle inválidos
        text = re.sub(r'[\x00-\x1F\x7F]', ' ', text)
    
        # 3️⃣ normaliza espaços
        text = re.sub(r'\s+', ' ', text)
        print(text)

        try:
            data = json.loads(text)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"Resposta não é JSON válido. Erro: {e}\n"
                f"Início da resposta:\n{text[:500]}"
            )

        return json.dumps(data, indent=4, ensure_ascii=False)

    return response.text
        
#query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM carga" + '"'
query = '"' + "mysql_query" + '"' ":" + '"' + f" numero FROM anterioridades_desc" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
print(url)
json_data = conectar_siscap(url,return_json=True)
    
#json_data='{"patents": [{"numero":"PI0905487","prioridade":"BR","instancia":"2 exame","decisao":"indeferimento","prioritario":"0","cc1":"4","anulado":"0","codigo":"1340921","rpi":"2020-12-29","divisao":"dicel","etapa":"2"}]}'
json_data = re.sub(r'[\x00-\x08\x0B\x0C\x0E-\x1F]', '', json_data)
json_data = json_data.replace('\r', '')
#print(json_data)
data = json.loads(json_data)

for patent in data.get("patents", []):
    numero = patent.get("numero")
    if not numero or numero == "NUMERO":
        continue
        
    query_pedido = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query_pedido}"
    print(url)

    codigo = None
    divisao = None
    try:
        json_data = conectar_siscap(url,return_json=True)
    except:
        pass

    if not json_data:
        continue

    if json_data:
        try:
            #json_data='{"patents": [{"numero":"PI0905487","prioridade":"BR","instancia":"2 exame","decisao":"indeferimento","prioritario":"0","cc1":"4","anulado":"0","codigo":"1340921","rpi":"2020-12-29","divisao":"dicel","etapa":"2"}]}'
            json_data = re.sub(r'[\x00-\x08\x0B\x0C\x0E-\x1F]', '', json_data)
            json_data = json_data.replace('\r', '')
            data_pedido = json.loads(json_data)
            patents = data_pedido.get("patents", [])

            if patents:
                codigo = data_pedido["patents"][0]["codigo"]
                divisao = data_pedido["patents"][0]["divisao"]

                if not codigo or not divisao or divisao == "sanot":
                    continue

                url = f"https://siscap.inpi.gov.br/adm/pareceres/{divisao}/{numero}{codigo}.txt"
                print(url)
            
                texto_relatorio = conectar_siscap(url, return_json=False)
                if not texto_relatorio or len(texto_relatorio.strip()) < 50:
                    continue
                    
                caminho_do_arquivo = f"pareceres/{divisao}/{numero}{codigo}.txt"
                # os.makedirs(os.path.dirname(caminho_do_arquivo), exist_ok=True)

                if not os.path.exists(caminho_do_arquivo):
                    os.makedirs(os.path.dirname(caminho_do_arquivo), exist_ok=True)
                
                    with open(caminho_do_arquivo, "w", encoding="utf-8") as arquivo:
                        arquivo.write(texto_relatorio)
                else:
                    print(f"Arquivo já existe, não sobrescrito: {caminho_do_arquivo}")   
                    
                #with open(caminho_do_arquivo, "w", encoding="utf-8") as arquivo:
                #    arquivo.write(texto_relatorio)
                    
        except json.JSONDecodeError:
            pass  # JSON inválido → segue o fluxo sem abortar

In [62]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = f"select * from anterioridades_desc where incoerencia='';"
comando = f"select * from anterioridades_desc where incoerencia='' and numero in (select numero from carga);"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
#print(resultado)
lista = df.values.tolist()
lista1 = lista
lista = df.iloc[:, 1].tolist()
lista.insert(0, 'numero')
#print(lista)
lista = [x for x in lista if x != "numero"]
json_data = {"patents": [{"numero": item} for item in lista]}
print(json_data)

{'patents': [{'numero': '112016022470'}, {'numero': '122014016517'}, {'numero': '122014023771'}, {'numero': 'PI0708406'}, {'numero': '102012028509'}, {'numero': '102014031393'}, {'numero': '102021013199'}, {'numero': '112013014036'}, {'numero': '112013030993'}, {'numero': '112015010392'}, {'numero': '112018014897'}, {'numero': '112020019522'}, {'numero': '112021007409'}, {'numero': '202012026251'}, {'numero': '202012030729'}, {'numero': '202013003796'}, {'numero': '202013025439'}, {'numero': 'PI0802657'}, {'numero': 'PI0900922'}, {'numero': 'PI1004418'}, {'numero': 'PI1005286'}, {'numero': 'PI1106243'}, {'numero': '102015027655'}, {'numero': '202014012390'}, {'numero': 'PI0701396'}, {'numero': '102012023815'}, {'numero': '102013011905'}, {'numero': '102013028660'}, {'numero': '102014002008'}, {'numero': '102016024247'}, {'numero': '112013028037'}, {'numero': '112014009228'}, {'numero': '112016005819'}, {'numero': '112016013344'}, {'numero': '122014030028'}, {'numero': '122014030029'}, {'numero': 'MU9001502'}, {'numero': '102014024348'}, {'numero': '102015017470'}, {'numero': '112013029300'}, {'numero': '112016006522'}, {'numero': '112016006534'}, {'numero': '122019020154'}, {'numero': '202014025663'}, {'numero': '202015030495'}, {'numero': '102019009508'}, {'numero': '102014022400'}, {'numero': '102014027536'}, {'numero': '102020006622'}, {'numero': '102022000499'}, {'numero': '112013000811'}, {'numero': '112014032792'}, {'numero': '112015030032'}, {'numero': '112015030093'}, {'numero': '112016000345'}, {'numero': '112016003644'}, {'numero': '112021013435'}, {'numero': '112022018674'}, {'numero': '122016008192'}, {'numero': '122016008203'}, {'numero': '122020001985'}, {'numero': '122020022312'}, {'numero': '202017011129'}, {'numero': 'PI0906181'}, {'numero': 'PI1012905'}]}

In [ ]:
##################################
## UPDATE anterioridades_desc campo incoerencia
## confira tabela carga que todos se referem a recursos
## SELECT * FROM `carga` WHERE numero not in (select numero from arquivados where despacho='12.2') 112021018995
## SELECT * FROM `carga` WHERE numero not in (select numero from pedido where decisao='indeferimento')
## DELETE FROM `carga` WHERE numero not in (select numero from pedido where decisao='indeferimento')
## SELECT * FROM `carga` WHERE numero in (select numero from anterioridades_desc where incoerencia='') and numero in (select numero from pedido where decisao='indeferimento')
# https://platform.openai.com/settings/organization/billing/overview
# habilita modelo gpt-5-mini
# https://platform.openai.com/settings/organization/general  Limits  e selecione os modelos
# GPT-5.2 custa US$ 1,750 / 1 milhão de tokens https://openai.com/pt-BR/api/pricing/
# GPT-5-mini custa US$ 0,250 / 1 milhão de tokens

import os
from dotenv import load_dotenv

load_dotenv(dotenv_path='.env', override=True)
openai_api_key = os.getenv("OPENAI_API_KEY")

query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM carga" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
print(url)
json_data = conectar_siscap(url,return_json=True)
    
#json_data='{"patents": [{"numero":"PI0905487","prioridade":"BR","instancia":"2 exame","decisao":"indeferimento","prioritario":"0","cc1":"4","anulado":"0","codigo":"1340921","rpi":"2020-12-29","divisao":"dicel","etapa":"2"}]}'
#json_data='{"patents": [{"numero":"122019017408"}]}'
json_data = {"patents": [{"numero": item} for item in lista]}
json_data = json.dumps(json_data, indent=4, ensure_ascii=False)
print(json_data)
data = json.loads(json_data)

for patent in data.get("patents", []):
    numero = patent.get("numero")
    if numero != 'NUMERO' and divisao != 'sanot':
        query_pedido = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
        url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query_pedido}"
        #print(url)
        try:
            json_data = conectar_siscap(url,return_json=True)
        except:
            print(f"conexão inválida, pulando (indeferimento {numero} não encontrado)...")
            continue
            
        if not json_data:
            print("json_data vazio, pulando...")
            continue
        try:
            data_pedido = json.loads(json_data)
        except json.JSONDecodeError:
            print("JSON inválido, pulando...")
            continue

        if not data_pedido["patents"]:
            print(f"Sem registros para {numero}, pulando...")
            continue
    
        #data_pedido = json.loads(json_data)
        codigo = data_pedido["patents"][0]["codigo"]
        divisao = data_pedido["patents"][0]["divisao"]
    
        url = f"https://siscap.inpi.gov.br/adm/pareceres/{divisao}/{numero}{codigo}.txt"
        #print(url)
    
        texto_relatorio = conectar_siscap(url, return_json=False)
        #print(texto_relatorio)
        url = "https://api.openai.com/v1/chat/completions"
        query = f"""Neste parecer verifique se existência de incoerência interna entre as conclusões e o restante do parecer. 
        Ignore os X nos quadros 2 e 3 e considere apenas a discussão que se segue nestes quadros (se houver).
        Quando apenas uma ou mais reivindicação não tem novidade ou atividade inventiva, é justificável indeferir o pedido por falta de novidade 
        ou atividade inventiva, respectivamente. Escreva a saída numa forma corrida, sem bullets, parágrafos, travessões, nem pula linha.
        Apresente uma resposta curta e objetiva. Relatório: {texto_relatorio}"""
        data_json = {
            "model": "gpt-5-mini",  # Use o modelo desejado, como 'gpt-5.2' ou 'gpt-4o-mini' ou 'gpt-5-mini'
            "messages": [
                {"role": "user", "content": query}
            ]
        }
        headers = {
            "Authorization": f"Bearer {openai_api_key}",
            "Content-Type": "application/json"
        }
        #response = requests.post(url, headers=headers, json=data_json, verify=False)
        #if response.status_code == 200:
        #    resposta = response.json()
        #    resumo = resposta['choices'][0]['message']['content']
        #    sql_resumo = f"UPDATE anterioridades_desc set incoerencia='{resumo}' WHERE numero='{numero}';"
        #    print(sql_resumo)
        #else:
        #    print(f"Não consegui conexão {numero}")

        response = requests.post(url, headers=headers, json=data_json, verify=False)
        
        if response.status_code != 200:
            print(f"Não consegui conexão {numero} (HTTP {response.status_code})")
            continue
        
        try:
            resposta = response.json()
            resumo = resposta["choices"][0]["message"]["content"]
        except (ValueError, KeyError, IndexError, TypeError):
            print(f"Resposta inválida da API para {numero}")
            continue
            
        texto_corrigido = " ".join(resumo.split())
        texto_corrigido = texto_corrigido.replace("'", "")
        texto_corrigido = texto_corrigido.replace("‑","-")
        sql_resumo = f"UPDATE anterioridades_desc SET incoerencia='{texto_corrigido}' WHERE numero='{numero}';"
        print(sql_resumo)

In [20]:
###########################
## fazer o dowload de uma petição 
# Mudada a Natureza do PI9903162-0 para MU7903457-8
# patente 848 MU7903457-8_001102.tif
# 0009020990011020  NPRJ	11 - Pagamento Conciliado 020990001102	08/07/1999	848
url = "https://siscap.inpi.gov.br/adm/download.php?arquivo=MU7903457-8_001102.tif&url=http://172.20.2.43:8080/medusa/imagens/6e4c89327ae1f2aa6ccc0710f2291e710949428e2d5d7287a1df97194da50666/imagem"
url = "http://br00-aux.inpi.gov.br/webservice/retornaImagem.php?codigo=2534496"
arquivo_saida = "MU7903457-8_001102.tif"

## 112015014614
## petição 214
## 29409161954365011  RJ	11 - Pagamento Conciliado 870220079398	01/09/2022	214  
# NUMERO;PETICAO;NUMNOSSONUMERO;DATA_PETICAO;TIPO_PETICAO;FLAG_PEDEXAME;FLAG_IMAGEM;CD_IMAGEM;UPDATE_IMAGEM;CONCILIADO
# "112015014614";"WBRJ 870220079398";"29409161954365011";"01/09/22 00:00:00,000000000";"214";1;1;9201851;"2022-09-03 00:53:04";1
# {"patents": [{"numero":"112015014614","peticao":"WBRJ 870220079398","numnossonumero":"29409161954365011","data_peticao":"2022-09-01",
# "tipo_peticao":"214","flag_pedexame":"7","flag_imagem":"1","cd_imagem":"1","update_imagem":"0000-00-00 00:00:00","conciliado":"1"}]}

# numnossonumero = '29409161954365011'
url = "https://siscap.inpi.gov.br/adm/download.php?arquivo=29409161954365011.pdf&url=http://172.20.2.43:8080/medusa/imagens/868b32d2c3aca81ac70f51f04cd5da92970f0ae2c57bbec71e6d806ff35fa2ab/imagem"
url = "http://br00-aux.inpi.gov.br/webservice/retornaImagem.php?codigo=9201851"
arquivo_saida = "29409161954365011.pdf"

try:
    response = requests.get(url, stream=True, verify=False, timeout=30)

    if response.status_code == 200:
        with open(arquivo_saida, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
        print(f"Download concluído: {arquivo_saida}")
    else:
        print(f"Falha no download. HTTP {response.status_code}")

except requests.exceptions.RequestException as e:
    print(f"Erro na requisição: {e}")

Download concluído: 29409161954365011.pdf

In [ ]:
# algoritmo de correção de cd_imagem

import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = f"select * from despachos_pag where cd_imagem>0;"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
lista = df.values.tolist()
lista1 = lista
numnossonumero = df.iloc[:, 2].tolist()
cd_imagem = df.iloc[:, 7].tolist()
#print(cd_imagem)
with open("updates.sql", "w", encoding="utf-8") as arquivo:
    for i in range(len(numnossonumero)):
        inumnossonumero = numnossonumero[i]
        icd_imagem = cd_imagem[i]
        sql = f"UPDATE despachos_pag SET cd_imagem='{icd_imagem}' WHERE numnossonumero='{inumnossonumero}' and tipo_peticao='214';"
        print(sql)
        arquivo.write(sql + "\n")

In [34]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = f"select * from anterioridades_desc where resumo_recurso='' and numero in (select numero from carga);"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
#print(resultado)
lista = df.values.tolist()
lista1 = lista
lista = df.iloc[:, 1].tolist()
lista.insert(0, 'numero')
#print(lista)
lista = [x for x in lista if x != "numero"]
json_data = {"patents": [{"numero": item} for item in lista]}
print(json_data)

{'patents': [{'numero': '112012033666'}, {'numero': '112014000466'}, {'numero': '112015011774'}, {'numero': '122019025423'}, {'numero': '122020013634'}, {'numero': '202012024436'}, {'numero': '202013014629'}, {'numero': 'PI1103692'}, {'numero': '102013009882'}, {'numero': '102014031235'}, {'numero': '102016016661'}, {'numero': '112014022817'}, {'numero': '112015003727'}, {'numero': '202012019591'}, {'numero': 'MU9000951'}, {'numero': 'PI0820657'}, {'numero': '102012004873'}, {'numero': '102014013268'}, {'numero': '102015017470'}, {'numero': '102019010055'}, {'numero': '102022007897'}, {'numero': '112012032204'}, {'numero': '112013022907'}, {'numero': '112014024641'}, {'numero': '112015019446'}, {'numero': '112016005389'}, {'numero': '122020024337'}, {'numero': '122020026570'}, {'numero': '122020026576'}, {'numero': '122021003228'}, {'numero': '122021006465'}, {'numero': '122021015578'}, {'numero': '122021022394'}, {'numero': '122022007908'}, {'numero': '122022012256'}, {'numero': '122022017195'}, {'numero': '122022019084'}, {'numero': '122022020636'}, {'numero': '122023002765'}, {'numero': '202012022499'}, {'numero': '202013017528'}, {'numero': '202014000433'}, {'numero': '202014013394'}, {'numero': '202014016230'}, {'numero': '202014017096'}, {'numero': '202014025663'}, {'numero': '202015030495'}, {'numero': '202020012873'}, {'numero': 'PI0919236'}, {'numero': 'PI0919841'}, {'numero': 'PI1001299'}, {'numero': 'PI1003746'}, {'numero': 'PI1004208'}, {'numero': 'PI1012956'}, {'numero': 'PI1015976'}, {'numero': 'PI1016173'}, {'numero': 'PI1100371'}, {'numero': 'PI1103116'}, {'numero': 'PI1104976'}, {'numero': '102012004079'}, {'numero': '102012010956'}, {'numero': '102012013367'}, {'numero': '102012018962'}, {'numero': '102012021084'}, {'numero': '102012023815'}, {'numero': '102012030377'}, {'numero': '102012030828'}, {'numero': '102012032591'}, {'numero': '102012032927'}, {'numero': '102013011905'}, {'numero': '102013014262'}, {'numero': '102013023577'}, {'numero': '102013028660'}, {'numero': '102013030975'}, {'numero': '102014002008'}, {'numero': '102014013800'}, {'numero': '102014013993'}, {'numero': '102014017842'}, {'numero': '102014024578'}, {'numero': '102014030105'}, {'numero': '102015006648'}, {'numero': '102015017609'}, {'numero': '102016015976'}, {'numero': '102016024247'}, {'numero': '102017001568'}, {'numero': '112012017243'}, {'numero': '112012026297'}, {'numero': '112012026999'}, {'numero': '112012029457'}, {'numero': '112012029982'}, {'numero': '112013003772'}, {'numero': '112013004244'}, {'numero': '112013004888'}, {'numero': '112013005711'}, {'numero': '112013007644'}, {'numero': '112013015675'}, {'numero': '112013017629'}, {'numero': '112013018454'}, {'numero': '112013018740'}, {'numero': '112013021524'}, {'numero': '112013023748'}, {'numero': '112013024512'}, {'numero': '112013026179'}, {'numero': '112013028037'}, {'numero': '112013028285'}, {'numero': '112013032901'}, {'numero': '112013033182'}, {'numero': '112014000676'}, {'numero': '112014000985'}, {'numero': '112014002748'}, {'numero': '112014006871'}, {'numero': '112014008804'}, {'numero': '112014009228'}, {'numero': '112014009565'}, {'numero': '112014010783'}, {'numero': '112014019190'}, {'numero': '112014026167'}, {'numero': '112014028369'}, {'numero': '112015000104'}, {'numero': '112015002586'}, {'numero': '112015005059'}, {'numero': '112015006343'}, {'numero': '112015008215'}, {'numero': '112015010247'}, {'numero': '112015013260'}, {'numero': '112015014017'}, {'numero': '112015014726'}, {'numero': '112015014925'}, {'numero': '112015015060'}, {'numero': '112015016235'}, {'numero': '112015018808'}, {'numero': '112015021619'}, {'numero': '112015023151'}, {'numero': '112015027158'}, {'numero': '112015028942'}, {'numero': '112015029135'}, {'numero': '112015030335'}, {'numero': '112016002195'}, {'numero': '112016003968'}, {'numero': '112016005819'}, {'numero': '112016007141'}, {'numero': '112016008936'}, {'numero': '112016013344'}, {'numero': '112016022147'}, {'numero': '112016028205'}, {'numero': '112017002417'}, {'numero': '112017011602'}, {'numero': '112017015838'}, {'numero': '112018001513'}, {'numero': '112018005056'}, {'numero': '112018011763'}, {'numero': '112018011919'}, {'numero': '112020027002'}, {'numero': '122014030028'}, {'numero': '122014030029'}, {'numero': '122017012058'}, {'numero': '122019014139'}, {'numero': '122019018070'}, {'numero': '122019019741'}, {'numero': '122019021253'}, {'numero': '122019025630'}, {'numero': '122020001995'}, {'numero': '122020002476'}, {'numero': '122020003658'}, {'numero': '122020006593'}, {'numero': '122020007757'}, {'numero': '122020008510'}, {'numero': '122020013200'}, {'numero': '122020014740'}, {'numero': '122020015607'}, {'numero': '122020015741'}, {'numero': '122020017367'}, {'numero': '122020017979'}, {'numero': '122020019588'}, {'numero': '122020019976'}, {'numero': '122020020442'}, {'numero': '122020021164'}, {'numero': '122020022545'}, {'numero': '122020023574'}, {'numero': '122020024087'}, {'numero': '122020024099'}, {'numero': '122020024655'}, {'numero': '122021004607'}, {'numero': '122021004615'}, {'numero': '122021004616'}, {'numero': '122021019202'}, {'numero': '122022012262'}, {'numero': '122022013728'}, {'numero': '122022017178'}, {'numero': '122023002744'}, {'numero': '122023002748'}, {'numero': '202012011722'}, {'numero': '202013027692'}, {'numero': '202014000069'}, {'numero': '202014013398'}, {'numero': '202014018347'}, {'numero': '202015004655'}, {'numero': 'MU9001502'}, {'numero': 'PI0908127'}, {'numero': 'PI0913949'}, {'numero': 'PI0922619'}, {'numero': 'PI1005695'}, {'numero': 'PI1011883'}, {'numero': 'PI1011888'}, {'numero': 'PI1012651'}, {'numero': 'PI1013288'}, {'numero': 'PI1013657'}, {'numero': 'PI1013904'}, {'numero': 'PI1014277'}, {'numero': 'PI1103669'}, {'numero': 'PI1105730'}, {'numero': 'PI1106900'}, {'numero': 'PI1106311'}, {'numero': '102019009508'}, {'numero': '102014022400'}, {'numero': '102014027536'}, {'numero': '102022000499'}, {'numero': '112013000811'}, {'numero': '112014032792'}, {'numero': '112015030032'}, {'numero': '112015030093'}, {'numero': '112016000345'}, {'numero': '112016003644'}, {'numero': '112022018674'}, {'numero': '122016008192'}, {'numero': '122016008203'}, {'numero': '122020001985'}, {'numero': 'PI1012905'}, {'numero': '102013024752'}, {'numero': 'PI0815837'}, {'numero': '112015002739'}, {'numero': 'PI1006418'}, {'numero': '112015020079'}, {'numero': '202015005230'}, {'numero': '202014006525'}, {'numero': '202019004832'}, {'numero': '102023026373'}, {'numero': '102022016594'}]}

In [35]:
# donwload das peticoes
# varios registros estao com cd_imagem=1
# numnossonumero=29409161953366073 cd_imagem=1
# para corrigir detectar no DBVISUALIZER os casos de 214
# select * from CEPIT_SISCAP.SISCAP_DESPACHOS_PAG where tipo_peticao='214' and cd_imagem>0
# salva em CSV e carrega no arquivo local do XAMPP na tabela despachos_pag
# delete FROM `despachos_pag`  where cd_imagem=0
# rode o algoritmo de correção de cd_imagem
# faça o import de updates.sql
# confira select * from despachos_pag where cd_imagem=0 and tipo_peticao='214';

import os
import json
import requests

#query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM carga" + '"'
query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM carga" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
print(url)

#json_data = conectar_siscap(url,return_json=True)
#json_data = re.sub(r'[\x00-\x08\x0B\x0C\x0E-\x1F]', '', json_data)
#json_data = json_data.replace('\r', '')
#data = json.loads(json_data)

json_str = json.dumps(json_data)
json_str = re.sub(r'[\x00-\x08\x0B\x0C\x0E-\x1F]', '', json_str)
json_str = json_str.replace('\r', '')
data = json.loads(json_str)

#print(json_data)

for patent in data.get("patents", []):
    numero = patent.get("numero")
    #divisao = patent.get("divisao")
    if not numero or numero == "NUMERO":
        continue

    # https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag WHERE numero='112015014614' and tipo_peticao='214'" 
    query_pedido = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM despachos_pag where numero='{numero}' and tipo_peticao='214'"+'"' # 112015029938
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query_pedido}"
    print(url)

    numnossonumero = None
    cd_imagem = None
    try:
        json_data = conectar_siscap(url,return_json=True)
    except:
        pass

    if not json_data:
        continue

    if json_data:
        try:
            json_data = re.sub(r'[\x00-\x08\x0B\x0C\x0E-\x1F]', '', json_data)
            json_data = json_data.replace('\r', '')
            data_pedido = json.loads(json_data)
            patents = data_pedido.get("patents", [])

            if patents:
                numnossonumero = data_pedido["patents"][0]["numnossonumero"]
                cd_imagem = int(data_pedido["patents"][0]["cd_imagem"])
                print (f"numnossonumero={numnossonumero} cd_imagem={cd_imagem}")

                if not codigo or not cd_imagem or cd_imagem==1:
                    continue

                url = f"http://br00-aux.inpi.gov.br/webservice/retornaImagem.php?codigo={cd_imagem}"
                arquivo_saida = f"pareceres/peticoes/{numero}_{numnossonumero}_214.pdf"

                try:
                    response = requests.get(url, stream=True, verify=False, timeout=30)
                
                    if response.status_code == 200:
                        if not os.path.exists(arquivo_saida):
                            with open(arquivo_saida, "wb") as f:
                                for chunk in response.iter_content(chunk_size=8192):
                                    if chunk:
                                        f.write(chunk)
                            print(f"Download concluído: {arquivo_saida}")
                        else:
                            print(f"O arquivo {arquivo_saida} já existe. Nada foi gravado.")
                    else:
                        print(f"Falha no download. HTTP {response.status_code}")
                
                except requests.exceptions.RequestException as e:
                    print(f"Erro na requisição: {e}")
   
                    
        except json.JSONDecodeError:
            pass  # JSON inválido → segue o fluxo sem abortar

https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM carga"
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112012033666' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161809558149 cd_imagem=5540174
O arquivo pareceres/peticoes/112012033666_29409161809558149_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014000466' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161934580219 cd_imagem=8146246
O arquivo pareceres/peticoes/112014000466_29409161934580219_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015011774' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161920516874 cd_imagem=7318588
Download concluído: pareceres/peticoes/112015011774_29409161920516874_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122019025423' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161920516874 cd_imagem=7318588
Download concluído: pareceres/peticoes/122019025423_29409161920516874_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020013634' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161941285812 cd_imagem=8474705
Download concluído: pareceres/peticoes/122020013634_29409161941285812_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202012024436' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161906788099 cd_imagem=6315454
Download concluído: pareceres/peticoes/202012024436_29409161906788099_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202013014629' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161908065892 cd_imagem=6529830
O arquivo pareceres/peticoes/202013014629_29409161908065892_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1103692' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161950098906 cd_imagem=8910581
O arquivo pareceres/peticoes/PI1103692_29409161950098906_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102013009882' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161951224930 cd_imagem=8977160
O arquivo pareceres/peticoes/102013009882_29409161951224930_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014031235' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161919817912 cd_imagem=7276248
Download concluído: pareceres/peticoes/102014031235_29409161919817912_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102016016661' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161947411992 cd_imagem=8842146
O arquivo pareceres/peticoes/102016016661_29409161947411992_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014022817' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161936820543 cd_imagem=8264570
O arquivo pareceres/peticoes/112014022817_29409161936820543_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015003727' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=0000221607847544 cd_imagem=3804981
O arquivo pareceres/peticoes/112015003727_0000221607847544_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202012019591' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161903783207 cd_imagem=6114935
O arquivo pareceres/peticoes/202012019591_29409161903783207_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='MU9000951' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161903286513 cd_imagem=6075172
O arquivo pareceres/peticoes/MU9000951_29409161903286513_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI0820657' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925737054 cd_imagem=7711342
Download concluído: pareceres/peticoes/PI0820657_29409161925737054_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012004873' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942694465 cd_imagem=8551877
O arquivo pareceres/peticoes/102012004873_29409161942694465_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014013268' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161955516625 cd_imagem=9326015
O arquivo pareceres/peticoes/102014013268_29409161955516625_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102015017470' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161946052530 cd_imagem=8756808
O arquivo pareceres/peticoes/102015017470_29409161946052530_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102019010055' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161911362401 cd_imagem=6671231
O arquivo pareceres/peticoes/102019010055_29409161911362401_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102022007897' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162333642234 cd_imagem=10879055
Download concluído: pareceres/peticoes/102022007897_29409162333642234_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112012032204' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161957989504 cd_imagem=9360008
O arquivo pareceres/peticoes/112012032204_29409161957989504_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013022907' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921399782 cd_imagem=7379666
O arquivo pareceres/peticoes/112013022907_29409161921399782_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014024641' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942406583 cd_imagem=8523890
O arquivo pareceres/peticoes/112014024641_29409161942406583_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015019446' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161955533201 cd_imagem=9250098
O arquivo pareceres/peticoes/112015019446_29409161955533201_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016005389' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161927043254 cd_imagem=7864419
O arquivo pareceres/peticoes/112016005389_29409161927043254_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020024337' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161935988327 cd_imagem=8222436
O arquivo pareceres/peticoes/122020024337_29409161935988327_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020026570' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161940804174 cd_imagem=8448817
O arquivo pareceres/peticoes/122020026570_29409161940804174_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020026576' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161940804182 cd_imagem=8448702
O arquivo pareceres/peticoes/122020026576_29409161940804182_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122021003228' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943211441 cd_imagem=8558546
O arquivo pareceres/peticoes/122021003228_29409161943211441_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122021006465' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162302453219 cd_imagem=9686537
O arquivo pareceres/peticoes/122021006465_29409162302453219_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122021015578' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942607228 cd_imagem=8539391
O arquivo pareceres/peticoes/122021015578_29409161942607228_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122021022394' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161950376272 cd_imagem=8944127
O arquivo pareceres/peticoes/122021022394_29409161950376272_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122022007908' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161957835400 cd_imagem=9399955
O arquivo pareceres/peticoes/122022007908_29409161957835400_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122022012256' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958126550 cd_imagem=9400039
O arquivo pareceres/peticoes/122022012256_29409161958126550_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122022017195' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161961255498 cd_imagem=9584532
O arquivo pareceres/peticoes/122022017195_29409161961255498_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122022019084' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161961302429 cd_imagem=9584527
O arquivo pareceres/peticoes/122022019084_29409161961302429_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122022020636' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162308028889 cd_imagem=9993084
O arquivo pareceres/peticoes/122022020636_29409162308028889_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122023002765' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162308007113 cd_imagem=9994814
O arquivo pareceres/peticoes/122023002765_29409162308007113_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202012022499' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161923060413 cd_imagem=7465749
O arquivo pareceres/peticoes/202012022499_29409161923060413_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202013017528' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921708505 cd_imagem=7370740
O arquivo pareceres/peticoes/202013017528_29409161921708505_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014000433' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921972245 cd_imagem=7394568
O arquivo pareceres/peticoes/202014000433_29409161921972245_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014013394' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161920116990 cd_imagem=7334855
O arquivo pareceres/peticoes/202014013394_29409161920116990_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014016230' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921959354 cd_imagem=7390291
O arquivo pareceres/peticoes/202014016230_29409161921959354_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014017096' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161922540403 cd_imagem=7455031
O arquivo pareceres/peticoes/202014017096_29409161922540403_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014025663' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921286686 cd_imagem=7365285
O arquivo pareceres/peticoes/202014025663_29409161921286686_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202015030495' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921241925 cd_imagem=7337314
O arquivo pareceres/peticoes/202015030495_29409161921241925_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202020012873' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161947920846 cd_imagem=8801668
O arquivo pareceres/peticoes/202020012873_29409161947920846_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI0919236' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161940400286 cd_imagem=8435923
O arquivo pareceres/peticoes/PI0919236_29409161940400286_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI0919841' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161941803155 cd_imagem=8502304
O arquivo pareceres/peticoes/PI0919841_29409161941803155_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1001299' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161929090802 cd_imagem=7988268
O arquivo pareceres/peticoes/PI1001299_29409161929090802_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1003746' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161938860178 cd_imagem=8384822
O arquivo pareceres/peticoes/PI1003746_29409161938860178_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1004208' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161920406602 cd_imagem=7298826
O arquivo pareceres/peticoes/PI1004208_29409161920406602_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1012956' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921377622 cd_imagem=7441048
O arquivo pareceres/peticoes/PI1012956_29409161921377622_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1015976' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161928694631 cd_imagem=7946448
O arquivo pareceres/peticoes/PI1015976_29409161928694631_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1016173' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943832969 cd_imagem=8582727
Download concluído: pareceres/peticoes/PI1016173_29409161943832969_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1100371' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921945434 cd_imagem=7392333
O arquivo pareceres/peticoes/PI1100371_29409161921945434_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1103116' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161929427670 cd_imagem=8004700
O arquivo pareceres/peticoes/PI1103116_29409161929427670_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1104976' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161923462074 cd_imagem=7486772
O arquivo pareceres/peticoes/PI1104976_29409161923462074_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012004079' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161959815406 cd_imagem=9468813
O arquivo pareceres/peticoes/102012004079_29409161959815406_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012010956' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958436894 cd_imagem=9441575
O arquivo pareceres/peticoes/102012010956_29409161958436894_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012013367' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161951092936 cd_imagem=8965563
O arquivo pareceres/peticoes/102012013367_29409161951092936_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012018962' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161934523860 cd_imagem=8135406
Download concluído: pareceres/peticoes/102012018962_29409161934523860_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012021084' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161957678703 cd_imagem=9347455
O arquivo pareceres/peticoes/102012021084_29409161957678703_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012023815' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161934300119 cd_imagem=8141770
O arquivo pareceres/peticoes/102012023815_29409161934300119_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012030377' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161960851941 cd_imagem=9512522
O arquivo pareceres/peticoes/102012030377_29409161960851941_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012030828' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161928710750 cd_imagem=7971052
O arquivo pareceres/peticoes/102012030828_29409161928710750_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012032591' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161946292892 cd_imagem=8771503
O arquivo pareceres/peticoes/102012032591_29409161946292892_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102012032927' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942260970 cd_imagem=8519713
O arquivo pareceres/peticoes/102012032927_29409161942260970_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102013011905' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161927519267 cd_imagem=7863830
O arquivo pareceres/peticoes/102013011905_29409161927519267_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102013014262' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161954963989 cd_imagem=9226448
O arquivo pareceres/peticoes/102013014262_29409161954963989_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102013023577' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161927568640 cd_imagem=7864427
O arquivo pareceres/peticoes/102013023577_29409161927568640_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102013028660' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161947052127 cd_imagem=8737933
O arquivo pareceres/peticoes/102013028660_29409161947052127_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102013030975' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161952060310 cd_imagem=9054272
O arquivo pareceres/peticoes/102013030975_29409161952060310_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014002008' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943962889 cd_imagem=8590984
O arquivo pareceres/peticoes/102014002008_29409161943962889_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014013800' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161955438640 cd_imagem=9251525
O arquivo pareceres/peticoes/102014013800_29409161955438640_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014013993' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161927017083 cd_imagem=7817653
O arquivo pareceres/peticoes/102014013993_29409161927017083_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014017842' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161923051813 cd_imagem=7642170
O arquivo pareceres/peticoes/102014017842_29409161923051813_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014024578' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925343145 cd_imagem=7657412
O arquivo pareceres/peticoes/102014024578_29409161925343145_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014030105' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943947553 cd_imagem=8590615
O arquivo pareceres/peticoes/102014030105_29409161943947553_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102015006648' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161956661807 cd_imagem=9295068
O arquivo pareceres/peticoes/102015006648_29409161956661807_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102015017609' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161952406128 cd_imagem=9047639
O arquivo pareceres/peticoes/102015017609_29409161952406128_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102016015976' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161951057880 cd_imagem=8978371
O arquivo pareceres/peticoes/102016015976_29409161951057880_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102016024247' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161948621605 cd_imagem=8910623
O arquivo pareceres/peticoes/102016024247_29409161948621605_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102017001568' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162300363409 cd_imagem=9584733
O arquivo pareceres/peticoes/102017001568_29409162300363409_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112012017243' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943800498 cd_imagem=8590965
O arquivo pareceres/peticoes/112012017243_29409161943800498_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112012026297' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161929063872 cd_imagem=7970342
O arquivo pareceres/peticoes/112012026297_29409161929063872_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112012026999' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161935073515 cd_imagem=8159492
O arquivo pareceres/peticoes/112012026999_29409161935073515_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112012029457' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161927931036 cd_imagem=7902487
O arquivo pareceres/peticoes/112012029457_29409161927931036_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112012029982' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161957421613 cd_imagem=9342223
O arquivo pareceres/peticoes/112012029982_29409161957421613_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013003772' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921579900 cd_imagem=7370928
O arquivo pareceres/peticoes/112013003772_29409161921579900_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013004244' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161927319543 cd_imagem=7843057
O arquivo pareceres/peticoes/112013004244_29409161927319543_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013004888' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161926215833 cd_imagem=7803890
O arquivo pareceres/peticoes/112013004888_29409161926215833_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013005711' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161944995756 cd_imagem=8625282
O arquivo pareceres/peticoes/112013005711_29409161944995756_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013007644' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161710478763 cd_imagem=4412762
O arquivo pareceres/peticoes/112013007644_29409161710478763_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013015675' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161944514561 cd_imagem=8616388
O arquivo pareceres/peticoes/112013015675_29409161944514561_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013017629' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943516056 cd_imagem=8572550
O arquivo pareceres/peticoes/112013017629_29409161943516056_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013018454' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942284305 cd_imagem=8531030
O arquivo pareceres/peticoes/112013018454_29409161942284305_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013018740' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161946825734 cd_imagem=8732910
O arquivo pareceres/peticoes/112013018740_29409161946825734_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013021524' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161935834486 cd_imagem=8215054
O arquivo pareceres/peticoes/112013021524_29409161935834486_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013023748' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161927810905 cd_imagem=7902901
O arquivo pareceres/peticoes/112013023748_29409161927810905_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013024512' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161955476747 cd_imagem=9251528
O arquivo pareceres/peticoes/112013024512_29409161955476747_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013026179' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943211425 cd_imagem=8558545
O arquivo pareceres/peticoes/112013026179_29409161943211425_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013028037' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161931343160 cd_imagem=8007750
O arquivo pareceres/peticoes/112013028037_29409161931343160_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013028285' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161935629688 cd_imagem=8191305
O arquivo pareceres/peticoes/112013028285_29409161935629688_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013032901' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925404942 cd_imagem=7680306
O arquivo pareceres/peticoes/112013032901_29409161925404942_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013033182' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161929517881 cd_imagem=7981270
O arquivo pareceres/peticoes/112013033182_29409161929517881_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014000676' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161926827251 cd_imagem=7808608
O arquivo pareceres/peticoes/112014000676_29409161926827251_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014000985' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161928952541 cd_imagem=7955314
O arquivo pareceres/peticoes/112014000985_29409161928952541_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014002748' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942284232 cd_imagem=8527904
O arquivo pareceres/peticoes/112014002748_29409161942284232_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014006871' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942013549 cd_imagem=8513088
O arquivo pareceres/peticoes/112014006871_29409161942013549_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014008804' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942139267 cd_imagem=8519932
O arquivo pareceres/peticoes/112014008804_29409161942139267_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014009228' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161932975666 cd_imagem=8050009
O arquivo pareceres/peticoes/112014009228_29409161932975666_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014009565' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943045851 cd_imagem=8550919
O arquivo pareceres/peticoes/112014009565_29409161943045851_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014010783' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161952329620 cd_imagem=9052612
O arquivo pareceres/peticoes/112014010783_29409161952329620_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014019190' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161952291029 cd_imagem=9046760
O arquivo pareceres/peticoes/112014019190_29409161952291029_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014026167' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161948568887 cd_imagem=8887065
O arquivo pareceres/peticoes/112014026167_29409161948568887_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014028369' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161917199286 cd_imagem=7099437
O arquivo pareceres/peticoes/112014028369_29409161917199286_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015000104' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161951509020 cd_imagem=9071959
O arquivo pareceres/peticoes/112015000104_29409161951509020_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015002586' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161957081570 cd_imagem=9332031
O arquivo pareceres/peticoes/112015002586_29409161957081570_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015005059' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161953582116 cd_imagem=9133005
O arquivo pareceres/peticoes/112015005059_29409161953582116_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015006343' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161954974948 cd_imagem=9226722
O arquivo pareceres/peticoes/112015006343_29409161954974948_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015008215' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161961356243 cd_imagem=9530645
O arquivo pareceres/peticoes/112015008215_29409161961356243_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015010247' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161924704829 cd_imagem=7636019
O arquivo pareceres/peticoes/112015010247_29409161924704829_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015013260' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161929473671 cd_imagem=7996806
O arquivo pareceres/peticoes/112015013260_29409161929473671_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015014017' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161957668040 cd_imagem=9342439
O arquivo pareceres/peticoes/112015014017_29409161957668040_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015014726' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161951390465 cd_imagem=8986634
O arquivo pareceres/peticoes/112015014726_29409161951390465_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015014925' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161956545971 cd_imagem=9285754
O arquivo pareceres/peticoes/112015014925_29409161956545971_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015015060' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161952095653 cd_imagem=9029968
O arquivo pareceres/peticoes/112015015060_29409161952095653_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015016235' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161956362192 cd_imagem=9295144
O arquivo pareceres/peticoes/112015016235_29409161956362192_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015018808' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161953153827 cd_imagem=9133631
O arquivo pareceres/peticoes/112015018808_29409161953153827_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015021619' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161946889708 cd_imagem=8720974
O arquivo pareceres/peticoes/112015021619_29409161946889708_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015023151' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161947365281 cd_imagem=8768851
O arquivo pareceres/peticoes/112015023151_29409161947365281_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015027158' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161923912886 cd_imagem=7535528
O arquivo pareceres/peticoes/112015027158_29409161923912886_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015028942' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161955001250 cd_imagem=9258040
O arquivo pareceres/peticoes/112015028942_29409161955001250_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015029135' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161956980422 cd_imagem=9327914
O arquivo pareceres/peticoes/112015029135_29409161956980422_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015030335' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161961240695 cd_imagem=9564606
O arquivo pareceres/peticoes/112015030335_29409161961240695_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016002195' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161951912763 cd_imagem=9028231
O arquivo pareceres/peticoes/112016002195_29409161951912763_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016003968' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161952216507 cd_imagem=9054061
O arquivo pareceres/peticoes/112016003968_29409161952216507_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016005819' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925423912 cd_imagem=7657235
O arquivo pareceres/peticoes/112016005819_29409161925423912_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016007141' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161928825302 cd_imagem=7950824
O arquivo pareceres/peticoes/112016007141_29409161928825302_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016008936' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925133981 cd_imagem=7686051
O arquivo pareceres/peticoes/112016008936_29409161925133981_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016013344' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161953718816 cd_imagem=9144516
O arquivo pareceres/peticoes/112016013344_29409161953718816_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016022147' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161953351130 cd_imagem=9107723
O arquivo pareceres/peticoes/112016022147_29409161953351130_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016028205' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161957421672 cd_imagem=9348893
O arquivo pareceres/peticoes/112016028205_29409161957421672_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112017002417' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161952966794 cd_imagem=9127317
O arquivo pareceres/peticoes/112017002417_29409161952966794_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112017011602' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161953647625 cd_imagem=9133061
O arquivo pareceres/peticoes/112017011602_29409161953647625_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112017015838' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161956683126 cd_imagem=9326008
O arquivo pareceres/peticoes/112017015838_29409161956683126_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112018001513' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958546398 cd_imagem=9411171
O arquivo pareceres/peticoes/112018001513_29409161958546398_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112018005056' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161961648902 cd_imagem=9562762
O arquivo pareceres/peticoes/112018005056_29409161961648902_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112018011763' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161946023484 cd_imagem=8665927
O arquivo pareceres/peticoes/112018011763_29409161946023484_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112018011919' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161956739890 cd_imagem=9304964
O arquivo pareceres/peticoes/112018011919_29409161956739890_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112020027002' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162321512934 cd_imagem=10485108
O arquivo pareceres/peticoes/112020027002_29409162321512934_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122014030028' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161953962334 cd_imagem=9168275
O arquivo pareceres/peticoes/122014030028_29409161953962334_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122014030029' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161953962857 cd_imagem=9168264
O arquivo pareceres/peticoes/122014030029_29409161953962857_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122017012058' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161951971662 cd_imagem=9017676
O arquivo pareceres/peticoes/122017012058_29409161951971662_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122019014139' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161931270863 cd_imagem=8007709
O arquivo pareceres/peticoes/122019014139_29409161931270863_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122019018070' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161935302867 cd_imagem=8174975
O arquivo pareceres/peticoes/122019018070_29409161935302867_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122019019741' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161935505806 cd_imagem=8181875
O arquivo pareceres/peticoes/122019019741_29409161935505806_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122019021253' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161922965382 cd_imagem=7462330
O arquivo pareceres/peticoes/122019021253_29409161922965382_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122019025630' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161940055368 cd_imagem=8423865
O arquivo pareceres/peticoes/122019025630_29409161940055368_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020001995' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161931377137 cd_imagem=8019523
O arquivo pareceres/peticoes/122020001995_29409161931377137_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020002476' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942139313 cd_imagem=8520152
O arquivo pareceres/peticoes/122020002476_29409161942139313_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020003658' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161949872750 cd_imagem=8903470
O arquivo pareceres/peticoes/122020003658_29409161949872750_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020006593' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161949377228 cd_imagem=8889291
O arquivo pareceres/peticoes/122020006593_29409161949377228_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020007757' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161938834266 cd_imagem=8371773
O arquivo pareceres/peticoes/122020007757_29409161938834266_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020008510' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161937105112 cd_imagem=8278748
O arquivo pareceres/peticoes/122020008510_29409161937105112_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020013200' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161942139216 cd_imagem=8519088
O arquivo pareceres/peticoes/122020013200_29409161942139216_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020014740' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161943516080 cd_imagem=8572385
O arquivo pareceres/peticoes/122020014740_29409161943516080_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020015607' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161939782677 cd_imagem=8414668
O arquivo pareceres/peticoes/122020015607_29409161939782677_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020015741' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958899347 cd_imagem=9430344
O arquivo pareceres/peticoes/122020015741_29409161958899347_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020017367' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161948009357 cd_imagem=8801046
O arquivo pareceres/peticoes/122020017367_29409161948009357_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020017979' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161938626736 cd_imagem=8353431
O arquivo pareceres/peticoes/122020017979_29409161938626736_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020019588' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161935251332 cd_imagem=8174785
O arquivo pareceres/peticoes/122020019588_29409161935251332_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020019976' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161936901357 cd_imagem=8297702
O arquivo pareceres/peticoes/122020019976_29409161936901357_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020020442' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161947830030 cd_imagem=8817683
O arquivo pareceres/peticoes/122020020442_29409161947830030_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020021164' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161938047574 cd_imagem=8326623
O arquivo pareceres/peticoes/122020021164_29409161938047574_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020022545' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161939908964 cd_imagem=8414291
O arquivo pareceres/peticoes/122020022545_29409161939908964_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020023574' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161935980555 cd_imagem=8215297
O arquivo pareceres/peticoes/122020023574_29409161935980555_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020024087' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161931980437 cd_imagem=8040181
O arquivo pareceres/peticoes/122020024087_29409161931980437_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020024099' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161931980445 cd_imagem=8040336
O arquivo pareceres/peticoes/122020024099_29409161931980445_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020024655' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161944998844 cd_imagem=8642038
O arquivo pareceres/peticoes/122020024655_29409161944998844_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122021004607' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162302626016 cd_imagem=9686756
O arquivo pareceres/peticoes/122021004607_29409162302626016_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122021004615' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958897387 cd_imagem=9430372
O arquivo pareceres/peticoes/122021004615_29409161958897387_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122021004616' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958899681 cd_imagem=9430505
O arquivo pareceres/peticoes/122021004616_29409161958899681_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122021019202' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161949541800 cd_imagem=8889831
O arquivo pareceres/peticoes/122021019202_29409161949541800_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122022012262' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958126569 cd_imagem=9392962
O arquivo pareceres/peticoes/122022012262_29409161958126569_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122022013728' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161957835418 cd_imagem=9400165
O arquivo pareceres/peticoes/122022013728_29409161957835418_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122022017178' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161961302410 cd_imagem=9584540
O arquivo pareceres/peticoes/122022017178_29409161961302410_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122023002744' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162324012100 cd_imagem=10556971
O arquivo pareceres/peticoes/122023002744_29409162324012100_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122023002748' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162324011871 cd_imagem=10556969
O arquivo pareceres/peticoes/122023002748_29409162324011871_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202012011722' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161910994790 cd_imagem=6623749
O arquivo pareceres/peticoes/202012011722_29409161910994790_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202013027692' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161920861113 cd_imagem=7320075
O arquivo pareceres/peticoes/202013027692_29409161920861113_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014000069' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161920956807 cd_imagem=7345005
O arquivo pareceres/peticoes/202014000069_29409161920956807_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014013398' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161915938987 cd_imagem=7096232
O arquivo pareceres/peticoes/202014013398_29409161915938987_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014018347' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161920243096 cd_imagem=7336827
O arquivo pareceres/peticoes/202014018347_29409161920243096_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202015004655' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161918252776 cd_imagem=7388810
O arquivo pareceres/peticoes/202015004655_29409161918252776_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='MU9001502' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161923713557 cd_imagem=7510623
O arquivo pareceres/peticoes/MU9001502_29409161923713557_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI0908127' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161956429238 cd_imagem=9294064
O arquivo pareceres/peticoes/PI0908127_29409161956429238_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI0913949' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161937251984 cd_imagem=8279058
Download concluído: pareceres/peticoes/PI0913949_29409161937251984_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI0922619' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921988990 cd_imagem=7398642
O arquivo pareceres/peticoes/PI0922619_29409161921988990_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1005695' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161926847562 cd_imagem=7808588
Download concluído: pareceres/peticoes/PI1005695_29409161926847562_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1011883' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925017264 cd_imagem=7611019
O arquivo pareceres/peticoes/PI1011883_29409161925017264_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1011888' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161928602133 cd_imagem=7946252
O arquivo pareceres/peticoes/PI1011888_29409161928602133_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1012651' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161920756999 cd_imagem=7319287
O arquivo pareceres/peticoes/PI1012651_29409161920756999_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1013288' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921176490 cd_imagem=7335330
O arquivo pareceres/peticoes/PI1013288_29409161921176490_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1013657' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161928231232 cd_imagem=7929842
O arquivo pareceres/peticoes/PI1013657_29409161928231232_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1013904' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161928532259 cd_imagem=7935166
O arquivo pareceres/peticoes/PI1013904_29409161928532259_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1014277' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161928726045 cd_imagem=7955270
O arquivo pareceres/peticoes/PI1014277_29409161928726045_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1103669' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161927769239 cd_imagem=7898058
O arquivo pareceres/peticoes/PI1103669_29409161927769239_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1105730' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161940055317 cd_imagem=8423323
O arquivo pareceres/peticoes/PI1105730_29409161940055317_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1106900' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161926815539 cd_imagem=7864489
O arquivo pareceres/peticoes/PI1106900_29409161926815539_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1106311' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161940812452 cd_imagem=8496719
O arquivo pareceres/peticoes/PI1106311_29409161940812452_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102019009508' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162324508806 cd_imagem=10618908
O arquivo pareceres/peticoes/102019009508_29409162324508806_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014022400' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925951625 cd_imagem=7729558
O arquivo pareceres/peticoes/102014022400_29409161925951625_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102014027536' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925830755 cd_imagem=7725847
O arquivo pareceres/peticoes/102014027536_29409161925830755_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102022000499' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162317780911 cd_imagem=10344623
O arquivo pareceres/peticoes/102022000499_29409162317780911_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112013000811' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161923234365 cd_imagem=7486682
O arquivo pareceres/peticoes/112013000811_29409161923234365_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112014032792' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921593848 cd_imagem=7390604
O arquivo pareceres/peticoes/112014032792_29409161921593848_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015030032' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925527580 cd_imagem=7706490
O arquivo pareceres/peticoes/112015030032_29409161925527580_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015030093' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925835340 cd_imagem=7728738
O arquivo pareceres/peticoes/112015030093_29409161925835340_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016000345' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925823473 cd_imagem=7746143
O arquivo pareceres/peticoes/112016000345_29409161925823473_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112016003644' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921695934 cd_imagem=7371003
O arquivo pareceres/peticoes/112016003644_29409161921695934_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112022018674' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162319492565 cd_imagem=10420346
O arquivo pareceres/peticoes/112022018674_29409162319492565_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122016008192' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958126321 cd_imagem=9393245
O arquivo pareceres/peticoes/122016008192_29409161958126321_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122016008203' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161958126313 cd_imagem=9399720
O arquivo pareceres/peticoes/122016008203_29409161958126313_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='122020001985' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161925752630 cd_imagem=7754304
O arquivo pareceres/peticoes/122020001985_29409161925752630_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1012905' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161923904573 cd_imagem=7545362
O arquivo pareceres/peticoes/PI1012905_29409161923904573_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102013024752' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921681054 cd_imagem=7391213
O arquivo pareceres/peticoes/102013024752_29409161921681054_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI0815837' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161811426807 cd_imagem=5656349
Download concluído: pareceres/peticoes/PI0815837_29409161811426807_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015002739' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921635311 cd_imagem=7365219
O arquivo pareceres/peticoes/112015002739_29409161921635311_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='PI1006418' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161921934394 cd_imagem=7390904
O arquivo pareceres/peticoes/PI1006418_29409161921934394_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='112015020079' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161922058210 cd_imagem=7406048
O arquivo pareceres/peticoes/112015020079_29409161922058210_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202015005230' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161922413541 cd_imagem=7441845
O arquivo pareceres/peticoes/202015005230_29409161922413541_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202014006525' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409161923538828 cd_imagem=7509994
O arquivo pareceres/peticoes/202014006525_29409161923538828_214.pdf já existe. Nada foi gravado.
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='202019004832' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162305512372 cd_imagem=9866587
Download concluído: pareceres/peticoes/202019004832_29409162305512372_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102023026373' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162334558610 cd_imagem=10910735
Download concluído: pareceres/peticoes/102023026373_29409162334558610_214.pdf
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM despachos_pag where numero='102022016594' and tipo_peticao='214'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

numnossonumero=29409162341437750 cd_imagem=11127131
O arquivo pareceres/peticoes/102022016594_29409162341437750_214.pdf já existe. Nada foi gravado.

In [27]:
# Expressão regular para pegar conteúdo até "Rio de Janeiro"
match = re.search(r"(Conclusão.*?)(?=Rio de Janeiro)", texto_relatorio, flags=re.S)

if match:
    conclusao = re.sub(r"\s+", " ", match.group(1)).strip()
    print("Conclusão extraída:\n")
    conclusao = conclusao.replace("Conclusão", "")
    conclusao = conclusao.replace("Assim sendo,", "")
    conclusao = conclusao.split("De acordo com o Art. 212")[0].strip()
    conclusao = conclusao[0].upper() + conclusao[1:]
    
    print(conclusao)
else:
    print("Trecho não encontrado.")

Conclusão extraída:

De acordo com o Art. 37, indefiro o presente pedido, uma vez que não atende ao requisito de atividade inventiva (Art. 8º combinado com Art. 13 da LPI) e não é considerado invenção, incidindo no Art. 10 da LPI.

In [39]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = f"select * from carga where numero<>'NUMERO' and numero not in (select numero from anterioridades_desc) and numero in (select numero from arquivados where despacho='12.2')"
# teste se existe algum pedido na carga com 12.2 que ainda não tenha registro em anterioridades_desc:
# f"SELECT * FROM `carga` WHERE numero<>'NUMERO' and numero not in (select numero from anterioridades_desc) and numero in (select numero from arquivados where despacho='12.2');"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
#print(resultado)
lista = df.values.tolist()
if df.shape[1] > 1:
    lista = df.iloc[:, 0].tolist()
else:
    lista = []
lista.insert(0, 'numero')
print(lista)

['numero']

In [29]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = f"select * from anterioridades_desc where descricao='' and numero in (select numero from arquivados where despacho='12.2');"
#comando = "SELECT * FROM carga WHERE numero not in (select numero from anterioridades_desc) and numero in (select numero from arquivados where despacho='12.2')"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
#print(resultado)
lista = df.values.tolist()
if not df.empty and df.shape[1] > 0:
    lista = df.iloc[:, 1].tolist() # ou entao lista = df.iloc[:, 0].tolist()
    lista.insert(0, 'numero')
else:
    lista = []
print(lista)

[]

In [15]:
import os
from dotenv import load_dotenv
load_dotenv(dotenv_path='.env', override=True)
openai_api_key = os.getenv("OPENAI_API_KEY")

In [ ]:
# ******************************************INSERT ANTERIORIDADES_DESC CAMPO DESCRICAO COM DISCUSSÃO DA ATIVIDADE INVENTIVA
# certifique-se de rodar a rotina acima conectar_siscap e de esta a VPN ligada
# SELECT * FROM `carga` WHERE numero not in (select numero from anterioridades_desc)
# UPDATE anterioridades_desc SET descricao = REPLACE(descricao, 'D1, D2, D3 e D4', 'de anterioridade') WHERE descricao LIKE '%D1, D2, D3 e D4%';


import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
from langchain.prompts.prompt import PromptTemplate

def format_as_single_paragraph(text):
    # Remove quebras de linha e espaços extras
    formatted_text = ' '.join(line.strip() for line in text.splitlines() if line.strip())
    return formatted_text
    
load_dotenv(dotenv_path='.env', override=True)
openai_api_key = os.getenv("OPENAI_API_KEY")
url_openai = "https://api.openai.com/v1/chat/completions"

query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM carga" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
json_data = conectar_siscap(url,return_json=True)
data = json.loads(json_data)
#data["patents"] = ['numero','102012004629','102012010730','102012019427','102014030124','112012027022','112012028907','112013027095','112014014375','112017016792','122014023771','122019021332','202013016285','PI0705574','PI0708406','PI0800529','PI0902841','PI1102778','PI1102785'] # lista de numeros especificos
data["patents"] = lista
for i in range(1, len(data["patents"])):
    #if i==2: break
    #numero = data["patents"][i]["numero"]
    numero = data["patents"][i] # para ler a lista de numeros especificos

    #query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
    query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where (decisao='indeferimento' or decisao='ciencia de parecer') and numero='{numero}'" + ' order by rpi desc"'
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
    print(url)
    try:
        json_data = conectar_siscap(url,return_json=True)
        data1 = json.loads(json_data)
        codigo = data1["patents"][0]["codigo"]
        divisao = data1["patents"][0]["divisao"]    
        
        url = f"https://siscap.inpi.gov.br/adm/pareceres/{divisao}/{numero}{codigo}.txt"
        print(url)
        texto_relatorio = conectar_siscap(url,return_json=False)
        ##print(texto_relatorio)
    
        url = "https://api.openai.com/v1/chat/completions"
        query = f"Selecione no texto seguinte apenas a parte que fala das diferenças com os documentos do estado da técnica e discute a atividade inventiva {texto_relatorio}"
        data_json = {
            "model": "gpt-5-mini",  # Use o modelo desejado, como 'gpt-4'
            "messages": [
                {"role": "user", "content": query}
            ]
        }
        headers = {
            "Authorization": f"Bearer {openai_api_key}",
            "Content-Type": "application/json"
        }
        response = requests.post(url, headers=headers, json=data_json, verify=False)
        if response.status_code == 200:
            resposta = response.json()
            resumo = resposta['choices'][0]['message']['content']
            resumo = resumo.replace("'","")
            resumo = resumo.replace('"',"")
            resumo = resumo.replace('---',"")
            resumo = resumo.replace('',',')
            resumo = resumo.replace('',',')
            resumo = resumo.replace('',',')
            resumo = resumo.replace('',',')
            resumo = resumo.replace('O trecho que fala sobre as diferenças com os documentos D1, D2, D3 e D4 e discute a atividade inventiva é o seguinte:','')
            resumo = resumo.replace('O trecho que fala das diferenças com os documentos D1, D2, D3 e D4 e discute a atividade inventiva é o seguinte:','')
            resumo = resumo.replace('A parte do texto que fala das diferenças com os documentos D1, D2, D3 e D4 e discute a atividade inventiva é a seguinte:','')
            resumo = resumo.replace('A parte do texto que fala sobre as diferenças com os documentos D1, D2, D3 e D4 e discute a atividade inventiva é a seguinte:','')
            resumo = resumo.replace('A parte que fala sobre as diferenças com os documentos D1, D2, D3 e D4 e discute a atividade inventiva é a seguinte:','')
            resumo = resumo.replace('A parte que fala das diferenças com os documentos D1, D2, D3 e D4 e discute a atividade inventiva é a seguinte:','')
            resumo = resumo.replace('Segue a parte do texto que fala sobre as diferenças com os documentos D1, D2, D3 e D4 e discute a atividade inventiva','')
            resumo = format_as_single_paragraph(resumo)
            sql_resumo = f"INSERT IGNORE INTO anterioridades_desc (id,numero,descricao) VALUES (null, '{numero}','{resumo}');"
            print(sql_resumo)
        else:
            print(f"Erro {response.status_code}: {response.text}")
            
        #if i == 2:
            #break
    except Exception as e:
        print(f"Não achei parecer de indeferimento {numero} {e}")

In [94]:
lista1[0][2]

'O pedido de patente não apresenta características inventivas e sofre de falta de clareza em determinar as características que deseja proteger. Conforme os documentos D1 e D3, a Requerente reformulou a reivindicação 1 sem revelar os elementos inventivos que a distinguem da matéria conhecida. Praticamente todos os componentes descritos na reivindicação, como rede resistiva, sensor, conversor A/D, processador e interface homem-máquina, já são conhecidos em equipamentos cirúrgicos, fato já abordado em parecer anterior. A única característica que poderia diferenciar a invenção seria a rede resistiva simulando diferentes tipos de tecido, incluindo o fator de crista. No entanto, essa simulação é implícita em muitos equipamentos, como demonstrado no documento D1 ([0188]), que descreve um circuito analisador de rede de baixa tensão usado para medir a impedância da ferramenta antes que a energia de RF seja acionada. D1 também inclui sensores de corrente ([0182]; [0183]) e medição de corrente de fuga ([0187]), entre outros procedimentos. Embora o fator de crista não seja explicitamente mencionado em D1, seria óbvio para um técnico na área, considerando a informação contida neste documento. Além disso, o documento D3 menciona a medição do fator de crista (col. 5, lin. 56-col. 6, lin 4) e sugere que tal procedimento já faz parte do estado da técnica (col. 2, lin. 20-24). Assim, reafirma-se a conclusão do parecer anterior de que D1 e D3 são documentos antecipatórios, retirando a matéria da atividade inventiva.'

In [95]:
lista1[0][3]

'Conclui-se que a o pedido, através da reivindicação 1, não apresenta características inventivas e sofre de falta de clareza em determinar as características que deseja proteger. de acordo com o Art. 37, indefiro o presente pedido, uma vez que: não atende ao requisito de atividade inventiva (Art.8º combinado com Art. 13 da LPI) as reivindicações estão indefinidas e/ou não estão fundamentadas no relatório descritivo (Art. 25 da LPI)'

In [174]:
comando = """
SELECT codigo, doc
FROM anterioridades
WHERE numero = '102012000669'
"""

cursor.execute(comando)
resultado = cursor.fetchall()

string_final = ", ".join(f"{codigo} {doc}" for codigo, doc in resultado)

print(string_final)

D1 US7200549, D2 US2008037833, D3 US7962754

In [122]:
query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM anterioridades_desc where numero='102012019230'" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
json_data = conectar_siscap(url,return_json=True)
try:
    data = json.loads(json_data)
    print(data['patents'][0]['descricao'])
    print(data['patents'][0]['numero'])
except:
    print("fim")

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

O pedido de patente não apresenta características inventivas e sofre de falta de clareza em determinar as características que deseja proteger. Conforme os documentos D1 e D3, a Requerente reformulou a reivindicação 1 sem revelar os elementos inventivos que a distinguem da matéria conhecida. Praticamente todos os componentes descritos na reivindicação, como rede resistiva, sensor, conversor A/D, processador e interface homem-máquina, já são conhecidos em equipamentos cirúrgicos, fato já abordado em parecer anterior. A única característica que poderia diferenciar a invenção seria a rede resistiva simulando diferentes tipos de tecido, incluindo o fator de crista. No entanto, essa simulação é implícita em muitos equipamentos, como demonstrado no documento D1 ([0188]), que descreve um circuito analisador de rede de baixa tensão usado para medir a impedância da ferramenta antes que a energia de RF seja acionada. D1 também inclui sensores de corrente ([0182]; [0183]) e medição de corrente de fuga ([0187]), entre outros procedimentos. Embora o fator de crista não seja explicitamente mencionado em D1, seria óbvio para um técnico na área, considerando a informação contida neste documento. Além disso, o documento D3 menciona a medição do fator de crista (col. 5, lin. 56-col. 6, lin 4) e sugere que tal procedimento já faz parte do estado da técnica (col. 2, lin. 20-24). Assim, reafirma-se a conclusão do parecer anterior de que D1 e D3 são documentos antecipatórios, retirando a matéria da atividade inventiva.
102012019230

In [120]:
import urllib
numero = '102012019230'
query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where (decisao='indeferimento' or decisao='ciencia de parecer') and numero='{numero}'" + ' order by rpi desc"'
query = '{"mysql_query":" * FROM pedido WHERE (decisao=\'indeferimento\' or decisao=\'ciencia de parecer\') and numero=\'102012019230\'"}'
query = urllib.parse.quote(query)
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
print(url)
try:
    json_data = conectar_siscap(url,return_json=True)
    data1 = json.loads(json_data)
    codigo = data1["patents"][0]["codigo"]
    divisao = data1["patents"][0]["divisao"]  
    print(f"{codigo} {divisao}")
except:
    print("fim")

https://cientistaspatentes.com.br/apiphp/patents/query/?q=%7B%22mysql_query%22%3A%22%20%2A%20FROM%20pedido%20WHERE%20%28decisao%3D%27indeferimento%27%20or%20decisao%3D%27ciencia%20de%20parecer%27%29%20and%20numero%3D%27102012019230%27%22%7D

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

1341579 difel

In [ ]:
for i in range(1, len(data["patents"])):
    if i==5: break
    #numero = data["patents"][i]["numero"]
    numero = data["patents"][i] # para ler a lista de numeros especificos
    print(numero)
    #query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
    query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM anterioridades_desc where numero='{numero}'" + ' "'
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
    print(url)
    try:
        json_data = conectar_siscap(url,return_json=True)
        data1 = json.loads(json_data)
        print(data1['patents'][0]['descricao'])
    except:
        print("fim")

In [121]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

numero='102012019230'
#numero='102012000669'
comando = f"SELECT codigo, doc FROM anterioridades WHERE numero = '{numero}'"
print(comando)
cursor.execute(comando)
resultado = cursor.fetchall()
documentos = ", ".join(f"{codigo} {doc}" for codigo, doc in resultado)
print(documentos)

SELECT codigo, doc FROM anterioridades WHERE numero = '102012019230'
D1 US2009/0248007, D2 US6251106

In [188]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

numero='102012000669'
comando = f"""
SELECT codigo, doc
FROM anterioridades
WHERE numero = '{numero}'
"""

cursor.execute(comando)
resultado = cursor.fetchall()

string_final = ", ".join(f"{codigo} {doc}" for codigo, doc in resultado)
print(string_final)

D1 US7200549, D2 US2008037833, D3 US7962754

In [77]:
load_dotenv(dotenv_path='.env')
openai_api_key = os.getenv("OPENAI_API_KEY")
#print(openai_api_key)

In [142]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = f"select * from anterioridades_desc where razoes='' AND numero in (select numero from carga) and numero in (select numero from arquivados where despacho='12.2')"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
#print(resultado)
lista = df.values.tolist()
lista1 = lista
lista = df.iloc[:, 1].tolist()
lista.insert(0, 'numero')
print(lista)

['numero', '122020019318', 'PI0800882', 'PI1102046', '102015012164', '102020011926', '112012028948', '112013008699', '112013017632', '112013019574', '112013023949', '112013027818', '112014009255', '112015001636', '112016022470', '112017023256', '112018012940', '122014016517', '122017027292', '122018015962', '122018076834', '122019015933', '122019018135', '122019021564', '122019021573', '122019021574', '122019021606', '122019022733', '122019027403', '122020007845', 'PI0608212', 'PI0716315', 'PI0811199', 'PI0822775', 'PI1001007', 'PI1004183', 'PI1005131', 'PI1010581', '122014023771', 'PI0708406', '102017021019', '102012010569', '102012010570', '102012010739', '102012012377', '102012014137', '102012014826', '102012028509', '102013013198', '102013020660', '102013024252', '102014018446', '102014027711', '102014031238', '102016023997', '112012007854', '112012010673', '112012013166', '112012017257', '112012022998', '112012025948', '112012026730', '112012030329', '112012030594', '112012033370', '112013000481', '112013001671', '112013004702', '112013007315', '112013009001', '112013014036', '112013019993', '112013024824', '112013025259', '112013030199', '112013033021', '112013033652', '112014000614', '112014000630', '112014002091', '112014003039', '112014005428', '112014005614', '112014009556', '112014010347', '112014010374', '112014012138', '112014018066', '112014022126', '112014027978', '112014028250', '112014028451', '112014030434', '112014031423', '112015000416', '112015000467', '112015001686', '112015004775', '112015006953', '112015008704', '112015010392', '112015013286', '112015014477', '112015019646', '112015023140', '112015029441', '112015031143', '112015032570', '112016013498', '112016020715', '112017018609', '112017022287', '112019009518', '112020004793', '112020006283', '112020008628', '112020010102', '112020019522', '112020019958', '112021004036', '112021007409', '112021009213', '122014021216', '122016004716', '122017013108', '122017014493', '122017015900', '122019007621', '122019012011', '122019014571', '122019016675', '122019018657', '122019018682', '122019019863', '122019022818', '122019024228', '122019024427', '122019025423', '122019027002', '122020000568', '122020001727', '122020004305', '122020006492', '122020008377', '122020010712', '122020014060', '122020017751', '122020021367', '122020022771', '122020026460', '122021001638', '122021004669', '122021005431', '122021007422', '122021007885', '122021009061', '122021014646', '122021015574', '122021019435', '122021020387', '122021024755', '122021025799', '122022001757', '122022005277', '122022009448', '122022017025', '122022022168', '202012019932', '202012021322', '202012022838', '202012023192', '202012023481', '202012026251', '202012030369', '202012030729', '202013002255', '202013003796', '202013003912', '202013009916', '202013012933', '202013014629', '202013018205', '202013019250', '202013024035', '202013025439', '202013030643', '202013032734', '202013033354', '202014007119', '202014008647', '202014010304', '202014026188', '202014031373', 'MU9001586', 'MU9100235', 'MU9100240', 'MU9100581', 'MU9101438', 'PI0802657', 'PI0815327', 'PI0900922', 'PI0901926', 'PI0903718', 'PI0906612', 'PI0906951', 'PI0907077', 'PI0908129', 'PI0911269', 'PI0912225', 'PI0914086', 'PI0919409', 'PI0919693', 'PI0920465', 'PI0921237', 'PI1000672', 'PI1003946', 'PI1004418', 'PI1004831', 'PI1005286', 'PI1005697', 'PI1007620', 'PI1010927', 'PI1015053', 'PI1015078', 'PI1102208', 'PI1103692', 'PI1103710', 'PI1105561', 'PI1105999', '102012014413', '102012015992', '102013009882', '102013016609', '102013029155', '102014013996', '102014015576', '102016016661', '102016028509', '112012016789', '112013001754', '112013003657', '112013022154', '112014011279', '112014022817', '112015003727', '112015019603', '112016015685', '112016029719', '112018007527', '122019017408', '122020006873', '122020009181', '122020024458', '122021013192', '122021019888', '122021020408', '202012004260', '202012008411', '202012019591', '202012022845', '202013013463', '202014012390', 'MU9000951', 'MU9002515', 'MU9100724', 'PI0912882', 'PI0917535', 'PI1013364', 'PI1102628', 'PI1104989', '102012004079', '102012010956', '102012013367', '102012021084', '102012023815', '102012030377', '102012030828', '102012032591', '102012032927', '102013011905', '102013014262', '102013023577', '102013028660', '102013030975', '102014002008', '102014012053', '102014013800', '102014013993', '102014017842', '102014024578', '102014030105', '102015006648', '102015017609', '102016015976', '102016024247', '102017001568', '102019023319', '112012017243', '112012026297', '112012026999', '112012029457', '112012029982', '112012030349', '112013003772', '112013004244', '112013004888', '112013005711', '112013007644', '112013015675', '112013017629', '112013018454', '112013018740', '112013021524', '112013023748', '112013024512', '112013026179', '112013028037', '112013028285', '112013032901', '112013033182', '112014000676', '112014000985', '112014002748', '112014006871', '112014008804', '112014009228', '112014009565', '112014010783', '112014019190', '112014026167', '112014028369', '112015000104', '112015002586', '112015005059', '112015006343', '112015008215', '112015010247', '112015013260', '112015014017', '112015014726', '112015014925', '112015015060', '112015016235', '112015018808', '112015021619', '112015023151', '112015027158', '112015028942', '112015029135', '112015030335', '112016002195', '112016002915', '112016003968', '112016005819', '112016007141', '112016008936', '112016013344', '112016022147', '112016028205', '112017002417', '112017011602', '112017015838', '112018001513', '112018005056', '112018011763', '112018011919', '112020027002', '112021001434', '122014030028', '122014030029', '122017012058', '122019014139', '122019018070', '122019019741', '122019021253', '122019025630', '122020001995', '122020002476', '122020003658', '122020006593', '122020007757', '122020008510', '122020013200', '122020014740', '122020015607', '122020015741', '122020017367', '122020017979', '122020019588', '122020019976', '122020020442', '122020021164', '122020022545', '122020023574', '122020024087', '122020024099', '122020024655', '122021004607', '122021004615', '122021004616', '122021019202', '122022012262', '122022013728', '122022017178', '122023002744', '122023002748', '132015013589', '202012011722', '202013027692', '202014000069', '202014013398', '202014018347', '202015004655', 'MU9001502', 'PI0805704', 'PI0908127', 'PI0922619', 'PI1008829', 'PI1011883', 'PI1011888', 'PI1012651', 'PI1013288', 'PI1013657', 'PI1013904', 'PI1014277', 'PI1103669', 'PI1105730', 'PI1106900', '102012004873', '102012010955', '102012021502', '102013005581', '102013009462', '102013016347', '102013017278', '102013019615', '102013019765', '102013025651', '102014010402', '102014013268', '102014021906', '102014024348', '102014025902', '102015007934', '102015017470', '102015019612', '102016017825', '102016027868', '102019010055', '102019010089', '102021003860', '112012000797', '112012005760', '112012006346', '112012008159', '112012008983', '112012009857', '112012009894', '112012011128', '112012023009', '112012023010', '112012024332', '112012029640', '112012030718', '112012032204', '112013000650', '112013003250', '112013003612', '112013008017', '112013009452', '112013010362', '112013013225', '112013018954', '112013019022', '112013019699', '112013020533', '112013022907', '112013022994', '112013023801', '112013024608', '112013025238', '112013027540', '112013028716', '112013029300', '112013029498', '112014000495', '112014001086', '112014001387', '112014007027', '112014008278', '112014009269', '112014009986', '112014011387', '112014011919', '112014014731', '112014019937', '112014020793', '112014024641', '112014027287', '112015013863', '112015019008', '112015019446', '112015021010', '112015031016', '112015032811', '112016003414', '112016004649', '112016005389', '112016006522', '112016006534', '112016006613', '112016008784', '112016010521', '112016015157', '112016015158', '112016018219', '112016021786', '112016023062', '112018004107', '112018009927', '112020011171', '112021012379', '122019008317', '122019012495', '122019014601', '122019017348', '122019018710', '122019019161', '122019020154', '122019022840', '122019026828', '122019026829', '122020004657', '122020013414', '122020013577', '122020016644', '122020017092', '122020017889', '122020022012', '122020022821', '122020024337', '122020026570', '122020026576', '122021003228', '122021006465', '122021015578', '122021022394', '122022007908', '122022012256', '122022017195', '122022019084', '122022020636', '122023002765', '122023019756', '202012022499', '202013017528', '202014000433', '202014013394', '202014016230', '202014017096', '202014025663', '202015030495', '202020012873', 'PI0817478', 'PI0919236', 'PI0919841', 'PI1001299', 'PI1003746', 'PI1003760', 'PI1004208', 'PI1012956', 'PI1015976', 'PI1100371', 'PI1103116', 'PI1104976', 'PI1106311', '102019009508', '102014025472', '102018000306', '102023026277', '202023008288', '202023017241', 'PI1006418', '102014022400', '102014027536', '102020006622', '102022000499', '112013000811', '112014032792', '112015030032', '112015030093', '112016000345', '112016003644', '112021013435', '112022018674', '122016008192', '122016008203', '122020001985', '122020022312', '202017011129', 'PI0906181', 'PI1012905']

In [21]:
# ******************************************ATUALIZA ANTERIORIDADES_DESC CAMPO RAZOES COM RAZOES INDEFERIMENTO
# certifique-se de rodar a rotina acima conectar_siscap e de esta a VPN ligada
# SELECT * FROM `carga` WHERE numero not in (select numero from anterioridades_desc)
# UPDATE anterioridades_desc SET descricao = REPLACE(descricao, 'D1, D2, D3 e D4', 'de anterioridade') WHERE descricao LIKE '%D1, D2, D3 e D4%';
# esta rotina usa o openai
# https://platform.openai.com/settings/organization/billing/overview

import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
from langchain.prompts.prompt import PromptTemplate

def format_as_single_paragraph(text):
    # Remove quebras de linha e espaços extras
    formatted_text = ' '.join(line.strip() for line in text.splitlines() if line.strip())
    return formatted_text
    
load_dotenv(dotenv_path='.env')
openai_api_key = os.getenv("OPENAI_API_KEY")
url_openai = "https://api.openai.com/v1/chat/completions"

query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM carga" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
json_data = conectar_siscap(url,return_json=True)
data = json.loads(json_data)
data["patents"] = ['102014022400','102014025472','102014027536','102018000306','102019009508','102020006622','102022000499','102023026277','112013000811','112014032792','112015030032','112015030093','112016000345','112016003644','112021013435','112022018674','122016008192','122016008203','122020001985','122020022312','122021015578','122021022394','122022007908','122022012256','122022017195','122022019084','122022020636','122023002765','122023019756','202012022499','202013017528','202014000433','202014013394','202014016230','202014017096','202014025663','202015030495','202017011129','202020012873','202023008288','202023017241','PI0817478','PI0906181','PI0919236','PI0919841','PI1001299','PI1003746','PI1003760','PI1004208','PI1006418','PI1012905','PI1012956','PI1015976','PI1100371','PI1103116','PI1104976','PI1106311'] # lista de numeros especificos 102012004629, 102012000669, 102012019230
#data["patents"] = lista
for i in range(1, len(data["patents"])):
    #if i==5: break
    numero = data["patents"][i]

    comando = f"SELECT codigo, doc FROM anterioridades WHERE numero = '{numero}'"
    print(comando)
    cursor.execute(comando)
    resultado = cursor.fetchall()
    documentos = ", ".join(f"{codigo} {doc}" for codigo, doc in resultado)
    #print(documentos)
    
    #query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
    query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM anterioridades_desc where numero='{numero}'" + ' "'
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
    print(url)
    try:
        json_data = conectar_siscap(url,return_json=True)
        data1 = json.loads(json_data)
        descricao = data1['patents'][0]['descricao']
        conclusao = data1['patents'][0]['conclusao']
   
        url = "https://api.openai.com/v1/chat/completions"
        if (documentos==''):
            query = f"""Voce é um assistente administrativo que deve identificar os artigos da LPI que fundamentam o indeferimento de um pedido de patente 
            tendo em vista a conclusão do parecer: ###{conclusao}###. No final 
            escreva no seguinte formato, citando apenas os artigos mencionados na conclusão do parecer indicando se trata de D1, D2, etc.. seguindo a 
            mesma nomeclatura em {documentos}: 'o artigo 25 por falta de clareza, o artigo 6° por dupla proteção, o artigo 32 por acréscimo de matéria, 
            a combinação dos artigos 8° e 11 por falta de novidade, 
            a combinação dos artigos 8° e 13 por falta de atividade inventiva diante dos documentos XXXXX, XXXXX, etc... (mantenha a mesma identificação
            de cada documento conforme {documentos},
            o artigo 10 inciso III por não ser considerado invenção, o artigo 18 inciso III or não ser considerado matéria patenteável, 
            o artigo 24 por insuficiência descritiva, o artigo 15 por falta de aplicação industrial'. Não faça referência ao artigo 37.
            Exiba como resposta simplesmente o texto final no formato solicitado
            """
        else:
            query = f"""Voce é um assistente administrativo que deve identificar os artigos da LPI que fundamentam o indeferimento de um pedido de patente 
            tendo em vista a conclusão do parecer: ###{conclusao}###. Se uma das razões for falta de atividade inventiva, cite os documentos usados para sua
            fundamentação, tendo em vista a discussão no parecer: ###{descricao}###. Identifique os documentos de patente tendo em vista {documentos}. 
            No final escreva no seguinte formato, citando apenas os artigos mencionados na conclusão do parecer e os documentos, indicando 
            se trata de D1, D2, etc.. seguindo a mesma nomeclatura em {documentos} : 'o artigo 25 por falta de clareza, o artigo 6° por dupla proteção, 
            o artigo 32 por acréscimo de matéria, a combinação dos artigos 8° e 11 por falta de novidade, 
            a combinação dos artigos 8° e 13 por falta de atividade inventiva diante dos documentos XXXXX, XXXXX, etc... (mantenha a mesma identificação
            de cada documento conforme {documentos},
            o artigo 10 inciso III por não ser considerado invenção, o artigo 18 inciso III or não ser considerado matéria patenteável, 
            o artigo 24 por insuficiência descritiva, o artigo 15 por falta de aplicação industrial'. Não faça referência ao artigo 37.
            Exiba como resposta simplesmente o texto final no formato solicitado
            """

        #print(query)
        data_json = {
            "model": "gpt-5-mini",  # Use o modelo desejado, como 'gpt-4'
            "messages": [
                {"role": "user", "content": query}
            ]
        }
        headers = {
            "Authorization": f"Bearer {openai_api_key}",
            "Content-Type": "application/json"
        }
        response = requests.post(url, headers=headers, json=data_json, verify=False)
        if response.status_code == 200:
            resposta = response.json()
            resumo = resposta['choices'][0]['message']['content']
            resumo = resumo.replace("'","")
            resumo = resumo.replace('"',"")
            resumo = resumo.replace('---',"")
            resumo = resumo.replace('',',')
            resumo = resumo.replace('',',')
            resumo = resumo.replace('',',')
            resumo = resumo.replace('',',')
            resumo = format_as_single_paragraph(resumo)
            print(resumo)
            sql_razoes = f"UPDATE anterioridades_desc set razoes='{resumo}' WHERE numero='{numero}';"
            print(sql_razoes)
        else:
            print(f"Erro {response.status_code}: {response.text}")
            
    except Exception as e:
        print(f"Não achei parecer de indeferimento {numero} {e}")

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

SELECT codigo, doc FROM anterioridades WHERE numero = '102014025472'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='102014025472' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Não achei parecer de indeferimento 102014025472 Expecting value: line 1 column 14 (char 13)
SELECT codigo, doc FROM anterioridades WHERE numero = '102014027536'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='102014027536' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '102018000306'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='102018000306' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Não achei parecer de indeferimento 102018000306 Expecting value: line 1 column 14 (char 13)
SELECT codigo, doc FROM anterioridades WHERE numero = '102019009508'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='102019009508' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '102020006622'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='102020006622' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '102022000499'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='102022000499' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '102023026277'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='102023026277' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Não achei parecer de indeferimento 102023026277 Expecting value: line 1 column 14 (char 13)
SELECT codigo, doc FROM anterioridades WHERE numero = '112013000811'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='112013000811' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '112014032792'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='112014032792' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '112015030032'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='112015030032' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '112015030093'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='112015030093' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '112016000345'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='112016000345' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '112016003644'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='112016003644' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '112021013435'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='112021013435' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '112022018674'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='112022018674' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122016008192'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122016008192' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122016008203'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122016008203' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122020001985'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122020001985' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122020022312'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122020022312' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122021015578'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122021015578' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122021022394'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122021022394' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122022007908'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122022007908' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122022012256'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122022012256' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122022017195'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122022017195' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122022019084'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122022019084' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122022020636'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122022020636' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122023002765'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122023002765' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '122023019756'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='122023019756' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202012022499'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202012022499' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202013017528'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202013017528' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202014000433'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202014000433' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202014013394'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202014013394' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202014016230'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202014016230' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202014017096'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202014017096' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202014025663'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202014025663' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202015030495'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202015030495' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202017011129'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202017011129' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202020012873'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202020012873' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = '202023008288'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202023008288' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Não achei parecer de indeferimento 202023008288 Expecting value: line 1 column 14 (char 13)
SELECT codigo, doc FROM anterioridades WHERE numero = '202023017241'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='202023017241' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Não achei parecer de indeferimento 202023017241 Expecting value: line 1 column 14 (char 13)
SELECT codigo, doc FROM anterioridades WHERE numero = 'PI0817478'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI0817478' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI0906181'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI0906181' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI0919236'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI0919236' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI0919841'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI0919841' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1001299'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1001299' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1003746'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1003746' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1003760'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1003760' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1004208'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1004208' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1006418'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1006418' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Não achei parecer de indeferimento PI1006418 Expecting value: line 1 column 14 (char 13)
SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1012905'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1012905' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1012956'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1012956' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1015976'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1015976' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1100371'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1100371' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1103116'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1103116' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1104976'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1104976' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

SELECT codigo, doc FROM anterioridades WHERE numero = 'PI1106311'
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM anterioridades_desc where numero='PI1106311' "

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Erro 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [ ]:
# ******************************************ATUALIZA ANTERIORIDADES_DESC CAMPO RAZOES COM RAZOES INDEFERIMENTO
# certifique-se de rodar a rotina acima conectar_siscap e de esta a VPN ligada
# SELECT * FROM `carga` WHERE numero not in (select numero from anterioridades_desc)
# UPDATE anterioridades_desc SET descricao = REPLACE(descricao, 'D1, D2, D3 e D4', 'de anterioridade') WHERE descricao LIKE '%D1, D2, D3 e D4%';
# esta rotina usa o gemini, rodar no ambiente python_inpi

import os
from dotenv import load_dotenv
from langchain_core.output_parsers import StrOutputParser
#from langchain.prompts.prompt import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

def format_as_single_paragraph(text):
    # Remove quebras de linha e espaços extras
    formatted_text = ' '.join(line.strip() for line in text.splitlines() if line.strip())
    return formatted_text
    
load_dotenv(dotenv_path='.env', override=True)
gemini_api_key = os.getenv("HELENO_API_KEY")
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=gemini_api_key)


#query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM carga" + '"'
#url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
#json_data = conectar_siscap(url,return_json=True)
#data = json.loads(json_data)
#data["patents"] = ['numero','102022011377'] # lista de numeros especificos
data["patents"] = lista
for i in range(1, len(data["patents"])):
    #if i==5: break
    numero = data["patents"][i]

    documentos = ''
    comando = f"SELECT codigo, doc FROM anterioridades WHERE numero = '{numero}'"
    print(comando)
    cursor.execute(comando)
    resultado = cursor.fetchall()
    documentos = ", ".join(f"{codigo} {doc}" for codigo, doc in resultado)
    print(f"Documentos: {documentos}")
    
    #query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
    query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM anterioridades_desc where numero='{numero}'" + ' "'
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
    print(url)
    try:
        json_data = conectar_siscap(url,return_json=True)
        data1 = json.loads(json_data)
        descricao = data1['patents'][0]['descricao']
        conclusao = data1['patents'][0]['conclusao']
   
        if (documentos==''):
            query = f"""Voce é um assistente administrativo que deve identificar os artigos da LPI que fundamentam o indeferimento de um pedido de patente 
            tendo em vista a conclusão do parecer: ###{conclusao}###. No final 
            escreva no seguinte formato: 'o artigo 25 por falta de clareza, o artigo 6° por dupla proteção, o artigo 32 por acréscimo de matéria, a combinação
            dos artigos 8° e 11 por falta de novidade, a combinação dos artigos 8° e 13 por falta de atividade inventiva diante de D1 US5000090 e D2 US4568898, 
            o artigo 10 inciso III por não ser considerado invenção, o artigo 18 inciso III or não ser considerado matéria patenteável, 
            o artigo 24 por insuficiência descritiva, o artigo 15 por falta de aplicação industrial'. 
            Exiba como resposta simplesmente o texto final no formato solicitado
            """
        else:
            query = f"""Voce é um assistente administrativo que deve identificar os artigos da LPI que fundamentam o indeferimento de um pedido de patente 
            tendo em vista a conclusão do parecer: ###{conclusao}###. Se uma das razões for falta de atividade inventiva, cite os documentos usados para sua
            fundamentação, tendo em vista a discussão no parecer: ###{descricao}###. Identifique os documentos de patente tendo em vista {documentos}. 
            No final escreva no seguinte formato: 'o artigo 25 por falta de clareza, o artigo 6° por dupla proteção, o artigo 32 por acréscimo de matéria, a combinação
            dos artigos 8° e 11 por falta de novidade, a combinação dos artigos 8° e 13 por falta de atividade inventiva diante de D1 US5000090 e D2 US4568898, 
            o artigo 10 inciso III por não ser considerado invenção, o artigo 18 inciso III or não ser considerado matéria patenteável, 
            o artigo 24 por insuficiência descritiva, o artigo 15 por falta de aplicação industrial'.
            Exiba como resposta simplesmente o texto final.
            """

        #print(query)
        messages=[{"role":"user", "content": query}]
        response = llm.invoke(messages)
        print(f"Resposta: {response}")
        #resposta = response.json()
        #resumo = resposta['choices'][0]['message']['content']
        #resumo = resumo.replace("'","")
        #resumo = resumo.replace('"',"")
        #resumo = resumo.replace('---',"")
        #resumo = resumo.replace('',',')
        #resumo = resumo.replace('',',')
        #resumo = resumo.replace('',',')
        #resumo = resumo.replace('',',')
        #resumo = format_as_single_paragraph(resumo)
        #print(resumo)
        resumo = response.content
        sql_razoes = f"UPDATE anterioridades_desc set razoes='{resumo}' WHERE numero='{numero}';"
        print(sql_razoes)
            
    except Exception as e:
        print(f"Não achei parecer de indeferimento {numero} {e}")

In [69]:
# SELECT * FROM `carga` WHERE numero not in (select numero from anterioridades_desc) and numero in (select numero from arquivados where despacho='12.2');

import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = f"select * from anterioridades_desc where conclusao='';"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
#print(resultado)
lista = df.values.tolist()
lista = df.iloc[:, 1].tolist()
lista.insert(0, 'numero')
print(lista)

['numero', '112020025305', '102017014626', '112019011142', 'PI0703369', 'PI1105114', 'PI0800529', '112014031679', 'PI0207878', 'PI0208569', 'PI0210514', '102012009754', '102014018446', '102014031393', '112013024824', '112013026802', '112014031439', '112015003693', '112015006953', '112015006954', '112015032570', '112016002831', '122019014983', '122019015499', '122019015505', '122021015471', '202012011047', '202014031373', 'MU9101438', 'MU9102962', 'PI1106243', '102012004682', '102012009184', '112016001884', '122019015504', '122019015516', '202013018221', '102012010956', '112013002786', '112014000985', 'PI0922619', '102012010955', '102013005581', '102014025902', '102018011384', '112012030718', '202014000433', '202020012873', 'PI0416669', '102019009508', '102014022400', '102014027536', '102020006622', '102022000499', '112013000811', '112014032792', '112015030032', '112015030093', '112016000345', '112016003644', '112021013435', '112022018674', '122016008192', '122016008203', '122020001985', '122020022312', '202017011129', 'PI0906181', 'PI1012905']

In [ ]:
## UPDATE anterioridades_desc campo conclusao
# certifique-se de rodar a rotina acima conectar_siscap e de esta a VPN ligada
# SELECT * FROM `carga` WHERE numero not in (select numero from anterioridades_desc)
# UPDATE anterioridades_desc SET descricao = REPLACE(descricao, 'D1, D2, D3 e D4', 'de anterioridade') WHERE descricao LIKE '%D1, D2, D3 e D4%';
# primeiro processe os pedidos com indeferimento tecnico

import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
from langchain.prompts.prompt import PromptTemplate

def remove_page_and_pid(text: str) -> str:
    # remove ocorrência "Página <n>" possivelmente seguida por código PI...
    text = re.sub(r'(?i)\bPágina\s*\d+(?:\s*(?:de|/)\s*\d+)?', '', text)
    # remove ocorrência "Página <n> PI..." (se sobrar algum resíduo)
    text = re.sub(r'(?i)\bPágina\s*\d+(?:\s+PI\d+(?:-\d+)?)?', '', text)
    # remove códigos PI isolados como "PI1009860-7" ou "PI 1009860-7"
    text = re.sub(r'\bPI\s*\d+(?:-\d+)?\b', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\bBR\s*\d+(?:-\d+)?\b', '', text, flags=re.IGNORECASE)
    # remove sequências de espaços em branco extras
    text = re.sub(r'\s{2,}', ' ', text)
    # remove espaços antes de pontuação
    text = re.sub(r'\s+([,.;:!?])', r'\1', text)
    # remover traços/lists soltos do tipo " - " ou " — " que ficaram isolados
    text = re.sub(r'\s*[-–—]\s*(?=[^\w-])', ' ', text)
    # remover traços isolados no começo ou fim de linhas/frases
    text = re.sub(r'^[\s\-–—]+', '', text)
    text = re.sub(r'[\s\-–—]+$', '', text)
    # remover espaços duplos novamente e aparar
    text = re.sub(r'\s{2,}', ' ', text).strip()
    text = text.replace("..",".")
    text = text.replace(". .",".")
    text = text.replace("Art .8","Art 8")
    return text

def format_as_single_paragraph(text):
    # Remove quebras de linha e espaços extras
    formatted_text = ' '.join(line.strip() for line in text.splitlines() if line.strip())
    return formatted_text
    
for i in range(1, len(lista)):
    #numero = data["patents"][i]["numero"]
    numero = lista[i] # para ler a lista de numeros especificos

    #query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
    query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where (decisao='indeferimento' or decisao='ciencia de parecer') and numero='{numero}'" + ' order by rpi desc"'
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
    print(url)
    try:
        json_data = conectar_siscap(url,return_json=True)
        data1 = json.loads(json_data)
        codigo = data1["patents"][0]["codigo"]
        divisao = data1["patents"][0]["divisao"]    
        
        url = f"https://siscap.inpi.gov.br/adm/pareceres/{divisao}/{numero}{codigo}.txt"
        print(url)
        texto_relatorio = conectar_siscap(url,return_json=False)
        
        match = re.search(r"(CONCLUS[aã]O\s*[\r\n]+.*?)(?:Rio de Janeiro|$)", texto_relatorio, flags=re.S | re.I)

        if match:
            conclusao = re.sub(r"\s+", " ", match.group(1)).strip()
            print("Conclusão extraída:\n")
            conclusao = conclusao.replace("Conclusão", "")
            conclusao = conclusao.replace("CONCLUSÃO", "")
            conclusao = conclusao.replace("Assim sendo,", "")
            conclusao = conclusao.replace("","")
            conclusao = conclusao.replace("","")
            conclusao = conclusao.replace("","")
            conclusao = conclusao.replace("O depositante deve se manifestar quanto ao contido neste parecer em até 90 (noventa) dias, a partir da data de publicação na RPI, de acordo com o Art. 36 da LPI","")
            conclusao = conclusao.replace("Publique-se a ciência de parecer (7.1).","")
            conclusao = conclusao.split("De acordo com o Art. 212")[0].strip()
            conclusao = conclusao[0].upper() + conclusao[1:]
            conclusao = conclusao.replace("'","")
            conclusao = remove_page_and_pid(conclusao)
            conclusao = conclusao.replace("Código:5975ce1e23737deeb22c88e902a79153versão1.3 19/04/12","");
            str = f"update anterioridades_desc set conclusao='{conclusao}' where numero='{numero}';"
            print(str)
        else:
            print(f"Trecho não encontrado {numero}.")
    
    except Exception as e:
        print(f"Não achei parecer de indeferimento {numero} {e}")

In [40]:

texto = "O quadro reivindicatório do presente pedido dividido apresenta modificações voluntárias que ampliam a matéria originalmente reivindicada no pedido original PI0822012-3, o que contraria as disposições do artigo 32 da LPI, e a requerente já havia sido notificada quanto a este mesmo tipo de infração ao artigo 32 da LPI no primeiro exame do pedido original (notificado na RPI 2600 de 03/11/2020).  estando o presente pedido dividido na mesma fase processual em que se encontra o pedido original (artigo 28 da IN 031/2013), de acordo com o Art. 37, indefiro o Página 3 BR122021001866-9 presente pedido, uma vez que contém acréscimo de matéria no pedido ou no escopo das reivindicações (Art. 32 da LPI)."
texto = "De acordo com o Art. 37, indefiro o presente pedido, uma vez que: Página 9 de 10 BR102016029628-5 - não atende ao requisito de novidade (Art .8º combinado com Art. 11 da LPI) - não atende ao requisito de atividade inventiva (Art .8º combinado com Art. 13 da LPI) - não apresenta suficiência descritiva (Art. 24 da LPI) - as reivindicações estão indefinidas e/ou não estão fundamentadas no relatório descritivo (Art. 25 da LPI)"
texto = "O presente pedido dividido, voluntariamente apresentado em 09/07/2014, após a solicitação de exame do pedido original (10/10/2005), apresenta em seu quadro reivindicatório 08 reivindicações de uso (fórmula suíça), configurando alteração da matéria reivindicada no quadro original (do pedido PI0302584-5). Assim, de acordo com a orientação contida na Resolução INPI nº 093/2013, o quadro reivindicatório apresentado no presente pedido dividido (BR122014016915- 9) não é aceito por incidir no Art. 32 da Lei 9.279/96. Como o quadro reivindicatório do presente pedido dividido não foi aceito, o mesmo não foi analisado em relação aos Arts. 8.º, 11, 13, 15, 24 e 25 da LPI.  de acordo com o Art. 37, indefiro o presente pedido, uma vez que: Página 6/7 BR122014016915-9 - representa acréscimo de matéria do pedido ou do escopo das reivindicações (Art. 32 da LPI)."
texto = "O presente pedido dividido BR122020021128-8 pleiteia matéria que já foi analisada durante o primeiro exame do pedido original PI0923500-0 e para a qual já foi emitida uma opinião (RPI 2585 de 21/07/2020). Neste sentido, vale lembrar que, de acordo com o artigo 28 da Instrução Normativa 031/2013, o pedido dividido será considerado como estando na mesma fase processual em que se encontra o pedido original, cabendo ao INPI reduzir a termo a referência aos documentos e petições que se encontram no pedido original. Assim, estando o presente pedido dividido na mesma fase processual do PI0923500-0, e não tendo sido apresentado qualquer argumento que supere as objeções feitas durante o primeiro exame do pedido original, de acordo com o Art. 37, indefiro o presente pedido, uma vez que: - não atende ao requisito de novidade (Art .8º combinado com Art. 11 da LPI) Página 3 BR122020021128-8 - não atende ao requisito de atividade inventiva (Art .8º combinado com Art. 13 da LPI) - não apresenta suficiência descritiva (Art. 24 da LPI) - as reivindicações estão indefinidas e/ou não estão fundamentadas no relatório descritivo (Art. 25 da LPI)"
texto = "Face ao exposto neste parecer, o presente pedido não é passível de proteção tendo em vista os artigos 8º, 11, 13, 24 e 25 da LPI. Página 4 PI0519349-4 ."
texto = "Face ao exposto neste parecer, conclui-se que o novo quadro reivindicatório e argumentos ora apresentados não superam os questionamentos feitos no exame anterior.  de acordo com o Art. 37, indefiro o presente pedido, uma vez que: - não atende ao requisito de atividade inventiva (Art .8º combinado com Art. 13 da LPI) Página 4 PI0619395-1 - não apresenta suficiência descritiva (Art. 24 da LPI) - as reivindicações estão indefinidas e/ou não estão fundamentadas no relatório descritivo (Art. 25 da LPI)"
texto = "Face ao exposto neste parecer técnico, conclui-se que a matéria do presente pedido não é patenteável, pois não atende aos artigos 8°, 11, 13 e 25 da LPI.  de acordo com o Art. 37, indefiro o presente pedido, uma vez que: - não atende ao requisito de atividade inventiva (Art .8º combinado com Art. 13 da LPI) Página 5 de 6 BR112018070017-7"
texto = "De acordo com o Art. 37, indefiro o presente pedido, uma vez que: - não atende ao requisito de novidade (Art .8º combinado com Art. 11 da LPI) - não atende ao requisito de atividade inventiva (Art 8º combinado com Art. 13 da LPI) Página 4 de 5 BR112012005627-1 - as reivindicações estão indefinidas e/ou não estão fundamentadas no relatório descritivo (Art. 25 da LPI) - não é considerado invenção, uma vez que incide no Art. 10 da LPI"
texto = "De acordo com o Art. 37, indefiro o presente pedido, uma vez que: - não atende ao requisito de novidade (Art 8º combinado com Art. 11 da LPI) - não atende ao requisito de atividade inventiva (Art .8º combinado com Art. 13 da LPI) - não apresenta suficiência descritiva (Art. 24 da LPI) Página 8 de 9 BR122021017423-7 - as reivindicações estão indefinidas e/ou não estão fundamentadas no relatório descritivo (Art. 25 da LPI)."
print(remove_page_and_pid(texto))

De acordo com o Art. 37, indefiro o presente pedido, uma vez que: não atende ao requisito de novidade (Art 8º combinado com Art. 11 da LPI) não atende ao requisito de atividade inventiva (Art.8º combinado com Art. 13 da LPI) não apresenta suficiência descritiva (Art. 24 da LPI) as reivindicações estão indefinidas e/ou não estão fundamentadas no relatório descritivo (Art. 25 da LPI).

In [34]:
# SELECT * FROM `carga` WHERE numero not in (select numero from anterioridades_desc) and numero in (select numero from arquivados where despacho='12.2');

import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = "SELECT * FROM `anterioridades_desc` WHERE numero in (select numero from arquivados where despacho='12.2') and numero in (select numero from pedido where decisao='9.2') and conclusao='';"
#comando = "SELECT * FROM `carga` WHERE numero not in (select numero from anterioridades_desc) and numero in (select numero from arquivados where despacho='12.2') and numero in (select numero from pedido where decisao='9.2');"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
#print(resultado)
lista = df.values.tolist()
lista = df.iloc[:, 1].tolist()
lista.insert(0, 'numero')
print(lista)

['numero', 'PI0800529', '102014022400', '112015030093', '102019009508']

In [36]:
# Processe os pedidos com indeferimento administrativo decisao = 9.2 e faça os INSERT em anterioridades_desc

import os

def extrair_indefiro_sem_publique(texto: str) -> str:
    # Captura do "Portanto, INDEFIRO" até antes de "Publique-se"
    padrao = r"(Portanto,?\s*INDEFIRO.*?)(?=Publique-se)"
    match = re.search(padrao, texto, flags=re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return ""
    
#lista = ['','102022014500']
for i in range(1, len(lista)):
    #numero = data["patents"][i]["numero"]
    numero = lista[i] # para ler a lista de numeros especificos

    #query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where decisao='indeferimento' and numero='{numero}'" + '"'
    query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where (decisao='9.2') and numero='{numero}'" + ' order by rpi desc"'
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
    print(url)
    try:
        json_data = conectar_siscap(url,return_json=True)
        data1 = json.loads(json_data)
        codigo = data1["patents"][0]["codigo"]
        divisao = data1["patents"][0]["divisao"]    
        
        url = f"https://siscap.inpi.gov.br/adm/pareceres/{divisao}/{numero}{codigo}.txt"
        print(url)
        texto_relatorio = conectar_siscap(url,return_json=False)
        
        match = re.search(r"(O depositante deixou.*?)(?=Rio de Janeiro)", texto_relatorio, flags=re.S)

        if match:
            conclusao = re.sub(r"\s+", " ", match.group(1)).strip()
            print("Conclusão:\n")
            conclusao = conclusao[0].upper() + conclusao[1:]
            conclusao = conclusao.replace("'","")
            conclusao = extrair_indefiro_sem_publique(conclusao)
            sql_resumo = f"INSERT IGNORE INTO anterioridades_desc (id,numero,descricao,conclusao) VALUES (null, '{numero}','','{conclusao}');"
            sql_resumo = f"UPDATE anterioridades_desc SET conclusao='{conclusao}' WHERE numero='{numero}';"
            print(sql_resumo)
        else:
            print(f"Trecho não encontrado {numero}.")
            
    
    except Exception as e:
        print(f"Não achei parecer de indeferimento {numero} {e}")

https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM pedido where (decisao='9.2') and numero='PI0800529' order by rpi desc"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

https://siscap.inpi.gov.br/adm/pareceres/dimol/PI0800529502867.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Conclusão:

UPDATE anterioridades_desc SET conclusao='Portanto, INDEFIRO o presente pedido de Patente de Invenção PI0800529-0 , de acordo com Art. 8° combinado com Art. 11 e Art. 8° combinado com Art. 13 da LPI (Lei 9279 / 96).' WHERE numero='PI0800529';
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM pedido where (decisao='9.2') and numero='102014022400' order by rpi desc"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

https://siscap.inpi.gov.br/adm/pareceres/dibio/1020140224001271043.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Conclusão:

UPDATE anterioridades_desc SET conclusao='Portanto, INDEFIRO o presente pedido de Patente de Invenção BR102014022400-9 , de acordo com Art. 8° combinado com Art. 13 da LPI (Lei 9279 / 96).' WHERE numero='102014022400';
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM pedido where (decisao='9.2') and numero='112015030093' order by rpi desc"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

https://siscap.inpi.gov.br/adm/pareceres/dibio/1120150300931271049.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Conclusão:

UPDATE anterioridades_desc SET conclusao='Portanto, INDEFIRO o presente pedido de Patente de Invenção BR112015030093-6 , de acordo com Art. 8° combinado com Art. 13 da LPI (Lei 9279 / 96).' WHERE numero='112015030093';
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM pedido where (decisao='9.2') and numero='102019009508' order by rpi desc"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

https://siscap.inpi.gov.br/adm/pareceres/dimec/1020190095081855363.txt
Conclusão:

UPDATE anterioridades_desc SET conclusao='Portanto, INDEFIRO o presente pedido de Patente de Invenção BR102019009508-3 , de acordo com Art. 8° combinado com Art. 13 da LPI (Lei 9279 / 96).' WHERE numero='102019009508';

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [38]:
import requests
from dotenv import load_dotenv
import os

# Defina a chave de API e o endpoint
url = "https://api.openai.com/v1/chat/completions"
load_dotenv(dotenv_path='.env', override=True)
openai_api_key = os.getenv("OPENAI_API_KEY")

# Defina o prompt e os parâmetros da solicitação
query = "qual a capital do Brasil?"
headers = {
    "Authorization": f"Bearer {openai_api_key}",
    "Content-Type": "application/json"
}

data = {
    "model": "gpt-5-mini",  # Use o modelo desejado, como 'gpt-4'
    "messages": [
        {"role": "user", "content": query}
    ]
}

# Faça a solicitação POST para a API
response = requests.post(url, headers=headers, json=data, verify=False)

# Verifique se a solicitação foi bem-sucedida
if response.status_code == 200:
    # Exiba o conteúdo da resposta
    resposta = response.json()
    print(resposta['choices'][0]['message']['content'])
else:
    # Exiba o erro
    print(f"Erro {response.status_code}: {response.text}")

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A capital do Brasil é Brasília. Foi inaugurada em 21 de abril de 1960 e está localizada no Distrito Federal.

In [70]:
import re 
pattern = r"(D\d+)\s+([A-Z]+\s?\d+)\s+([A-B]\d)?\s+(\d{2}\/\d{2}\/\d{4})"
pattern = r"(D\d+)\s+(US\s?(?:\d{1,3}(?:,\d{3})+|\d+))(?:\s+([A-Z]\d))?\s+(\d{2}\/\d{2}\/\d{4})"
pattern = r"(D\d+)\s+(US\s?\d{1,3}(?:,)(\d{1,10})+)\s+([A-Z]\d)\s+(\d{2}/\d{2}/\d{4})"
pattern = r"(D\d+)\s+(US\s?\d{1,12})\s+([A-Z]\d)\s+(\d{2}/\d{2}/\d{4})"
pattern = r"(D\d+)\s+(US\s?\d[\d.,;]{0,20}\d)\s+([A-Z]\d)\s+(\d{2}/\d{2}/\d{4})"
texto_relatorio = "D1 US 2;010,153.846 A1 17/06/2010"
matches = re.findall(pattern, texto_relatorio)
for match in matches:
    codigo, documento, tipo, data_publicacao = match
    documento_formatado = " ".join(documento.split())
    documento_formatado = documento_formatado.replace(" ", "")
    print(f"{codigo}: {documento_formatado}, Data de Publicação = {data_publicacao}")
documento_formatado=documento_formatado.replace(',','')
documento_formatado=documento_formatado.replace('.','')
documento_formatado=documento_formatado.replace(';','')
print(documento_formatado.replace(',',''))

D1: US2;010,153.846, Data de Publicação = 17/06/2010
US2010153846

In [30]:
# teste
import re
pattern = r"Quadro 4.*?Documento.*?(\w+\s\d{7,8}\s\w{2})"

# Busca no texto usando a regex
match = re.search(pattern, texto_relatorio, re.DOTALL)

if match:
    documento_citado = match.group(1)
    print(f"Documento citado no Quadro 4: {documento_citado}")
else:
    print("Documento citado no Quadro 4 não encontrado.")

Documento citado no Quadro 4 não encontrado.

In [31]:
# teste
pattern = r"D1\s+([\w\s]+)\s+D2\s+([\w\s]+)"

# Busca no texto usando a regex
match = re.search(pattern, texto_relatorio)

if match:
    d1_document = match.group(1).strip()
    d2_document = match.group(2).strip()
    print(f"Documento D1: {d1_document}")
    print(f"Documento D2: {d2_document}")
else:
    print("Documentos D1 e D2 não encontrados.")

Documentos D1 e D2 não encontrados.

In [33]:
# pip install unstructured[all-docs]==0.10.19
import os
from unstructured.partition.text import partition_text

txt_file_path = 'document.txt'
if os.path.exists(txt_file_path):
    print(f"O arquivo '{txt_file_path}' existe.")
else:
    print(f"O arquivo '{txt_file_path}' não existe.")
    
raw_txt_elements = partition_text(filename=txt_file_path)

O arquivo 'document.txt' existe.

In [34]:
tables = []
texts = []
titles = []
narratives = []
list_items = []
for element in raw_txt_elements:
    #print(type(element))
    if "unstructured.documents.elements.Table" in str(type(element)):
        tables.append(str(element))
    if "unstructured.documents.elements.Text" in str(type(element)):
        texts.append(str(element))
    if "unstructured.documents.elements.Title" in str(type(element)):
        titles.append(str(element))
    if "unstructured.documents.elements.NarrativeText" in str(type(element)):
        narratives.append(str(element))
    if "unstructured.documents.elements.ListItem" in str(type(element)):
        list_items.append(str(element))

In [35]:
# https://regex101.com/

for i, texto in enumerate(texts):
    texts[i] = texts[i].replace('ó', 'o')
    texts[i] = texts[i].replace('ç', 'c')
    texts[i] = texts[i].replace('ã', 'a')
    if "Codigo" in texts[i] and "Documento" in texts[i] and "Data de publicacao" in texts[i]:
        print(texts[i])
        # print(i)
        pattern = r"(D\d+)\s+([A-Z]+\s?\d+)\s+([A-B]\d)?\s+(\d{2}\/\d{2}\/\d{4})"
        matches = re.findall(pattern, texto)
        for match in matches:
            codigo, documento, tipo, data_publicacao = match
            documento_formatado = " ".join(documento.split())
            documento_formatado = documento_formatado.replace(" ", "")
            print(f"{codigo}: {documento_formatado}, Data de Publicação = {data_publicacao}")

Codigo                                  Documento                             Data de publicacao D1                                 US 2010153846                                  17/06/2010 D2                                 US 2009327349                                  31/12/2009
D1: US2010153846, Data de Publicação = 17/06/2010
D2: US2009327349, Data de Publicação = 31/12/2009

In [43]:
texts[0]

'N.° do Pedido:                      BR112013005558-8            N.° de Deposito PCT:US2011/051262 Data de Deposito:                   12/09/2011 Prioridade Unionista:               US 12879982 (10/09/2010) Depositante:                        Sony Computer Entertainment America Llc (US) Inventor:                           Steve Schneider Título:                             \x93Método de gerenciar listar de reproducao, dispositivo de mídia portátil, e, meio de armazenamento nao transitorio \x94'

In [42]:
titles

['SERVIÇO PÚBLICO FEDERAL MINISTÉRIO DA ECONOMIA INSTITUTO NACIONAL DA PROPRIEDADE INDUSTRIAL',
 'RELATÓRIO DE EXAME TÉCNICO',
 'PARECER',
 'Conclusão',
 'Página 2',
 'Publique',
 'se o indeferimento (9.2).',
 'Rio de Janeiro, 5 de fevereiro de 2021.',
 'Bruna Marques Mazoco',
 'Pesquisador/ Mat. Nº 2316562',
 'DIRPA / CGPAT III/DICEL',
 'Deleg. Comp.',
 'Port. INPI/DIRPA Nº 001/18',
 'Página 3']

In [44]:
narratives

['Em 04/01/2020, por meio da petição 870210000611, a Requerente apresentou modificações no pedido em resposta ao parecer emitido, notificado na RPI 2596 de 06/10/2020 (despacho 7.1). Estas modificações estão consideradas no Quadro 1.',
 'Quadro 2 \x96 Considerações referentes aos Artigos 10, 18, 22 e 32 da Lei n.o 9.279 de 14 de maio de 1996 \x96 LPI Artigos da LPI                                                                                Sim       Não A matéria enquadra-se no art. 10 da LPI (não se considera invenção)                            x A matéria enquadra-se no art. 18 da LPI (não é patenteável)                                              x O pedido apresenta Unidade de Invenção (art. 22 da LPI)                                        x O pedido está de acordo com disposto no art. 32 da LPI                                         x Comentários/Justificativas',
 'Mantém-se o posicionamento exarado em parecer de 1º exame técnico publicado na RPI 2596 de 06/10/2020, no qual considera-se que o presente pedido infringe o disposto no Art. 10(VI), por pleitear detalhes de exibição da interface gráfica do aplicativo de reprodução de uma playlist, não sendo tais características passíveis de serem patenteadas.',
 'Quadro 3 \x96 Considerações referentes aos Artigos 24 e 25 da LPI',
 'Artigos da LPI                                                           Sim               Não O relatório descritivo está de acordo com disposto no art. 24 da LPI      x O quadro reivindicatório está de acordo com disposto no art. 25 da LPI    x Comentários/Justificativas',
 'Em petição 870210000611 de resposta ao parecer de 1º exame técnico exarado na RPI 2596 de 06/10/2020, a Requerente atendeu satisfatoriamente às exigências formuladas acerca do não enquadramento do pedido no Art. 25 da LPI, assim como elucidou eventuais dúvidas que o texto do quadro reivindicatório tenha suscitado.',
 'Quadro 4 \x96 Documentos citados no parecer',
 'Quadro 5 \x96 Análise dos Requisitos de Patenteabilidade (Arts. 8.º, 11, 13 e 15 da LPI) Requisito de Patenteabilidade              Cumprimento           Reivindicações Sim                    1-11 Aplicação Industrial Não                       - Sim                    1-11 Novidade Não                       -',
 'Os argumentos apresentados pela Requerente foram levados em consideração e julgados não persuasivos. Reitera-se a posição de que, apesar de dotado de novidade, o presente pedido não possui atividade inventiva quando confrontado com os ensinamentos de D1 e D2.',
 'Assim sendo, de acordo com o Art. 37, indefiro o presente pedido, uma vez que não atende ao requisito de atividade inventiva (Art. 8º combinado com Art. 13 da LPI) e não é considerado invenção, incidindo no Art. 10 da LPI.',
 'De acordo com o Art. 212 da LPI, o depositante tem prazo de 60 (sessenta) dias, a partir da data de publicação na RPI, para interposição de recurso.']

In [45]:
list_items

['', '', '']

In [ ]:
doc = 'US20030065257'
url = f"https://patents.google.com/patent/{doc}A1/en?oq={doc}"
data = conectar_siscap(url,return_json=False)
print(data)

In [47]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

html = urlopen(url)
#print(html.read())

bs = BeautifulSoup(html.read(),'html.parser')
print(bs.title)

<title>US20030065257A1 - Diet and activity monitoring device
        - Google Patents</title>

In [48]:
nameList = bs.findAll("meta", {"name":"DC.description"})
for name in nameList:
    content_value = name.get('content')
    print(content_value)

     A diet and activity-monitoring device includes a housing configured to be mounted on the subject and a display integral with the housing for displaying information to the subject. The device also includes a body activity monitor operatively disposed within the housing for monitoring the body activity of the subject, a consumption notation control operable by the subject to indicate food consumption, and a timer operable to output a time indicative signal. The device further includes a processor operable to receive and process the body activity signal, time indicative signal and the food consumption signal, for use in determining a food consumption indicator or a body activity indicator, that is stored in a memory portion of the processor for recall by the subject on the display screen.

In [49]:
nameList = bs.findAll("div", {"class":"abstract"})
for name in nameList:
    print(name.getText())

A diet and activity-monitoring device includes a housing configured to be mounted on the subject and a display integral with the housing for displaying information to the subject. The device also includes a body activity monitor operatively disposed within the housing for monitoring the body activity of the subject, a consumption notation control operable by the subject to indicate food consumption, and a timer operable to output a time indicative signal. The device further includes a processor operable to receive and process the body activity signal, time indicative signal and the food consumption signal, for use in determining a food consumption indicator or a body activity indicator, that is stored in a memory portion of the processor for recall by the subject on the display screen.

In [ ]:
# <section itemprop="description" itemscope>

nameList = bs.findAll("section", {"itemprop":"description"})
for name in nameList:
    print(name.getText())
    texto = name.getText()

In [30]:
from openai import OpenAI
client = OpenAI(api_key=openai_api_key)
query = "o que é causa madura ?"
response = client.chat.completions.create(model='gpt-4o-mini',messages=[{"role":"user","content":query}])
print(response)

ChatCompletion(id='chatcmpl-D4RDpkhg9H7EV8BjWGlNnzC5BoYTC', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='O termo "causa madura" é frequentemente utilizado no contexto jurídico, especialmente no direito processual civil. Uma causa é considerada madura quando todos os elementos necessários para a sua resolução estão presentes e o juiz está em condições de proferir uma decisão sem a necessidade de produção de mais provas ou de outros atos processuais.\n\nEm geral, isso significa que não há mais fatos a serem investigados e que a questão é clara o suficiente para que uma decisão possa ser tomada. A causa madura permite, portanto, que o juiz possa proferir uma sentença com base nos elementos já existentes nos autos do processo.\n\nÉ importante notar que a definição e a aplicação desse conceito podem variar dependendo da legislação e do sistema jurídico de cada país.', refusal=None, role='assistant', function_call=None, tool_calls=None, annotations=[]))], created=1769950325, model='gpt-4o-mini-2024-07-18', object='chat.completion', service_tier='default', system_fingerprint='fp_1590f93f9d', usage=CompletionUsage(completion_tokens=145, prompt_tokens=13, total_tokens=158, completion_tokens_details=CompletionTokensDetails(reasoning_tokens=0, audio_tokens=0, accepted_prediction_tokens=0, rejected_prediction_tokens=0), prompt_tokens_details={'cached_tokens': 0, 'audio_tokens': 0}))

In [71]:
import requests

# Defina a chave de API e o endpoint
api_key = openai_api_key  # Substitua pela sua chave de API
url = "https://api.openai.com/v1/chat/completions"

# Defina o prompt e os parâmetros da solicitação
query = "o que é causa madura?"
headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json"
}

data = {
    "model": "gpt-5-mini",  # Use o modelo desejado, como 'gpt-4'
    "messages": [
        {"role": "user", "content": query}
    ]
}

# Faça a solicitação POST para a API
response = requests.post(url, headers=headers, json=data, verify=False)

# Verifique se a solicitação foi bem-sucedida
if response.status_code == 200:
    # Exiba o conteúdo da resposta
    resposta = response.json()
    print(resposta['choices'][0]['message']['content'])
else:
    # Exiba o erro
    print(f"Erro {response.status_code}: {response.text}")

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Você pode estar se referindo a um termo jurídico. Quer que eu explique nesse sentido ou em outro contexto?

Se for no direito: “causa madura” significa, de forma simples, um processo ou matéria que está pronta para ser julgada — isto é, cuja fase de instrução e diligências necessárias já foi concluída, não há mais atos processuais pendentes que impeçam a decisão e não existem questões preliminares que obstaculizem o julgamento do mérito. Em outras palavras, os elementos de prova e as condições processuais estão consolidados, de modo que o juiz pode proferir sentença ou decidir o mérito.

Exemplos e sinais de que a causa está madura:
- todas as provas foram produzidas (oitiva de testemunhas, perícias, documentos);
- as partes apresentaram as alegações finais ou prazo expirou;
- não há incidentes processuais pendentes (ex.: nulidades a resolver, incapacidade a ser declarada);
- prazos recursais ou de cumprimento de diligências foram esgotados, quando relevante.

Se quiser, eu explico com um exemplo prático (civil, trabalhista ou administrativo) ou trago jurisprudência/citação do Código de Processo Civil relacionada ao tema. Quer que eu desenvolva?

In [54]:
from langchain.chat_models import ChatOpenAI
from langchain.schema.output_parser import StrOutputParser

from langchain_core.prompts import ChatPromptTemplate
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(api_key=open_api_key)
output_parser = StrOutputParser()

user_query = "o que é causa madura ?"

from langchain.chains import LLMChain
template="""
    Questão: {question}
"""
prompt = ChatPromptTemplate.from_template(template)
chain1 = LLMChain(
    llm=llm,
    prompt=prompt,
    output_parser=output_parser
)
response = chain1.invoke({"question": user_query})
print(response['text'])

ImportError: cannot import name 'field_validator' from 'pydantic' (D:\Users\abrantes\AppData\Local\anaconda3\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)

In [55]:
from langchain.chat_models import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

prompt = ChatPromptTemplate.from_template("Responda: {pergunta}")
model = ChatOpenAI(api_key=open_api_key)
parser = StrOutputParser()

chain = prompt | model | parser

resp = chain.invoke({"pergunta": "O que é causa madura?"})
print(resp)

ImportError: cannot import name 'field_validator' from 'pydantic' (D:\Users\abrantes\AppData\Local\anaconda3\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)

In [51]:
import os
from dotenv import load_dotenv
#from langchain_openai import ChatOpenAI
from langchain.chat_models import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferMemory

load_dotenv(dotenv_path='.env')
open_api_key = os.getenv("OPENAI_API_KEY")
#print(open_api_key)

llm = ChatOpenAI(api_key=open_api_key)
out_parser = StrOutputParser()
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "Você é um assistente virtual."),
        ("user", "{user_input}"),
    ])

prompt2 = ChatPromptTemplate.from_messages(
    [
        ("system", "Você é um assistente virtual."),
        ("user", "{user_input}"),
        ("system", "{history}"),
    ]
)

chain = prompt | llm | out_parser

memory = ConversationBufferMemory()

conversation = ConversationChain(
    #prompt = prompt2,
    llm = llm,
    verbose = False,
    memory=ConversationBufferMemory()
)

query = "Qual a capital do Brasil?"
#query = texto
#resposta = chain.invoke({"user_input":f"{query}"})
#print(resposta)

#resposta = conversation.invoke({"user_input":f"{query}"})
resposta = conversation.invoke(query)
print(resposta['response'])

D:\Users\abrantes\AppData\Local\anaconda3\lib\importlib\__init__.py:126: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. 	from pydantic.v1 import BaseModel

  return _bootstrap._gcd_import(name[level:], package, level)
D:\Users\abrantes\AppData\Local\anaconda3\lib\site-packages\pydantic\_internal\_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'validate_by_name'
  warnings.warn(message, UserWarning)
D:\Users\abrantes\AppData\Local\Temp\ipykernel_22056\1630912043.py:15: LangChainDeprecationWarning: The class `ChatOpenAI` was deprecated in LangChain 0.0.10 and will be removed in 0.3.0. An updated version of the class exists in the :class:`~langchain-openai package and should be used instead. To use it run `pip install -U :class:`~langchain-openai` and import as `from :class:`~langchain_openai import ChatOpenAI``.
  llm = ChatOpenAI(api_key=open_api_key)
D:\Users\abrantes\AppData\Local\Temp\ipykernel_22056\1630912043.py:33: LangChainDeprecationWarning: Please see the migration guide at: https://python.langchain.com/docs/versions/migrating_memory/
  memory = ConversationBufferMemory()
D:\Users\abrantes\AppData\Local\Temp\ipykernel_22056\1630912043.py:35: LangChainDeprecationWarning: The class `ConversationChain` was deprecated in LangChain 0.2.7 and will be removed in 1.0. Use :class:`~langchain_core.runnables.history.RunnableWithMessageHistory` instead.
  conversation = ConversationChain(

TypeError: 'FieldInfo' object is not a mapping

In [52]:
query = "qual sua população?"
resposta = conversation.invoke(query)
print(resposta['response'])

TypeError: 'FieldInfo' object is not a mapping

In [53]:
query = "quais os principais pontos turísticos?"
resposta = conversation.invoke(query)
print(resposta['response'])

TypeError: 'FieldInfo' object is not a mapping

In [38]:
texto

'<revista numero="2707" dataPublicacao="22/11/2022" diretoria="Patente">\n  '

In [ ]:
query

In [32]:
from openai import OpenAI

client = OpenAI(api_key=openai_api_key)
query = f"resuma o documento D1: {texto}"
reponse = client.chat.completions.create(model='gpt-4o-mini',messages=[{"role":"user","content":query}])
print(response)

ChatCompletion(id='chatcmpl-D4RDpkhg9H7EV8BjWGlNnzC5BoYTC', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='O termo "causa madura" é frequentemente utilizado no contexto jurídico, especialmente no direito processual civil. Uma causa é considerada madura quando todos os elementos necessários para a sua resolução estão presentes e o juiz está em condições de proferir uma decisão sem a necessidade de produção de mais provas ou de outros atos processuais.\n\nEm geral, isso significa que não há mais fatos a serem investigados e que a questão é clara o suficiente para que uma decisão possa ser tomada. A causa madura permite, portanto, que o juiz possa proferir uma sentença com base nos elementos já existentes nos autos do processo.\n\nÉ importante notar que a definição e a aplicação desse conceito podem variar dependendo da legislação e do sistema jurídico de cada país.', refusal=None, role='assistant', function_call=None, tool_calls=None, annotations=[]))], created=1769950325, model='gpt-4o-mini-2024-07-18', object='chat.completion', service_tier='default', system_fingerprint='fp_1590f93f9d', usage=CompletionUsage(completion_tokens=145, prompt_tokens=13, total_tokens=158, completion_tokens_details=CompletionTokensDetails(reasoning_tokens=0, audio_tokens=0, accepted_prediction_tokens=0, rejected_prediction_tokens=0), prompt_tokens_details={'cached_tokens': 0, 'audio_tokens': 0}))

In [74]:
query = f"resuma o documento D1: {texto}"
resposta = chain.invoke({"user_input":f"{query}"})
print(resposta)

KeyError: "Input to ChatPromptTemplate is missing variables {'pergunta'}.  Expected: ['pergunta'] Received: ['user_input']\nNote: if you intended {pergunta} to be part of the string and not a variable, please escape it with double curly braces like: '{{pergunta}}'."

In [71]:
#memory = ConversationBufferMemory()
query = f"resuma o documento D1: {texto}"
resposta = conversation.invoke(query)
print(resposta)

BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 16385 tokens. However, your messages resulted in 28088 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

In [33]:
query = f"resuma os problemas técnicos apontados no texto: {texto}"
resposta = chain.invoke({"user_input":f"{query}"})
print(resposta)

NameError: name 'chain' is not defined

In [68]:
query = f"resuma o pedido em exame: {texto_pedido} e o documento D1: {texto} e aponte as diferenças"
resposta = chain.invoke({"user_input":f"{query}"})
print(resposta)

O pedido em exame refere-se a um sistema de internet sem fio para monitorizar exercício ou condição física, enquanto o documento D1 se refere a um dispositivo que combina monitoramento de dieta e atividade. As formas de realização da invenção do pedido proporcionam um método e um aparelho para um sistema de monitoração de exercício sem fio, enquanto o documento D1 se concentra em melhorar a determinação do balanço calórico por meio de monitoramento de dieta e atividade.

Além disso, o pedido em exame descreve o uso de um dispositivo de internet sem fio conectado a uma câmera digital e/ou dispositivo de monitoração de exercício, enquanto o documento D1 aborda a gestão de dieta, saúde e fitness, sem mencionar o uso de câmeras ou dispositivos de monitoramento de exercício conectados à internet sem fio.

Em suma, o pedido em exame se concentra no monitoramento interativo de aspectos de exercício, nutrição e condição física usando um sistema de internet sem fio, enquanto o documento D1 aborda um dispositivo que combina monitoramento de dieta e atividade, sem mencionar o uso de dispositivos de internet sem fio ou câmeras digitais.

In [70]:
# hostgator / cpanel / terminal / python --version
# roda offline com vpn ligada e obtem as docs citados no 9.2 e salva numa tabela
# no php do sinergias acessa a pagina do streamlit com numero pedido e anterioridade
# resgata a resposta com xml
# insere xml no documento odt modelo
url = "https://app-helloabrantes.streamlit.app/teste.txt"
dados = conectar_siscap(url,return_json=False)
print(dados)

<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no,user-scalable=no"/><meta name="theme-color" content="#FFFFFF"/><link id="favicon" rel="icon" href="/-/build/favicon.svg"/><link id="alternate-favicon" rel="alternate icon" href="/-/build/favicon.ico"/><link rel="mask-icon" href="/-/build/favicon_safari_mask.png" color="#FF2B2B"/><link rel="apple-touch-icon" href="/-/build/favicon_256.png"/><link rel="manifest" href="/-/build/manifest.json"/><script>!function(e,t,a,n,g){e[n]=e[n]||[],e[n].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});var m=t.getElementsByTagName(a)[0],r=t.createElement(a);r.async=!0,r.src="https://www.googletagmanager.com/gtm.js?id=GTM-52GRQSL",m.parentNode.insertBefore(r,m)}(window,document,"script","dataLayer")</script><script>!function(){var e=window.analytics=window.analytics||[];if(!e.initialize)if(e.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{e.invoked=!0,e.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"],e.factory=function(t){return function(){var n=Array.prototype.slice.call(arguments);return n.unshift(t),e.push(n),e}};for(var t=0;t<e.methods.length;t++){var n=e.methods[t];e[n]=e.factory(n)}e.load=function(t,n){var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src="https://cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(a,r),e._loadOptions=n},e.SNIPPET_VERSION="4.13.1",e.load("GI7vYWHNmWwHbyFjBrvL0jOBA1TpZOXC")}}()</script><script defer="defer" src="/-/build/static/js/main.34651d50.js"></script><link href="/-/build/static/css/main.1725856a.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>

In [34]:
# continue aqui. atualização da tabela anterioridades

In [36]:
from datetime import datetime
def converter_data(data):
    try:
        # Tenta converter usando o formato 'dd/mm/yy'
        return datetime.strptime(data, '%d/%m/%y').strftime('%Y-%m-%d')
    except ValueError:
        # Caso falhe, tenta converter usando o formato 'dd/mm/yyyy'
        return datetime.strptime(data, '%d/%m/%Y').strftime('%Y-%m-%d')
        
print(converter_data('10/11/06'))
print(converter_data('08/12/2004'))

2006-11-10
2004-12-08

In [154]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

comando = f"select * from carga where numero not in (select numero from anterioridades) and numero in (select numero from pedido where decisao='9.2')"
comando = f"select * from carga where numero not in (select numero from anterioridades) and numero in (select numero from arquivados where despacho='12.2')"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
#print(resultado)
lista = df.values.tolist()
lista = df.iloc[:, 0].tolist()
print(lista)

['122014021216', '122014030028', '122014030029', '122016008192', '122016008203', '122017012058', '122017013108', '122019008317', '122019014139', '122019017348', '122019017408', '122019018710', '122019019161', '122019019741', '122019020154', '122019022840', '122019025423', '122019025630', '122019026828', '122019026829', '122020000568', '122020001985', '112022018674', '122023002765', '122023019756', '112020011171', '102019023319', '102020006622', '102023026277', '112021009213', '102022000499', '202020012873', '112021013435', 'MU9100240', 'PI0811199', 'PI0900922', 'PI0906181', 'PI0912882', 'PI0919841', 'PI0920465', 'PI0921237', 'PI1000672', 'PI1001299', 'PI1003746', 'PI1003760', 'PI1003946', 'PI1004183', 'PI1004208', 'PI1004831', 'PI1011888', 'PI1012905', 'PI1013364', 'PI1102208', 'PI1103116', 'PI1105561', 'PI1105730', 'PI1105999', 'PI1106311', '132015013589', '202012011722', '202012022499', '202012022838', '202012022845', '202012023481', '202013002255', '202013009916', '202013013463', '202013017528', '202013018205', '202013019250', '202013030643', '202013033354', '202014007119', '202014008647', '202017011129', '112016013498', '112016015685', '112016018219', '112016021786', '112016022147', '112016023062', '112016028205', '112017002417', '112017015838', '112018009927', '112018011919', '112013015675', '112013017629', '112013019574', '112013019699', '112013019993', '112013022994', '112013023949', '112013024608', '112013024824', '112013026179', '112013027540', '112013033021', '112013033182', '112014000495', '112014000630', '112014001086', '112014002748', '112014007027', '112014008278', '112014008804', '112014009269', '112014009565', '112014010347', '112014011387', '112014012138', '112014019937', '112014020793', '112014024641', '112014027978', '112014032792', '112015004775', '112015006343', '112015006953', '112015013863', '112015015060', '112015019603', '112015023140', '112015030032', '112015032570', '112015032811', '112016000345', '112016002195', '112016003414', '112016003644', '112016008784', '102016024247', '102012004079', '102012010956', '102012012377', '102012013367', '102012015992', '102012023815', '102012028509', '102012030828', '102012032927', '102013017278', '102013023577', '102014002008', '102014012053', '102014013268', '102014013993', '102014013996', '102014021906', '102014024348', '102014024578', '102014027536', '102015006648', '102015019612', '122020004305', '122020004657', '122020007757', '122020007845', '122020008510', '122020009181', '122020010712', '122020014060', '122020014740', '122020015607', '122020015741', '122020016644', '122020017092', '122020017367', '122020017751', '122020017889', '122020019318', '122020019976', '122020021367', '122020022012', '122020022312', '122020022771', '122020023574', '122020024337', '122021003228', '122021004607', '122021004615', '122021004616', '122021004669', '122021006465', '122021007885', '122021014646', '122021015578', '122021019202', '122021019888', '122021025799', '122022001757', '122022017025', '122022017178', '122022017195', '122022019084', '122022020636', '112012008983', '112012011128', '112012017243', '112012017257', '112012023010', '112012026730', '112012026999', '112012029457', '112012030594', '112013000811', '112013001671', '112013001754', '112013003250', '112013003657', '112013004702', '112013007315', '112013009001', '112013010362', '112013013225', '112013014036']

In [155]:
# ******************************************
# gera lista de docs para cada um dos 285 pedidos na carga da tabela anterioridades
# select * from CEPIT_SISCAP.SISCAP_CARGA where numero in (select numero from CEPIT_SISCAP.SISCAP_arquivados WHERE despacho='9.2' and anulado=0)
# primeiro apague os registros com direp delete FROM `carga` WHERE divisao='direp'; para poder carregar os novos registros
# agora faça o import com o CSV gerado
# delete FROM `carga` WHERE divisao<>'direp'

# https://cientistaspatentes.com.br/apiphp/patents/query/?q={"mysql_query":" * FROM carga where divisao='direp'"}
# https://cientistaspatentes.com.br/apiphp/patents/query/?q={"mysql_query":" * FROM carga where divisao='direp' and numero in (select numero from arquivados WHERE despacho='9.2' and anulado=0)"}

# rodar rotina abaixo com VPN ligada certifique-se que siscap.inpi.gov.br funcionando
# quando terminar acerte a tabela anterioridades com
# https://cientistaspatentes.com.br/central/control.php?action=172
# SELECT numero from carga WHERE numero not in (select numero from anterioridades)

import re
from datetime import datetime
import json
import requests  # Supondo que conectar_siscap use requests

def converter_data(data):
    try:
        # Tenta converter usando o formato 'dd/mm/yy'
        return datetime.strptime(data, '%d/%m/%y').strftime('%Y-%m-%d')
    except ValueError:
        # Caso falhe, tenta converter usando o formato 'dd/mm/yyyy'
        return datetime.strptime(data, '%d/%m/%Y').strftime('%Y-%m-%d')

def converter_data2(data):
    if not data:
        return None

    # Remove qualquer coisa que não seja número ou /
    data = re.sub(r'[^0-9/]', '', data)

    formatos = ['%d/%m/%y', '%d/%m/%Y']

    for fmt in formatos:
        try:
            return datetime.strptime(data, fmt).strftime('%Y-%m-%d')
        except ValueError:
            pass  # tenta o próximo formato

    # Se nada deu certo, NÃO aborta
    return None

def montar_url_parecer(numero):
    query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM pedido where (decisao='indeferimento' or decisao='ciencia de parecer') and numero='{numero}' order by rpi desc" + '"'
    url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
    json_data = conectar_siscap_new(url,return_json=True)
    if json_data is not None:
        data = json.loads(json_data)
        if not json_data or "patents" not in json_data or len(data["patents"]) == 0:
            return None
        else:
            data = json.loads(json_data)
            codigo = data["patents"][0]["codigo"]
            divisao = data["patents"][0]["divisao"]
            # print(f"Código: {codigo}")
            # print(f"Divisão: {divisao}")
            url = f"https://siscap.inpi.gov.br/adm/pareceres/{divisao}/{numero}{codigo}.txt"
            return url
    else:
        return None

def conectar_siscap_new(url, return_json=False):
    headers = {
        "Accept": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    try:
        response = requests.get(url,headers=headers,verify=False)
        response.raise_for_status()  # Verifica se a resposta tem status 200 (OK)
        
        if return_json:
            try:
                # Tenta decodificar a resposta como JSON
                data = response.json()
                json_data = json.dumps(data, indent=4)
                return(json_data)
            except json.JSONDecodeError:
                # Caso falhe na decodificação do JSON, retorna None ou gera um log
                print(f"Erro ao decodificar o JSON da URL: {url}")
                return None
        else:
            return response.text

    except requests.exceptions.RequestException as e:
        print(f"Erro na requisição para a URL: {url} - {e}")
        return None
    
saida = ''
url = ''
total = 0
query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM carga WHERE divisao='direp'" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
json_data = conectar_siscap_new(url,return_json=True)
data = json.loads(json_data)
numbers = [patent['numero'] for patent in data['patents']]
numbers = ['102019009508']
numbers = lista
for numero in numbers:
    total = total + 1
    if (total>1000):
        break
    url = montar_url_parecer(numero)
    if url is not None:
        print(numero)
        print(url)
        
        texto_relatorio = conectar_siscap_new(url,return_json=False)
        if texto_relatorio is not None:
            #caminho_do_arquivo='document.txt'
            #with open(caminho_do_arquivo, 'w', encoding='utf-8') as arquivo:
            #    arquivo.write(texto_relatorio)

            ##print(texto_relatorio)
            #pattern = r"(D\d+)\s+([A-Z]+\s?\d+)\s+([A-B]\d)?\s+(\d{2}\/\d{2}\/\d{4})"
            #pattern = r"(D\d+)\s+([A-Z]+\s?\d+\/?\d+)\s?([A-B]\d?)?\s+(\d{2}\/\d{2}\/\d{4})"
            pattern = r"(D\d+)\s+([A-Z]+\s?\d+\/?\d+-?[0-9]?)\s?(\(?[A-B]\d?\)?)?\s+(\([A-Za-z\s]+(?:\[[A-Z]{2}\])?\))?\s+(\d{2}\/\d{2}\/\d{2,4})"
            pattern = r"(D\d+)\s+((?:[A-Z]{2})\s*\d{4,10}(?:-\d[A-Z]?)?)\s+.*?(\d{2}/\d{2}/\d{4})"
            pattern = r"(D\d+)\s+((?:[A-Z]{2,3})\s*\d{4,10}(?:-\d[A-Z]?)?)\s+.*?(\d{2}/\d{2}/\d{4})"
            pattern = r"(D\d+)\s+((?:[A-Z]{2,3})\s*\d{4,10}(?:-\d[A-Z]?)?)\s+.*?(\d{2}[\/\.]\d{2}[\/\.]\d{4})"

            matches = re.findall(pattern, texto_relatorio)
            for match in matches:
                #codigo, documento, tipo, data = match
                codigo = match[0]
                documento = match[1]
                doc = " ".join(documento.split())
                doc = doc.replace(" ", "")
                doc = doc.replace("/", "")
                doc = doc.replace(".", "")
                doc = doc.replace(",", "")
                doc = doc.replace(";", "")
                doc = doc.split("-")[0]
                data = match[-1]
                data = converter_data2(data)
                #data = datetime.strptime(data, '%d/%m/%Y') # 11/07/2013
                #data = data.strftime('%Y-%m-%d')
                ##print(f"{codigo}: {doc}, Data de Publicação = {data}")
                print(f"INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('{numero}','{codigo}','{doc}','{data}');")
                saida = saida + f"INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('{numero}','{codigo}','{doc}','{data}');\n"

print(saida)
# teste regex https://regex101.com/

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122014021216
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220140212161603380.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122014030028
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220140300281542514.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122014030029
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220140300291542515.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122016008192
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220160081921636447.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122016008203
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220160082031636448.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122017012058
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220170120581561751.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122017013108
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220170131081584152.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019008317
https://siscap.inpi.gov.br/adm/pareceres/difarii/1220190083171335039.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019014139
https://siscap.inpi.gov.br/adm/pareceres/difarii/1220190141391340769.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019017348
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220190173481445492.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019017408
https://siscap.inpi.gov.br/adm/pareceres/dipae/1220190174081189623.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019018710
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220190187101391750.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019019161
https://siscap.inpi.gov.br/adm/pareceres/difarii/1220190191611345671.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019019741
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220190197411384290.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019020154
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220190201541217286.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019022840
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220190228401449886.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019025423
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220190254231771346.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019025630
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220190256301435413.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019026828
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220190268281424350.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122019026829
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220190268291424361.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020000568
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220200005681275188.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020001985
https://siscap.inpi.gov.br/adm/pareceres/dibio/1220200019851272517.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('122020001985','D1','US2007224184','2007-09-27');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('122020001985','D2','US7824673','2006-08-10');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112022018674
https://siscap.inpi.gov.br/adm/pareceres/difarii/1120220186741814858.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D1','WO0230395','2002-04-18');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D2','WO03072141','2003-09-04');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D3','WO02072066','2002-09-19');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D4','WO2006059221','2006-06-08');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D5','WO2006079896','2006-08-03');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D6','WO2018175185','2018-09-27');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D8','WO2005113520','2005-12-01');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D9','WO2017070024','2017-04-27');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D10','WO0146185','2001-06-28');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D11','WO0232857','2002-04-25');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D12','WO02080841','2002-10-17');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122023002765
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220230027651977578.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122023019756
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220230197561924330.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('122023019756','D1','WO2019213727','2019-11-14');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112020011171
https://siscap.inpi.gov.br/adm/pareceres/dimat/1120200111711816587.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102019023319
https://siscap.inpi.gov.br/adm/pareceres/dialp/1020190233191929590.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102020006622
https://siscap.inpi.gov.br/adm/pareceres/dicel/1020200066221846012.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102020006622','D1','US7925440','2011-04-12');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102020006622','D2','CN105448098','2016-03-30');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102023026277
https://siscap.inpi.gov.br/adm/pareceres/dinor/1020230262771916299.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112021009213
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120210092131993827.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102022000499
https://siscap.inpi.gov.br/adm/pareceres/dipeq/1020220004991797961.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102022000499','D1','US5151395','1992-09-29');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202020012873
https://siscap.inpi.gov.br/adm/pareceres/dimec/2020200128731528831.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112021013435
https://siscap.inpi.gov.br/adm/pareceres/difarii/1120210134351786124.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112021013435','D1','WO2011100380','2011-08-18');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112021013435','D2','WO2019014100','2019-01-17');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112021013435','D3','WO2019226770','2019-11-28');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112021013435','D4','WO2019226761','2019-11-28');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

MU9100240
https://siscap.inpi.gov.br/adm/pareceres/dimut/MU9100240867882.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI0811199
https://siscap.inpi.gov.br/adm/pareceres/difari/PI08111991097862.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI0900922
https://siscap.inpi.gov.br/adm/pareceres/difarii/PI09009221088863.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI0906181
https://siscap.inpi.gov.br/adm/pareceres/difari/PI09061811458794.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('PI0906181','D1','PI0510883','2007-12-26');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI0912882
https://siscap.inpi.gov.br/adm/pareceres/difari/PI09128821354783.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI0919841
https://siscap.inpi.gov.br/adm/pareceres/dimol/PI09198411463772.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI0920465
https://siscap.inpi.gov.br/adm/pareceres/difarii/PI09204651430765.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI0921237
https://siscap.inpi.gov.br/adm/pareceres/dimol/PI09212371183863.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1000672
https://siscap.inpi.gov.br/adm/pareceres/dimut/PI10006721321857.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('PI1000672','D1','US4057291','1977-11-08');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1001299
https://siscap.inpi.gov.br/adm/pareceres/difari/PI10012991337829.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1003746
https://siscap.inpi.gov.br/adm/pareceres/dimol/PI10037461438799.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1003760
https://siscap.inpi.gov.br/adm/pareceres/dipol/PI10037601221098.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1003946
https://siscap.inpi.gov.br/adm/pareceres/dimut/PI10039461403287.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1004183
https://siscap.inpi.gov.br/adm/pareceres/dimut/PI10041831571352.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1004208
https://siscap.inpi.gov.br/adm/pareceres/difarii/PI10042081143311.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1004831
https://siscap.inpi.gov.br/adm/pareceres/dipol/PI10048311209720.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1011888
https://siscap.inpi.gov.br/adm/pareceres/difari/PI10118881311836.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1012905
https://siscap.inpi.gov.br/adm/pareceres/difarii/PI10129051244923.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('PI1012905','D1','WO2008072032','2008-06-19');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1013364
https://siscap.inpi.gov.br/adm/pareceres/dialp/PI10133641480205.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1102208
https://siscap.inpi.gov.br/adm/pareceres/dimut/PI11022081361396.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('PI1102208','D1','US5975906','1999-11-02');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1103116
https://siscap.inpi.gov.br/adm/pareceres/difarii/PI11031161343631.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1105561
https://siscap.inpi.gov.br/adm/pareceres/dimut/PI11055611460614.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1105730
https://siscap.inpi.gov.br/adm/pareceres/dimol/PI11057301438189.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1105999
https://siscap.inpi.gov.br/adm/pareceres/dimut/PI11059991352527.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

PI1106311
https://siscap.inpi.gov.br/adm/pareceres/dimol/PI11063111460607.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

132015013589
https://siscap.inpi.gov.br/adm/pareceres/dipae/1320150135891204663.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202012011722
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020120117221005686.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202012022499
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020120224991230538.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202012022838
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020120228381031241.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202012022845
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020120228451062373.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202012023481
https://siscap.inpi.gov.br/adm/pareceres/dimut/202012023481961332.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202013002255
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020130022551166279.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202013009916
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020130099161167968.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('202013009916','D1','US2007191983','2007-08-16');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202013013463
https://siscap.inpi.gov.br/adm/pareceres/dimut/202013013463936455.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202013017528
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020130175281163886.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('202013017528','D1','MU8700437','2008-11-04');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('202013017528','D2','US6247834','2001-01-19');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202013018205
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020130182051138345.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202013019250
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020130192501013024.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202013030643
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020130306431094858.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202013033354
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020130333541062055.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202014007119
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020140071191185312.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202014008647
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020140086471165824.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

202017011129
https://siscap.inpi.gov.br/adm/pareceres/dimut/2020170111291793398.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016013498
https://siscap.inpi.gov.br/adm/pareceres/dibio/1120160134981097316.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016015685
https://siscap.inpi.gov.br/adm/pareceres/difel/1120160156851543686.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016018219
https://siscap.inpi.gov.br/adm/pareceres/dipae/1120160182191291999.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112016018219','D1','EP2684436','2014-01-15');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016021786
https://siscap.inpi.gov.br/adm/pareceres/dipae/1120160217861299630.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016022147
https://siscap.inpi.gov.br/adm/pareceres/dipeq/1120160221471578496.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016023062
https://siscap.inpi.gov.br/adm/pareceres/difel/1120160230621619166.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016028205
https://siscap.inpi.gov.br/adm/pareceres/difel/1120160282051619168.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112017002417
https://siscap.inpi.gov.br/adm/pareceres/dipeq/1120170024171578491.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112017015838
https://siscap.inpi.gov.br/adm/pareceres/difel/1120170158381619169.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112018009927
https://siscap.inpi.gov.br/adm/pareceres/difel/1120180099271606649.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112018011919
https://siscap.inpi.gov.br/adm/pareceres/difel/1120180119191619170.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013015675
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130156751496642.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013017629
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130176291483165.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013019574
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130195741264016.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013019699
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130196991367806.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013019993
https://siscap.inpi.gov.br/adm/pareceres/dimut/1120130199931059205.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013022994
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130229941367775.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013023949
https://siscap.inpi.gov.br/adm/pareceres/dicel/1120130239491449030.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013024608
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130246081366875.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013024824
https://siscap.inpi.gov.br/adm/pareceres/dibio/112013024824758936.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013026179
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130261791479978.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013027540
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130275401375914.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013033021
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130330211315446.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013033182
https://siscap.inpi.gov.br/adm/pareceres/difarii/1120130331821337760.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014000495
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120140004951366655.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014000630
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120140006301333764.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014001086
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120140010861412917.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014002748
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120140027481470243.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014007027
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120140070271495038.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014008278
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120140082781499452.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014008804
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120140088041457708.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014009269
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120140092691411159.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014009565
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120140095651477121.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014010347
https://siscap.inpi.gov.br/adm/pareceres/dipae/1120140103471148404.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014011387
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120140113871391805.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014012138
https://siscap.inpi.gov.br/adm/pareceres/dibio/112014012138929779.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014019937
https://siscap.inpi.gov.br/adm/pareceres/ditel/1120140199371574807.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014020793
https://siscap.inpi.gov.br/adm/pareceres/dimec/1120140207931566811.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014024641
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120140246411466873.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014027978
https://siscap.inpi.gov.br/adm/pareceres/dinor/1120140279781372412.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112014032792
https://siscap.inpi.gov.br/adm/pareceres/dibio/1120140327921185140.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015004775
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120150047751354246.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015006343
https://siscap.inpi.gov.br/adm/pareceres/dicel/1120150063431595283.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015006953
https://siscap.inpi.gov.br/adm/pareceres/dibio/1120150069531153811.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015013863
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120150138631470443.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015015060
https://siscap.inpi.gov.br/adm/pareceres/dicel/1120150150601563120.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015019603
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120150196031353574.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015023140
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120150231401353540.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015030032
https://siscap.inpi.gov.br/adm/pareceres/dibio/1120150300321266499.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112015030032','D1','EP1061897','2002-09-25');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015032570
https://siscap.inpi.gov.br/adm/pareceres/dibio/1120150325701258149.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112015032811
https://siscap.inpi.gov.br/adm/pareceres/dimec/1120150328111537554.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016000345
https://siscap.inpi.gov.br/adm/pareceres/dibio/1120160003451273951.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016002195
https://siscap.inpi.gov.br/adm/pareceres/dimec/1120160021951575235.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016003414
https://siscap.inpi.gov.br/adm/pareceres/dinor/1120160034141539329.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016003644
https://siscap.inpi.gov.br/adm/pareceres/difarii/1120160036441197975.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112016008784
https://siscap.inpi.gov.br/adm/pareceres/dipae/1120160087841311391.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102016024247
https://siscap.inpi.gov.br/adm/pareceres/dipeq/1020160242471499258.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012004079
https://siscap.inpi.gov.br/adm/pareceres/dimec/1020120040791643431.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012010956
https://siscap.inpi.gov.br/adm/pareceres/dinec/1020120109561645323.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012012377
https://siscap.inpi.gov.br/adm/pareceres/dialp/1020120123771315348.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012013367
https://siscap.inpi.gov.br/adm/pareceres/ditel/1020120133671551291.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012015992
https://siscap.inpi.gov.br/adm/pareceres/dialp/1020120159921350964.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012023815
https://siscap.inpi.gov.br/adm/pareceres/dialp/1020120238151298699.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012028509
https://siscap.inpi.gov.br/adm/pareceres/dialp/1020120285091324274.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012030828
https://siscap.inpi.gov.br/adm/pareceres/difari/1020120308281338094.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102012032927
https://siscap.inpi.gov.br/adm/pareceres/dialp/1020120329271465942.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102013017278
https://siscap.inpi.gov.br/adm/pareceres/dimec/1020130172781571290.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102013023577
https://siscap.inpi.gov.br/adm/pareceres/dipae/1020130235771292388.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014002008
https://siscap.inpi.gov.br/adm/pareceres/dipeq/1020140020081413014.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014012053
https://siscap.inpi.gov.br/adm/pareceres/dicel/1020140120531604086.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014013268
https://siscap.inpi.gov.br/adm/pareceres/dicel/1020140132681617478.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014013993
https://siscap.inpi.gov.br/adm/pareceres/dipaq/1020140139931284082.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014013996
https://siscap.inpi.gov.br/adm/pareceres/difel/1020140139961497074.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014021906
https://siscap.inpi.gov.br/adm/pareceres/dipae/1020140219061253114.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102014021906','D1','US4099365','1978-07-11');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014024348
https://siscap.inpi.gov.br/adm/pareceres/dipeq/1020140243481479835.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014024578
https://siscap.inpi.gov.br/adm/pareceres/dipae/1020140245781261172.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102014027536
https://siscap.inpi.gov.br/adm/pareceres/dibio/1020140275361272123.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102014027536','D1','CA2723166','2009-11-05');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102014027536','D2','JPH1077217','1998-03-24');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102015006648
https://siscap.inpi.gov.br/adm/pareceres/difel/1020150066481605888.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

102015019612
https://siscap.inpi.gov.br/adm/pareceres/difel/1020150196121578487.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020004305
https://siscap.inpi.gov.br/adm/pareceres/dinec/1220200043051582965.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020004657
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220200046571425680.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020007757
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220200077571430521.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020007845
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220200078451410162.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020008510
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220200085101410881.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020009181
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220200091811534489.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020010712
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220200107121581384.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020014060
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220200140601738295.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020014740
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220200147401483746.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020015607
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220200156071440137.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020015741
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220200157411637987.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020016644
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220200166441355376.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020017092
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220200170921792764.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020017367
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220200173671530198.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020017751
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220200177511353824.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020017889
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220200178891598153.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020019318
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220200193181459497.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020019976
https://siscap.inpi.gov.br/adm/pareceres/difari/1220200199761415553.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020021367
https://siscap.inpi.gov.br/adm/pareceres/dipaq/1220200213671358908.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020022012
https://siscap.inpi.gov.br/adm/pareceres/difari/1220200220121372200.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020022312
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220200223121484816.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020022771
https://siscap.inpi.gov.br/adm/pareceres/dinor/1220200227711428887.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020023574
https://siscap.inpi.gov.br/adm/pareceres/difari/1220200235741378978.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122020024337
https://siscap.inpi.gov.br/adm/pareceres/difari/1220200243371378979.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021003228
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220210032281480359.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021004607
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220210046071681445.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021004615
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220210046151637984.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021004616
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220210046161637986.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021004669
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220210046691577230.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021006465
https://siscap.inpi.gov.br/adm/pareceres/dimec/1220210064651673371.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021007885
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220210078851581700.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021014646
https://siscap.inpi.gov.br/adm/pareceres/ditem/1220210146461659681.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021015578
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220210155781471840.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021019202
https://siscap.inpi.gov.br/adm/pareceres/dialp/1220210192021539157.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021019888
https://siscap.inpi.gov.br/adm/pareceres/dicel/1220210198881536390.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122021025799
https://siscap.inpi.gov.br/adm/pareceres/difarii/1220210257991593130.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122022001757
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220220017571727409.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122022017025
https://siscap.inpi.gov.br/adm/pareceres/dimol/1220220170251704021.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122022017178
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220220171781669136.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122022017195
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220220171951669137.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122022019084
https://siscap.inpi.gov.br/adm/pareceres/ditel/1220220190841669138.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

122022020636
https://siscap.inpi.gov.br/adm/pareceres/dimec/1220220206361731243.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012008983
https://siscap.inpi.gov.br/adm/pareceres/difari/1120120089831338789.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012011128
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120120111281394676.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012017243
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120120172431488430.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012017257
https://siscap.inpi.gov.br/adm/pareceres/dicel/1120120172571190646.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012023010
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120120230101391791.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012026730
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120120267301360940.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012026999
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120120269991373716.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012029457
https://siscap.inpi.gov.br/adm/pareceres/ditex/1120120294571300386.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112012030594
https://siscap.inpi.gov.br/adm/pareceres/dipol/1120120305941207523.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112012030594','D1','GB664811','1952-01-16');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013000811
https://siscap.inpi.gov.br/adm/pareceres/ditex/1120130008111233722.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013001671
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130016711311405.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013001754
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130017541360091.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013003250
https://siscap.inpi.gov.br/adm/pareceres/dipol/1120130032501289875.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013003657
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130036571349324.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013004702
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130047021354299.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013007315
https://siscap.inpi.gov.br/adm/pareceres/dipeq/1120130073151496439.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112013007315','D6','WO2009049676','2009-04-23');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112013007315','D7','CN101610493','2009-12-23');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013009001
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130090011304296.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013010362
https://siscap.inpi.gov.br/adm/pareceres/dimol/1120130103621442668.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013013225
https://siscap.inpi.gov.br/adm/pareceres/dialp/1120130132251424337.txt

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

112013014036
https://siscap.inpi.gov.br/adm/pareceres/dibio/1120130140361062473.txt
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('122020001985','D1','US2007224184','2007-09-27');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('122020001985','D2','US7824673','2006-08-10');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D1','WO0230395','2002-04-18');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D2','WO03072141','2003-09-04');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D3','WO02072066','2002-09-19');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D4','WO2006059221','2006-06-08');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D5','WO2006079896','2006-08-03');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D6','WO2018175185','2018-09-27');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D8','WO2005113520','2005-12-01');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D9','WO2017070024','2017-04-27');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D10','WO0146185','2001-06-28');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D11','WO0232857','2002-04-25');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112022018674','D12','WO02080841','2002-10-17');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('122023019756','D1','WO2019213727','2019-11-14');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102020006622','D1','US7925440','2011-04-12');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102020006622','D2','CN105448098','2016-03-30');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102022000499','D1','US5151395','1992-09-29');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112021013435','D1','WO2011100380','2011-08-18');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112021013435','D2','WO2019014100','2019-01-17');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112021013435','D3','WO2019226770','2019-11-28');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112021013435','D4','WO2019226761','2019-11-28');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('PI0906181','D1','PI0510883','2007-12-26');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('PI1000672','D1','US4057291','1977-11-08');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('PI1012905','D1','WO2008072032','2008-06-19');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('PI1102208','D1','US5975906','1999-11-02');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('202013009916','D1','US2007191983','2007-08-16');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('202013017528','D1','MU8700437','2008-11-04');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('202013017528','D2','US6247834','2001-01-19');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112016018219','D1','EP2684436','2014-01-15');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112015030032','D1','EP1061897','2002-09-25');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102014021906','D1','US4099365','1978-07-11');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102014027536','D1','CA2723166','2009-11-05');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('102014027536','D2','JPH1077217','1998-03-24');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112012030594','D1','GB664811','1952-01-16');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112013007315','D6','WO2009049676','2009-04-23');
INSERT IGNORE INTO anterioridades (numero, codigo, doc, data) VALUES ('112013007315','D7','CN101610493','2009-12-23');

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [151]:
texto_relatorio = """
Código                                 Documento                                Data de publicação
    D1       MU8203332-3U Disposição construtiva em caixa hermética e                   08/03/2005
             isotérmica aplicada em veículos de transporte de cargas
"""
pattern = r"(D\d+)\s+(US\s?\d[\d.,;]{0,20}\d)\s+([A-Z]\d)\s+(\d{2}/\d{2}/\d{4})"
pattern = r"(D\d+)\s+(US|MU)\s*([A-Z0-9][A-Z0-9.,;\-]{3,20})\s+.*?(\d{2}/\d{2}/\d{4})"
pattern = r"(D\d+)\s+((?:US|MU)\s*[0-9][0-9.,;\-]{3,20})\s+([A-Z]\d)\s+(\d{2}/\d{2}/\d{4})"
pattern = r"(D\d+)\s+((?:US|MU)\s*[0-9][0-9.,;\-]{3,20})\s+([A-Z]\d)\s+.*?(\d{2}/\d{2}/\d{4})"
pattern = r"(D\d+)\s+((?:US|MU)\s*[0-9][0-9.,;\-]{3,20})(?:\s+([A-Z]\d))?\s+.*?(\d{2}/\d{2}/\d{4})"
pattern = r"(D\d+)\s+(([A-Z]{2})\s*[0-9][0-9.,;\-]{3,20})(?:\s+([A-Z]\d))?\s+.*?(\d{2}/\d{2}/\d{4})"
pattern = r"(D\d+)\s+((?:[A-Z]{2,3})\s*\d{4,10}(?:-\d[A-Z]?)?)\s+.*?(\d{2}[\/\.]\d{2}[\/\.]\d{4})"

#texto_relatorio = "D1 MU8203332  17/06/2010"
texto_relatorio = "D1                                                JP0592914                               16/04/1993"
matches = re.findall(pattern, texto_relatorio)
documento_formatado=''
for match in matches:
    codigo, documento, data_publicacao   = match
    documento_formatado = " ".join(documento.split())
    documento_formatado = documento_formatado.replace(" ", "")
    print(f"{codigo}: {documento_formatado}, Data de Publicação = {data_publicacao}")
documento_formatado=documento_formatado.replace(',','')
documento_formatado=documento_formatado.replace('.','')
documento_formatado=documento_formatado.replace(';','')
documento_formatado = documento_formatado.split("-")[0]
print("resposta:",documento_formatado)

D1: JP0592914, Data de Publicação = 16/04/1993
resposta: JP0592914

In [47]:
from urllib.request import urlopen
from urllib.error import HTTPError, URLError

# https://patents.google.com/patent/US2013182757A1/en?oq=US2013182757
doc = "US20030065257" # ok
doc = "US2013182757"  # Certifique-se de que o valor de 'doc' é válido
doc = "US2013177069"  # Certifique-se de que o valor de 'doc' é válido
url = f"https://patents.google.com/patent/{doc}A1/en?oq={doc}"

tentar_novamente = False
try:
    html = urlopen(url)
    content = html.read()
    print("Página carregada com sucesso.")
except HTTPError as e:
    print(f"Erro HTTP: {e.code} - {e.reason}")
    tentar_novamente = True
except URLError as e:
    print(f"Erro de URL: {e.reason}")
    tentar_novamente = True
except Exception as e:
    print(f"Erro inesperado: {e}")
    tentar_novamente = True
    
if tentar_novamente:
    novo_doc = doc[:6] + '0' + doc[6:]
    url = f"https://patents.google.com/patent/{novo_doc}A1/en?oq={novo_doc}"

    tentar_novamente = False
    try:
        html = urlopen(url)
        content = html.read()
        print("Página carregada com sucesso.")
    except HTTPError as e:
        print(f"Erro HTTP: {e.code} - {e.reason}")
        tentar_novamente = True
    except URLError as e:
        print(f"Erro de URL: {e.reason}")
        tentar_novamente = True
    except Exception as e:
        print(f"Erro inesperado: {e}")
        tentar_novamente = True

Erro HTTP: 404 - Not Found
Página carregada com sucesso.

In [7]:
        url = 'https://siscap.inpi.gov.br/adm/pareceres/difel/1020130167311459844.txt'
        texto_relatorio = conectar_siscap_new(url,return_json=False)
        pattern = r"(D\d+)\s+([A-Z]+\s?\d+\/?\d+)\s?([A-B]\d?)?\s+(\d{2}\/\d{2}\/\d{4})"
        matches = re.findall(pattern, texto_relatorio)
        for match in matches:
            codigo, documento, tipo, data = match
            doc = " ".join(documento.split())
            doc = doc.replace(" ", "")
            doc = doc.replace("/", "")
            data = datetime.strptime(data, '%d/%m/%Y') # 11/07/2013
            data = data.strftime('%Y-%m-%d')
            ##print(f"{codigo}: {doc}, Data de Publicação = {data}")
            print(f"INSERT INTO anterioridades (numero, codigo, doc, data) VALUES ('{numero}','{codigo}','{doc}','{data}');")
            saida = saida + f"INSERT INTO anterioridades (numero, codigo, doc, data) VALUES ('{numero}','{codigo}','{doc}','{data}');\n"

INSERT INTO anterioridades (numero, codigo, doc, data) VALUES ('122021026661','D1','EP2239925','2010-10-13');
INSERT INTO anterioridades (numero, codigo, doc, data) VALUES ('122021026661','D2','US2008037192','2008-02-14');

D:\Users\abrantes\.conda\envs\LangChain\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'siscap.inpi.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [ ]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

# https://otimistarj.pythonanywhere.com/chat?numero=PI1101142&doc=US2009077666
# https://patents.google.com/patent/US20090077666A1/en?oq=US2009077666
# https://patents.google.com/patent/US2009077666A1/en?oq=US2009077666

doc = 'US20090077666'
url = f"https://patents.google.com/patent/{doc}A1/en?oq={doc}"
print(url)
html = urlopen(url)
bs = BeautifulSoup(html.read(),'html.parser')
nameList = bs.findAll("section", {"itemprop":"description"})
for name in nameList:
    texto_D1 = name.getText()
print(texto_D1)

In [20]:
import mysql.connector
conexao = mysql.connector.connect(host='localhost',user='root',password='',database='producao')
cursor = conexao.cursor()

In [25]:
import requests

comando = f"select * from arquivados where despacho='16.1' and anulado=0 limit 200"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
# print(resultado)
for linha in resultado:
    numero = linha[2]
    print(numero)
    texto = numero
    comando = f"select * from publicados where numero={numero}"
    cursor.execute(comando)
    resultado2 = cursor.fetchall()
    print(resultado2[0][2])
    texto = texto + ', Depositante: ' + resultado2[0][2]
    
    comando = f"select * from titulo where numero={numero}"
    cursor.execute(comando)
    resultado2 = cursor.fetchall()

    if not resultado2:     # se vazio, pula
        print("Sem registro em título — pulando.")
        continue

    print(resultado2[0][5])
    texto = texto + ', Título: ' + resultado2[0][5]
    print(resultado2[0][6])
    texto = texto + ', Resumo: ' + resultado2[0][6]

    comando = f"select * from revistas4 where numero like '{numero}%' and inid='72'"
    cursor.execute(comando)
    resultado2 = cursor.fetchall()
    print(resultado2[0][3])
    texto = texto + ', Inventores: ' + resultado2[0][3]

    print("--")
    
    query = f"O que voce sabe sobre esta patente, em qespecial se recebeu algum prêmio ou destaque: {texto}"
    # print(query)
    
    url = "https://api.openai.com/v1/chat/completions"
    data_json = {
        "model": "gpt-4o-mini",  # Use o modelo desejado, como 'gpt-4'
        "messages": [
            {"role": "user", "content": query}
        ]
    }
    headers = {
        "Authorization": f"Bearer {openai_api_key}",
        "Content-Type": "application/json"
    }
    response = requests.post(url, headers=headers, json=data_json, verify=False)
    if response.status_code == 200:
        resposta = response.json()
        resumo = resposta['choices'][0]['message']['content']
        resumo = resumo.replace("'","")
        if "não encontrei" in resumo.lower():
            print("Não encontrei nada sobre esta patente na internet.")
        else:        
            print(resumo)
    else:
        print(f"Erro {response.status_code}: {response.text}")

102012000058
VETCO GRAY CONTROLS LIMITED (GB)
M?TODO DE MONITORAMENTO DA OPERA??O DE UM SISTEMA DE CONTROLE DE PRODU??O DE HIDROCARBONETO SUBMARINO E SISTEMA DE CONTROLE DE PRODU??O DE HIDROCARBONETO SUBMARINO
Trata-se de um m?todo de monitoramento da opera??o de um sistema de controle de produ??o de hidrocarboneto submarino que compreende monitorar pelo menos um dispositivo submarino do sistema e, se o dispositivo falhar em uma condi??o de seguran?a/falha, enviar uma indica??o disso sem fio
NARESH KUNCHAKOORI, GOPALAKRISHNA GUDIVADA
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente mencionada, com o número 102012000058, foi depositada pela VETCO GRAY CONTROLS LIMITED e aborda um método de monitoramento da operação de um sistema de controle de produção de hidrocarbonetos submarinos. O foco principal dessa invenção é a capacidade de monitorar dispositivos submarinos e detectar falhas, especialmente em situações de segurança, enviando essas informações de forma wireless.

No que diz respeito a prêmios ou destaques, não tenho acesso a informações específicas sobre reconhecimentos ou prêmios que essa patente tenha recebido. No entanto, a relevância de inovações na indústria de petróleo e gás pode levar a prêmios em feiras e eventos especializados, dada a importância de sistemas de monitoramento eficazes na segurança e eficiência da produção submarina.

Para obter mais informações sobre prêmios ou reconhecimentos específicos associados a essa patente, seria ideal consultar bases de dados de propriedade intelectual, registros de patentes ou publicações do setor relevantes.
102012000059
GENERAL ELECTRIC COMPANY (US)
M?TODO PARA FORNECER MONITORAMENTO DE ENERGIA
M?TODO. Sistemas, m?todos e aparelho para fornecer gerenciamento de energia (148) utilizando um medidor de pot?ncia (105) s?o fornecidos. Uma solicita??o por uma interface de usu?rio gr?fica (120) pode ser recebida por um medidor de pot?ncia (105) em comunica??o com um dispositivo externo. A interface de usu?rio gr?fica solicitada pode ser associada a pelo menos um dentre (i) opera??o do medidor de pot?ncia (105) ou (ii) abastecimento de pot?ncia el?trica a uma ou mais cargas. Com base, pelo menos em parte, na solicita??o recebida, as informa??es associadas ? interface de usu?rio gr?fica podem ser geradas pelo medidor de pot?ncia (105) e comunicadas ao dispositivo externo (120)
BALAKRISHNA PAMULAPARTHY, KANAKA VENKATA SURYA MANOJ KUMAR VADALI
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente US102012000059, depositada pela General Electric Company, refere-se a um método para fornecer monitoramento e gerenciamento de energia utilizando um medidor de potência. O resumo indica que o sistema permite que um medidor de potência receba solicitações para uma interface de usuário gráfica de um dispositivo externo. Essa interface pode estar relacionada tanto à operação do medidor de potência quanto ao fornecimento de energia elétrica a uma ou mais cargas. A patente descreve como informações associadas a essa interface podem ser geradas e comunicadas ao dispositivo externo com base nas solicitações recebidas.

Quanto a prêmios ou destaques específicos recebidos pela patente ou pelos inventores, essa informação não é disponibilizada em bases de dados públicas de patentes, e geralmente, prêmios específicos são atribuídos em contextos distintos, como conferências de tecnologia ou inovação. O reconhecimento de uma patente pode variar conforme seu impacto na indústria, seu uso prático e inovação. Para informações mais detalhadas sobre prêmios ou reconhecimentos, seria necessário consultar fontes específicas da General Electric ou de órgãos de premiação em tecnologia.
102012000072
GE AVIATION SYSTEMS LLC (US)
SISTEMA DE GERENCIAMENTO DE VOO, AERONAVE E M?TODO DE OPERA??O DE UMA AERONAVE INCLUINDO UM SISTEMA DE GERENCIAMENTO DE VOO
SISTEMA DE GERENCIAMENTO DE VOO E AERONAVE. Um sistema de gerenciamento de voo (24) para uso em gera??o autom?tica de uma trajet?ria de trajeto de voo (26) para uma aeronave (10) ? fornecido. A trajetoria de trajeto de voo inclui uma pluralidade de pontos de rota (28) e uma pluralidade de vetores (30) se estendendo entre cada ponto de rota da pluralidade de pontos de rota, o sistema de gerenciamento de voo inclui um processador (302) que ? configurado para calcular uma primeira trajet?ria de trajeto de voo (36) que inclui um ponto de rota de origem (40) e um ponto de rota de destino (42), recebe um comando t?tico que indica uma mudan?a durante a trajet?ria do voo, e calculada uma segunda trajet?ria de trajeto de voo (38) com base pelo menos em parte no comando t?tico, a segunda trajet?ria de trajeto de voo calculada inclui um ponto de rota de partida ao longo da primeira trajet?ria de trajeto de voo, um ponto de rota de intercep??o (48) ao longo da primeira trajet?ria de trajeto de voo, e um vetor de partida desde o ponto de rota de partida (46) at? o ponto de rota de intercep??o
RANDY LYNN WALTER
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente número 102012000072, depositada pela GE Aviation Systems LLC, se refere a um sistema de gerenciamento de voo para aeronaves, relacionado à geração automática de trajetórias de voo. O sistema é projetado para calcular tanto uma trajetória inicial quanto uma segunda trajetória de voo em resposta a comandos táticos que podem alterar o curso do voo. Isso inclui a identificação de pontos de rota e vetores entre esses pontos, permitindo uma navegação mais eficiente e adaptativa.

Infelizmente, não tenho informações específicas sobre prêmios ou destaques recebidos por esta patente. Para saber mais sobre prêmios, reconhecimentos ou aplicações específicas, seria necessário consultar bases de dados de patentes, publicações da indústria aeroespacial ou mesmo os comunicados de imprensa da GE Aviation que possam abordar o impacto e as inovações relacionadas a esta tecnologia. Se precisar de informações mais específicas, recomendo acessar a documentação oficial da patente ou explorar as notícias asociadas à GE Aviation sobre essa tecnologia.
102012000093
LEGRAND FRANCE (FR) , LEGRAND SNC (FR)
CAIXA DE ALOJAMENTO PARA APARELHAGEM EL?TRICA E CONJUNTO
A inven??o refere-se a uma caixa de alojamento para aparelhagem el?trica, compreendendo um corpo (2) e um ?rg?o de ancoragem (18) apresentando uma ?rea de recep??o (19) de um ?rg?o de fixa??o da mencionada aparelhagem el?trica (41) e admitindo cara a cara do mencioando corpo (2) uma primeira posi??o para fixar a mencionada aparelhagem ? mencionada caixa (1) com o mencionado ?rg?o de fixa??o, quando a mencionada caixa (1) ? encaixada aflorando e uma segunda posi??o para fixar a mencionada aparelhagem ? mencionada caixa (1) com o mencionado ?rg?o de fixa??o, quando a mencionada caixa (1) ? encaixada em profundidade, o mencionado corpo (2) compreendendo uma chamin? (10), o mencionado ?rg?o de ancoragem (18) sendo anexado interiormente ? chamin? (10) por uma por??o fina de um material pl?stico, sendo que s?o formados conjuntamente a chamin? (10) e o mencionado ?rg?o de ancoragem (18), o mencionado ?rg?o de ancoragem (18) pivota em rela??o ? mencionada chamin? (10) em torno da mencionada por??o fina que forma uma articula??o para a passagem da mencionada primeira posi??o ? mencionada segunda posi??o
EDMO LUIZ FERREIRA GALARCE, FRANK JUVING
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente que você mencionou, com o número 102012000093, é uma invenção relacionada a uma caixa de alojamento para aparelhagem elétrica. O depositante é a Legrand France e Legrand SNC, empresas renomadas no setor de soluções elétricas e de infraestrutura.

O resumo da patente descreve uma caixa que possui um corpo e um órgão de ancoragem, com características que permitem a fixação da aparelhagem elétrica em duas posições diferentes. Isso pode ser útil em diversas aplicações elétricas, proporcionando flexibilidade na instalação de dispositivos. Além disso, a invenção parece incluir elementos que facilitam a articulação e a operação do sistema de fixação.

Quanto a prêmios ou destaques específicos recebidos pela patente ou pela invenção, essa informação não é geralmente divulgada de forma acessível em bancos de dados públicos. Patentes podem ser homenageadas em feiras de tecnologia ou design, mas isso requer uma busca mais detalhada em fontes específicas ou registros da empresa. Recomendo verificar o site da Legrand ou consultar bases de dados de patentes para obter informações adicionais sobre a aplicação da patente e quaisquer reconhecimentos ou prêmios que possam ter sido concedidos.
102012000116
Agrigenetics, INC. (US)
M?TODOS DE FAZER SILAGEM DE MILHO N?O TRANSG?NICO E PARA IDENTIFICAR UMA PLANTA DE MILHO N?O TRANSG?NICA COMPREENDENDO UM GENE DE ?LCOOL CINAM?LICO DESIDROGENASE 2 (CAD2) MUTANTE
GENE E VARIA??ES ASSOCIADAS COM O FEN?TIPO BM1, MARCADORES MOLECULARES, E SEU USO. Esta inven??o diz respeito a genes CAD2 de milho mutantes de ocorr?ncia natural espec?ficos, cujos genes alterados contribuem para o fen?tipo de milho bm1 em linhagens particulares de milho. Em algumas modalidades, composi??es e m?todos s?o fornecidos que utilizam uma mol?cula de ?cido nucleico compreendendo um gene CAD2 mutante, e/ou marcadores ligados a um gene CAD2 mutante
Wei Chen, Nathan J. Vanopdorp, Siva P. Kumpatla, Peizhong Zheng, Peter D. Friedemann, Thomas W. Greene, Dennis Fitzl
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente 102012000116, depositada pela Agrigenetics, Inc. (EUA), refere-se a métodos para fazer silagem de milho não transgênico e para identificar uma planta de milho não transgênica contendo um gene de álcool cinâmico desidrogenase 2 (CAD2) mutante. Essa invenção está relacionada a genes CAD2 mutantes de ocorrência natural que podem influenciar o fenótipo BM1 em certas linhagens de milho.

O foco principal da patente inclui:

1. **Genes Mutantes CAD2**: A patente menciona variações específicas do gene CAD2 que estão associadas a alterações fenotípicas no milho, oferecendo uma base para a seleção de características desejáveis na cultura.

2. **Uso de Marcadores Moleculares**: A inclusão de marcadores moleculares que estão ligados ao gene CAD2 mutante permite identificar e selecionar plantas de milho que carregam as características desejadas, facilitando a melhoria das cultivares.

3. **Métodos de Silagem**: O documento também discute métodos para produzir silagem a partir do milho não transgênico com essas características genéticas específicas, o que pode ter implicações práticas na agricultura e na nutrição animal.

Infelizmente, não possuo informações específicas sobre prêmios ou reconhecimentos recebidos por essa patente ou pela tecnologia relacionada. Geralmente, patentes em biotecnologia podem ganhar destaque em conferências da área, publicações científicas ou através de sua aplicação comercial, mas detalhes sobre prêmios específicos requerem pesquisa adicional em fontes de notícias ou registros de premiações na área agrícola e biotecnológica.
102012000131
DT ENGENHARIA DE EMPREENDIMENTOS LTDA. (BR/SP)
CORTINA MODULAR SEPARADORA DE CORPOS D ?GUA DE RESERVAT?RIOS, REPRESAS, LAGOAS OU BA?AS
Que se refere a uma cortina modular destinada a separa??o de corpos d?gua contidas em reservat?rios, represas, lagoas ou ba?as, dentre outros, no intuito de separar os corpos d?gua originados de fontes direfentes e que se unem em um reservat?rio comum, tendo como principal intuito da presente patente evitar que ?guas provenientes de mananciais se misturem com ?guas provenientes de vias receptoras de ?guas contaminadas com esgoto dom?stico, comercial e/ou industrial, oriundos dos centros urbanos, permitindo os usos m?ltiplos dos corpos d?gua com o monitoramento e controle de fluxos, vaz?es, e da qualidade das ?guas
JO?O CARLOS GOMES DE OLIVEIRA, FELIPE GOMES DE OLIVEIRA, PROC?PIO GOMES DE OLIVEIRA NETO
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente brasileira de número 102012000131, depositada pela DT Engenharia de Empreendimentos LTDA, refere-se a uma "cortina modular separadora de corpos dágua de reservatórios, represas, lagoas ou baías". O objetivo principal dessa invenção é impedir a mistura de diferentes fontes de água, especificamente separando águas de mananciais de águas contaminadas provenientes de esgoto doméstico, comercial ou industrial. Com isso, a patente visa garantir o monitoramento e controle da qualidade da água, permitindo usos múltiplos dos corpos dágua.

Sobre prêmios ou destaques recebidos por essa patente em particular, não há informações específicas disponíveis. No entanto, geralmente, patentes inovadoras em áreas de tecnologia ambiental e gestão de recursos hídricos podem receber reconhecimento em eventos ou feiras do setor, além de serem citadas em publicações científicas e técnicas. Para informações detalhadas ou atualizações quanto a prêmios específicos, recomenda-se consultar fontes especializadas ou o próprio depositante.
102012000232
Mitsuba Corporation (JP)
MOTOR DE LIMPADOR
Em um motor de limpador incluindo uma unidade de motor tendo um eixo de rota??o, e uma unidade de engrenagem tendo um mecanismo de redu??o de velocidade para reduzir e produzir como sa?da a rota??o reduzida em velocidade, uma primeira engrenagem de redu??o de velocidade formando um mecanismo de redu??o de velocidade ? provida em um lado de extremidade de um eixo de rota??o, um magneto de sensor ? fixado ao outro lado de extremidade do eixo de rota??o, uma placa de controle ? provida de modo a se voltar para o outro lado de extremidade do eixo de rota??o a partir da dire??o axial do eixo de rota??o, um sensor MR para detectar um estado rotacional do eixo de rota??o ? provido para uma por??o de frente da placa de controle para o maneto de sensor, e por??es de extremidade de bobina de bobinas configuradas para gerar uma for?a eletromagn?tica para rodar o eixo de rota??o com base na alimenta??o de corrente de acionamento da placa de controle s?o eletricamente conectadas ? placa de controle
Toshiyuki Amagasa
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente de número 102012000232, depositada pela Mitsuba Corporation, refere-se a um motor de limpador com um design que inclui uma unidade de motor e uma unidade de engrenagem com um mecanismo de redução de velocidade. O resumo indica que o motor foi projetado para fornecer um controle preciso da rotação, utilizando um sensor para detectar o estado rotacional do eixo, além de incluir um magneto de sensor e uma placa de controle que gerencia a alimentação elétrica.

Sobre prêmios ou destaques, não há informações específicas disponíveis sobre essa patente em particular ou se recebeu algum reconhecimento especial. Normalmente, empresas do setor automobilístico e de componentes elétricos como a Mitsuba Corporation se destacam pela inovação em suas tecnologias, mas para detalhes sobre prêmios especificamente relacionados a essa patente, seria necessário consultar registros de prêmios da indústria, publicações da Mitsuba Corporation ou bancos de dados de patentes para informações adicionais.

Se você precisar de mais informações sobre a Mitsuba Corporation ou inovações no campo de motores de limpador, eu ficaria feliz em ajudar!
102012000249
Hypred (FR)
DISPOSITIVO DE CONEX?O DE CUBAS DE ARMAZENAGEM E PROCESSO DE ADMINISTRA??O DA CONEX?O DE UMA CUBA DE ARMAZENAGEM
Pedido de patente de inven??o para DISPOSITIVO DE CONEX?O DE CtJBAS DE ARMAZENAGEM E PROCESSO DE ADMINISTRA??O DA CONEX?O DE UMA CUBA DE ARMAZENAGEM O dispositivo compreende uma tubula??o (18) que tem uma entrada (18A) capaz de ser conectada ? alimenta??o e uma sa?da (18B) capaz de ser conectada ? cuba de armazenagem (10), bem como uma c?mera de reten??o (20) que ? bifurcada da tubula??o (18) e que ? equipada com uma v?lvula de amostragem (24). A tubula??o compreende uma v?lvula para carga (22) localizacla entre a c?mera de reten??o e a sa?da da tubula??o. Depois que o produto originado da alimenta??o ? transportado para a c?mera de reten??o (20), e a amostra da mistura do produto presente na c?mera de reten??o (20) ? retirada para verilicar a informa??o referente ao tipo desta mistura, e caso a informa??o verificada corresponda ? informa??o esperada, a v?lvula para carga (22) ? aberta para estabelecer a liga??o da sa?da da tubula??o (18) com a cuba (10)
R?gis Galland
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente mencionada, com o número 102012000249, foi depositada pela empresa Hypred, com sede na França. O título da patente é "Dispositivo de conexão de cubas de armazenagem e processo de administração da conexão de uma cuba de armazenagem".

### Descrição do Dispositivo
O dispositivo aborda um sistema para conectar cubas de armazenagem, incluindo uma tubulação com entrada e saída conectadas a um sistema de alimentação e a uma cuba de armazenagem, respectivamente. A tubulação incorpora uma câmara de retenção equipada com uma válvula de amostragem. O sistema permite coletar uma amostra do produto antes que ele seja enviado à cuba de armazenagem, garantindo que a mistura do produto atenda às especificações esperadas antes de ser transferida para o armazenamento.

### Aspectos Relevantes
1. **Invenção e Processo**: Este dispositivo parece focar na automação e controle de qualidade do produto armazenado, garantindo que somente as misturas adequadas sejam enviadas para as cubas de armazenagem.
2. **Inovação Tecnológica**: A combinação da câmara de retenção com a válvula de amostragem sugere um avanço na forma como produtos químicos ou misturas podem ser controlados e gerenciados antes do armazenamento, minimizando riscos e desperdícios.
3. **Inventor**: R?gis Galland é mencionado como o inventor da patente, o que pode indicar seu papel direto na concepção e desenvolvimento do dispositivo.

### Destaques ou Prêmios
No que se refere a prêmios ou reconhecimento, não há informações disponíveis na descrição da patente que indiquem se ela recebeu algum prêmio ou destaque específico. Geralmente, informações sobre prêmios ou reconhecimentos associados a patentes podem não ser amplamente divulgadas, exceto se forem publicados em conferências, revistas especializadas ou comunicados de imprensa da empresa.

### Considerações Finais
Para obter informações mais detalhadas sobre o status da patente, inovações associadas, ou reconhecimento da patente dentro da indústria, pode ser útil consultar bancos de dados de patentes, publicações do setor, ou diretamente os canais de comunicação da Hypred.
102012000289
Hughes Network Systems, LLC (US)
SISTEMA DE COMUNICA??ES DO SAT?LITE DE ALTA CAPACIDADE E M?TODO PARA UM SISTEMA DE COMUNICA??ES DO SAT?LITE DE ALTA CAPACIDADE
SISTEMA DE COMUNICA??ES POR SAT?LITE DE ALTA CAPACIDADE. A presente inven??o refere-se a um sistema de comunica??es por sat?lite de alta capacidade incluindo um sat?lite com um feixe para uma liga??o descendente avan?ada, focada em um ?rea geogr?fica para a qual maior capacidade desproporcional ? desejada, um concentrador localizado em uma ?rea geogr?fica para a qual a menor capacidade desproporcional ? desejada, comparado ? localiza??o de um VSAT, no VSAT localizado na ?rea onde um feixe para uma liga??o descendente avan?ada recebido pelo VSAT a partir do sat?lite n?o se sobrep?em com um feixe para uma liga??o descendente de retorno recebido pelo concentrador a partir de um sat?lite
Dave Ross, Stanley Kay, Adrian Morris
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente mencionada (nº 102012000289) é uma invenção relacionada a um sistema de comunicações por satélite de alta capacidade. A depositante é a Hughes Network Systems, LLC, uma empresa conhecida na indústria de comunicações por satélite e redes. Este sistema parece ser projetado para operar de maneira eficiente em áreas geográficas com diferentes demandas de capacidade, utilizando um satélite que fornece feixes direcionais específicos para atender a essas necessidades.

Infelizmente, não tenho informações sobre prêmios ou destaques específicos que essa patente ou a tecnologia associada possa ter recebido. Patentes em si geralmente não são premiadas, mas podem ser parte de inovações que recebem reconhecimento em conferências, publicações, ou prêmios da indústria. Para saber mais sobre prêmios ou reconhecimentos, seria necessário consultar registros específicos de inovação ou da indústria de telecomunicações.

Se você estiver buscando mais detalhes concretos sobre a aplicação da tecnologia ou o impacto dela no setor, recomenda-se verificar publicações acadêmicas, artigos da indústria ou comunicados de imprensa da própria Hughes Network Systems.
102012000290
IFP ENERGIES NOUVELLES (FR)
PROCESSO DE PREPARA??O DE UM CATALISADOR COMPREENDENDO UMA ZE?LITA DESALUMINADA USY E PROCESSO DE HIDROCRAQUEAMENTO E/OU DE HIDROTRATAMENTO DE CARGAS DE HIDROCARBONETO
PROCESSO DE HIDROCRAQUEAMENTO, UTILIZANDO UM CATALISADOR ZEOLITICO, CONTENDO DUAS FUN??ES HIDROGENANTES DISTINTAS. A inven??o refere-se a um processo de hidrocraqueamento e/ou de hidrotratamento de cargas hidrocarbonadas utilizando-se um catalisador que compreende pelo menos um elemento hidrodesidrogenante escolhido no grupo formado pelos elementos do grupo VIB e do grupo VIII n?o nobre considerado sozinho ou em mistura da classifica??o peri?dica, e um suporte compreendendo pelo menos uma matriz mineral porosa e pelo menos uma zeolita desaluminada USY que apresenta uma rela??o at?mica global de sil?cio sobre alum?nio compreendida entre 2,5 e 10, uma fra??o ponderal de ?tomo de alum?nio extra-rede superior a 10 %, em rela??o ? massa total do alum?nio presente na zeolita, um volume mesoporoso medido por porosimetria ao nitrog?nio superior a 0,07 ml.g , e um par?metro cristalino a0 da malha elementar superior a 24,28 ?, no qual uma quantidade de elemento n?quel compreendida entre 0,5 e 3 % em peso em rela??o ? massa total da zeolita ? depositada sobre essa zeolita USY e no qual esse catalisador est? sob a forma sulfurada
JEREMY FRANCIS, NICOLAS BATS, CHRISTOPHE PICHON, LAURENT SIMON, EMMANUELLE GUILLON, AVELINO CORMA
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente com o número 102012000290 foi depositada pela empresa francesa IFP Energies Nouvelles e se refere a um processo de hidrocraqueamento e/ou hidrotratamento de cargas hidrocarbonadas utilizando um catalisador zeolítico específico. O resumo da patente indica que o catalisador contém duas funções hidrogenantes distintas e é baseado em uma zeolita desaluminada USY com características particulares, como uma relação atômica de silício para alumínio e um parâmetro cristalino específico.

A invenção se concentra em otimizar o processo de hidrocraqueamento, que é uma técnica importante na indústria petroquímica para a conversão de petróleo bruto em produtos mais leves e úteis, como gasolina e diesel, ao mesmo tempo buscando melhorar a eficiência e a atividade do catalisador utilizado.

Em relação a prêmios ou destaques recebidos pela patente, a informação específica sobre reconhecimento ou premiações não é tão facilmente acessível, a menos que seja divulgada publicamente ou registrada em fontes relevantes. A indústria de patentes frequentemente submete suas inovações a conferências e competições, mas para informações exatas sobre reconhecimento, seria necessário consultar bases de dados de patentes, publicações especializadas ou notícias do setor que possam documentar esses aspectos.

Se você tiver interesse em informações adicionais, como análises de patente, impacto no setor ou detalhes mais técnicos, eu posso ajudar!
102012000329
Grendene S.A. (BR/RS)
CAL?ADO E ACESS?RIO DE VESTU?RIO COMPREENDENDO SUPERF?CIE HOLOGR?FICA E PROCESSO DE PRODU??O DOS MESMOS
A presente inven??o refere-se acal?ados e/ou acess?rios de vestu?rio compreendendo superf?cie hologr?fica e o processo de produ??o dos mesmos, em qua a superf?cie hologr?fica possui grau de transpar?ncia e opcionalmente incorpora tanto elementos, motivos ou aplica??es gr?ficas bi ou tridimensionais, onde a referida superf?cie hologr?fica est? disposta em pelo menos uma por??o do cal?ado e/ou acess?rio
Edson Matsuo
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente 102012000329, registrada pela Grendene S.A., descreve um calçado e/ou acessório de vestuário que apresenta uma superfície holográfica, além de um processo para a sua produção. A inovação se destaca por incorporar uma superfície que possui um grau de transparência e, opcionalmente, elementos gráficos bi ou tridimensionais.

Infelizmente, não tenho informações específicas sobre se essa patente recebeu prêmios ou destaques. Contudo, a Grendene é uma empresa conhecida por suas inovações e esforços em design e tecnologia na indústria do calçado, o que pode indicar que a patente, em si, é uma parte importante de suas estratégias de mercado.

Se você estiver interessado em mais detalhes sobre a comercialização ou impactos dessa patente, recomenda-se consultar fontes relacionadas a inovações em moda ou registros da empresa, como comunicados de imprensa, notícias do setor e artigos acadêmicos.
102012000340
Grendene S.A. (BR/RS)
CAL?ADO COMPREENDENDO SISTEMA DE CABEDAL ENCAIX?VEL
SISTEMA DE CABEDAL ENCAIX?VEL, CAL?ADO E PROCESSO PARA A OBTEN??O DOS MESMOS.A presente inven??o refere-se a um sistema de cabedal encaix?vel composto por pelo menos duas tiras com meios de fixa??o dispostos ao longo de sua regi?o, cal?ado com o sistema de cabedal encaix?vel composto por pelo menos duas tiras uma tira com compreendendo, em uma de suas extremidades, uma dedeira que possui dispositivo(s) de encaixe que se encaixa(m) na sola do cal?ado. A outra tira compreendendo, em uma das suas extermidades, dispositivo(s) de encaixe que se encaixa(m) na sola do cal?ado e sua outra extremidade ? demandada de acordo com o encaixe de uma tira na outra, apresentando versatilidade est?tica e funcional ap permitir a dapatabilidade a qualquer formato/largura de p?s. ? tamb?m revelado processo para obten??o do cabedal de caa?ados
Edson Matsuo
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente que você mencionou, com o código 102012000340, é uma invenção da Grendene S.A., uma empresa brasileira conhecida pela fabricação de calçados, especialmente de plástico. O título da patente refere-se a um "calçado compreendendo sistema de cabedal encaixável". O resumo descreve um sistema inédito que permite que o cabedal (a parte superior do calçado) possa ser encaixado de forma intercambiável, oferecendo versatilidade quanto ao ajuste e à estética do calçado.

Esse tipo de inovação pode ser bastante relevante para o mercado de calçados, pois possibilita personalização e adaptações consoante as variações nos formatos dos pés, além de facilitar a troca de partes do calçado, o que pode ser atraente para os consumidores em termos de moda e funcionalidade.

Em relação a prêmios ou destaques, não tenho informações específicas sobre se essa patente recebeu prêmios ou reconhecimento, dado que minha última atualização foi em outubro de 2023 e informações sobre patentes podem não ter ampla cobertura de notícias fora de círculos especializados. Para obter essas informações, você poderia consultar bancos de dados de patentes, publicações da indústria de calçados, ou mesmo notícias relacionadas à Grendene S.A. e suas inovações.
102012000344
Grendene S.A. (BR/RS)
FORQUILHA COM APLICA??ES TRIDIMENSIONAIS EM PARTES EXTERNAS, PROCESSO PARA SUA OBTEN??O E CAL?ADO COMPREENDENDO A MESMA
. A presente inven??o proporciona forquilhas com aplica??es em mais de uma das dimens?es ou superf?cies externas, bem como processos para usa obten??o. O processo da inven??o compreende forquilhas dotadas aplica??es, incorporadas a forquilha, proporcionando assim a obten??o de motivos e/ou aplica??es gr?ficas tridimensionais diretamente sobre mais de uma de suas superf?cies externas, sendo por isso denominado de forquilha com aplica??es tridimensionais. A obten??o de tais aplica??es nas forquilhas pelo processo da inven??o ocorre em uma s? etapa, proporcionando diversas vantagens t?cnicas, e con?micas e de versatilidade na produ??o industrial, al?m de uma maior produtividade e melhor sustentabilidade ambiental
Edson Matsuo
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente 102012000344, depositada pela Grendene S.A., refere-se a uma invenção que envolve forquilhas com aplicações tridimensionais em suas superfícies externas, bem como o processo de fabricação dessas forquilhas. O foco da invenção é a possibilidade de incorporar motivos ou aplicações gráficas diretamente nas forquilhas, o que se traduz em vantagens como maior versatilidade na produção, eficiência e sustentabilidade ambiental.

Embora eu não tenha informações específicas sobre prêmios ou destaques que essa patente possa ter recebido, inovações na área de design e produção de calçados frequentemente são valorizadas, principalmente quando apresentam benefícios em termos de processos produtivos e sustentabilidade. Grendene, como uma das maiores fabricantes de calçados do Brasil, é conhecida por investir em design e tecnologia, e patentes como essa poderiam, potencialmente, estar alinhadas com essas iniciativas.

Para informações detalhadas sobre prêmios ou reconhecimentos específicos que esta patente possa ter recebido, seria necessário consultar registros específicos ou publicações da empresa, feiras do setor ou órgãos de propriedade intelectual que possam ter promovido eventos ou reconhecimentos relacionados a inovações industriais.
102012000350
Wonderland Nurserygoods Company Limited (HK)
ESTRUTURA DE SUPORTE AJUST?VEL DE UM ASSENTO DE SEGURAN?A PARA CRIAN?A
Trata-se de um estrutura de suporte ajust?vel que inclui um alojamento acoplado a um lado infeior de um assento de seguran?a para crian?a, uma montagem de tubo conectada o alojamento, primeira e segunda linguteas e um bot?o de libera??o. A montagem de tubo inclui um primeiro segmento de tubo e um segmento de tubo telescopicamente conectados, e uma base afixada em uma extremidade mais inferior da montagem de tubo. A primeira lingueta ? oper?vel para bloquear a retra??o do primeiro segmento de tubo no segmento quando o primeiro segmento de tubo est? posicionado em uma posi??o desejada. A segunda lingueta ? oper?vel para bloquear a retra??o do segmento de tubo no alojamento quando o segmento de tubo est? posicionado em uma posi??o desejada. O bot?o de libera??o ? conectado ? primeira lingueta, e ? oper?vel para destravar a primeira ligueta para permitir a retra??o do primeiro segmento de tubo no segundo segmento de tubo. Nessa estrutura, um movimento de retra??o do primeiro segmento de tubo nos egundo segmento de tubo aciona o destravamento da segunda lingueta para permitir a retra??o so segmento de tubo no alolojamento
Zheng-Wen Guo
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente número 102012000350, depositada pela Wonderland Nurserygoods Company Limited (HK), refere-se a uma estrutura de suporte ajustável para um assento de segurança para crianças. A descrição técnica indica que a invenção se concentra na flexibilidade e na segurança do assento, utilizando um sistema de tubos telescópicos e linguetas que permitem a ajuste e a fixação do assento em posições desejadas. A operação de um botão de liberação é uma característica destacada, possibilitando o desbloqueio e o ajuste fácil da estrutura.

No entanto, não tenho informações específicas sobre prêmios ou destaques que essa patente pode ter recebido. Patentes como essa podem ser reconhecidas em feiras de invenções ou em prêmios de design de produtos, mas isso geralmente requer uma pesquisa mais profunda em bancos de dados de patentes ou notícias da indústria. Se você estiver interessado em resultados específicos sobre prêmios ou reconhecimento, sugiro consultar registros de prêmios de inovação ou plataformas de notícias que cubram inovações em produtos para crianças.
102012000351
Wonderland Nurserygoods Company Limited (HK)
ASSENTO DE ELEVA??O
Trata-se de uma assento de eleva??o infantil que inclui uma carca?a de assento,e apoios para o bra?o que podem ser convevientemente colocados em um inv?lucro externo da carca?a de assento. Os apoios para o bra?o podem ser colocados em uma cavid?o de armazenamento da carca?a de assento e posicionados no exterior da cavidade de armazenamento para uso. Quando os apoios para o bra?o s?o recebidos na carca?a de assento, o inv?lucro externo do assento de eleva??o pode ser substancialmente compat?vel com o formato do contorno externo da carca?a de assento. O assento de eleva??o pode, desse modo, ocupar um volume menor
Sharon A. Gillett, Michel H. Gillett, Curtis M. Hartenstine, Guang-Hui Zhao
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente mencionada, com o número **102012000351**, refere-se a um assento de elevação infantil projetado pela Wonderland Nurserygoods Company Limited. O objetivo principal desse dispositivo é proporcionar um assento de elevação compacto, que inclui características inovadoras como apoios para os braços que podem ser armazenados no interior da carcaça do assento e facilmente posicionados para uso quando necessário. Isso permite que o assento mantenha um formato mais aerodinâmico e ocupe menos espaço quando os apoios não estão em uso.

Quanto a prêmios ou destaques recebidos, não tenho informações específicas sobre essa patente em particular que confirmem se ela recebeu algum reconhecimento ou prêmio. Normalmente, informações sobre prêmios ou reconhecimentos relacionados a patentes podem ser acessadas por meio de bases de dados de propriedade intelectual, publicações da indústria ou comunicados de imprensa da empresa depositante. Para obter essas informações, você pode consultar registros de patentes, sites especializados ou entrar em contato diretamente com a Wonderland Nurserygoods Company Limited.
102012000366
Hughes Network Systems, LLC (US)
APARELHO DE SAT?LITE DE USO TRIPLO, SISTEMA DO SAT?LITE DE USO TRIPLO E M?TODO PARA FORNECIMENTO DE UM SISTEMA DO SAT?LITE DE USO TRIPLO
M?TODO E APARELHO PARA UM SISTEMA DO SAT?LITE DE USO TRIPLO. A presente inven??o refere-se a um sistema do sat?lite de uso triplo que inclui um VSAT populacional icnluindo um VSAT, e um sat?lite incluindo um feixe de difus?o para um servi?o de difus?o e um feixe de sinal para um servi?o de banda larga, em cada um do feixe de sinal fornece servi?o de banda larga para VSAt em ?reas de cobertura separadas em uma regi?o geogr?fioca e o feixe de difus?o fornece um servi?o de difus?o para o VSAT populacional na regi?o geogr?fica
Adrian Morris, Dave Ross, Stanley Kay, Pradman Kaul
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente que você mencionou, de número 102012000366, é de propriedade da Hughes Network Systems, LLC e diz respeito a um sistema de satélite de uso triplo. O resumo da patente indica que ela envolve métodos e aparelhos que permitem o uso de um satélite para fornecer diferentes tipos de serviços, incluindo transmissão de dados de banda larga e serviços de difusão.

O conceito de um "sistema de satélite de uso triplo" sugere que o satélite é capaz de suportar múltiplas funções, possivelmente garantindo uma maior eficiência no uso da infraestrutura e oferecendo serviços diversos (como internet e TV) a uma base de usuários (VSATs)

Infelizmente, não tenho acesso a informações específicas sobre prêmios ou destaques que possam ter sido otorgados a esta patente ou à empresa, como reconhecimentos em feiras de tecnologia ou prêmios de inovação. Para saber mais sobre a relevância da patente na indústria, como ela foi recebida ou se houve alguma premiação associada, seria ideal consultar registros de prêmios da área de tecnologia, publicações da companhia em conferências ou relatórios de inovação no setor de comunicações por satélite.
102012000368
TAI-HER YANG (TW)
SISTEMA ACIONADOR DE FOR?A DUAL COM JOGOS DE ENGRENAGENS EPICICLOIDAIS DE TRANSMISS?O EM S?RIE
A presente inven??o prov? um sistema acionador de for?a dual com jogos de engrenagens epicicloidais de transmiss?o em s?rie, no qual o eixo de sa?da e o dispositivo de freio control?vel de cada jogo de engrenagens epicicloidais pdoem ser conectados coaxilamnete em s?rie, ou conectados em pararelo ou n?o em pararelo, o eixo rotativo na extremidade de sa?da e o eixo rotativo na extermidade de entrada de cada jogo de engrenagens epicicloidais podem ser diretamente conectados, ou um dispositivo de transmiss?o intermedi?ria pode ser instladao p?ra conex?o, e atrav?s da opera??o dos dispositivos de freio control?vel, escolher as configura??es estruturais do sistema acionador de for?a dual
TAI-HER YANG
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente mencionada, com o número 102012000368, foi depositada por Tai-Her Yang e está relacionada a um sistema de acionamento de força dual. O foco da invenção é um arranjo que utiliza jogos de engrenagens epicóideas em série, permitindo conexões coaxiais, em paralelo ou não em paralelo, entre os eixos de saída e entrada, com a possibilidade de utilizar dispositivos de freio controláveis.

Infelizmente, não possuo informações sobre prêmios ou destaques específicos que esta patente possa ter recebido. Para obter esse tipo de informação, seria necessário consultar bancos de dados especializados em propriedade intelectual, revistas técnicas ou publicações de patentes, onde novidades e inovações frequentemente são divulgadas. Além disso, organizações que premia inovações e patentes, como instituições de pesquisa ou eventos de tecnologia, podem ter dados relevantes sobre reconhecimentos associados a essa patente.

Se precisar de mais detalhes ou informações específicas sobre a aplicação ou funcionalidade dessa patente, recomendo procurar em bases de dados como o INPI (Instituto Nacional da Propriedade Industrial) ou consultar literatura técnica relacionada.
102012000372
Johnson & Johnson do Brasil Industria e Comercio de Produtos para Sa?de Ltda (BR/SP)
COMPOSI??O COSM?TICA AQUOSA DE PROTETOR SOLAR E USO DA MESMA, M?TODO COSM?TICO PARA APLICA??O DA REFERIDA COMPOSI??O, M?TODO COSM?TICO PARA PREVENIR E CONTROLAR A OLEOSIDADE DA PELE, M?TODO COSM?TICO PARA PROTEGER A PELE DOS DANOS CAUSADOS PELA RADIA??O ULTRAVIOLETA, E PRODUTO COSM?TICO
A presente inven??o refere-se a uma composigao cosm?tica aquosa de protetor solar que compreende pelo menos um agente emulsificante, pelo menos um agente de filtro solar hidrossol?vel e pelo menos um agente de filtro solar lipossol?vel, na qual a dita composi??o apresenta forma de s?rum e ? isenta de particulas absorvedoras de ?leo ou dotada dessas particulas em at? 7% em peso.E tamb?m descrito no presente pedido um m?todo para aplica??o da referida composi??o, um m?todo para preven??o e controle da oleosidade da pele, e ainda um m?todo para proteger a pele dos danos causados pela radia??o ultravioleta.Por fim, ? tamb?m escopo do presente pedido o uso da composi??o revelada para preparar um protetor solar, bem como um produto compreendendo a referida composi??o
Cristina W?lke Vendruscolo, Cinthia Fernanda Zanatta, Gabriela Maria de Luca Moreira, Nilo Lemos Cobeiros
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente que você mencionou (número 102012000372) é uma invenção de uma composição cosmética aquosa de protetor solar, depositada pela Johnson & Johnson do Brasil. A patente abrange uma série de aspectos relacionados à formulação e aplicação desse protetor solar, incluindo:

1. **Composição**: A composição é descrita como uma formulação em forma de soro, que é isenta de partículas absorvedoras de óleo ou contém até 7% em peso dessas partículas, contendo pelo menos um agente emulsificante, um agente de filtro solar hidrossolúvel e um agente de filtro solar lipossolúvel.

2. **Métodos**: Não apenas a composição é coberta pela patente, mas também métodos relacionados à sua aplicação, prevenção e controle da oleosidade da pele, além de métodos de proteção contra danos causados pela radiação ultravioleta.

3. **Produto Cosmético**: A patente também menciona o uso da composição para a elaboração de um produto cosmético, especificamente um protetor solar.

Quanto a prêmios ou destaques, não tenho acesso a informações específicas sobre se esta patente recebeu algum reconhecimento especial ou prêmio após o seu registro. Para encontrar informações adicionais sobre prêmios ou reconhecimento, pode ser necessário consultar bases de dados de patentes, publicações científicas ou o historial de prêmios e reconhecimentos da Johnson & Johnson ou dos inventores envolvidos.

Se você estiver interessado em detalhes mais específicos, como mudanças recentes na patente ou estudos associados, eu recomendaria verificar sites de patentes ou bases de dados de propriedade intelectual.
102012000485
Nippon Steel Corporation (JP)
M?TODO DE PRODU??O DE CHAPA DE A?O EL?TRICO N?O ORIENTADO
- A presente inven??o refere-se a um material de a?o sil?cio, tendo uma composi??o prescrita, que ? aquecido. Uma tira de a?o ? obtida executando-se lamina??o a quente do material de a?o sil?cio aquecido. ? executada a lamina??o a frio da tira de a?o. A seguir, ? executado o recozimento de acabamento da tira de a?o. A temperatura do lado de entrada ? de n?o menos 50<198> e a taxa de tens?o ? de menos que 44/s, mas n?o mais que 220/s no primeiro passe da lamina??o a frio
Kenichi Murakami, Takahide Shimazu, Junichi Takaobushi, Kenta Maeda, Yoshiaki Natori
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente mencionada, 102012000485, depositada pela Nippon Steel Corporation, refere-se a um método de produção de chapa de aço elétrico não orientado. Este tipo de aço é amplamente utilizado em aplicações elétricas e magnéticas, como em transformadores e motores, devido às suas propriedades magnéticas favoráveis e baixa perda de energia.

O resumo da patente destaca uma metodologia que inclui o aquecimento de um material de aço silício seguido pela laminação a quente, a laminação a frio e, finalmente, um recozimento de acabamento. Esse processo é projetado para otimizar as propriedades do aço, garantindo que a chapa resultante tenha características adequadas para as aplicações desejadas.

Em relação a prêmios ou destaques específicos para esta patente, não tenho dados concretos que indiquem se ela recebeu alguma distinção ou prêmio. Informações sobre prêmios associados a patentes específicas nem sempre são documentadas publicamente e podem depender de reconhecimento dentro da indústria ou de eventos específicos. Para informações detalhadas sobre prêmios ou reconhecimentos relacionados a essa patente, recomendo consultar fontes da própria Nippon Steel Corporation ou registros da indústria de aço.
102012000497
Meggitt Aircraft Braking Systems Corporation (US)
SISTEMA DE CONVERS?O E DISTRIBUI??O DE POT?NCIA PARA UM ATUADOR EL?TRICO DE AERONAVE, E, SISTEMA DE CONVERS?O E DISTRIBUI??O DE POT?NCIA DE FREIOS EL?TRICOS DE AERONAVE
SISTEMA DE CONVERS?O E DISTRIBUI??O DE POT?NCIA, PARA UM ATUADOR EL?TRICO DE AERONAVE, E DE FREIOS EL?TRICOS DE AERONAVE. ? provido um sistema de convers?o e distribui??o de pot?ncia de freio el?trico para uso em aeronave. um conjunto de conversores CC-CC ? interposto entre uma fonte de pot?ncia de Cc e uma pluralidade de atuadores de freio el?trico de aeronave. Cada conversor CC-CC tem uma voltagem de sa?da caracter?stica. Os conversores CC-CC s?o inter conectados a uma s?rie aditiva de conex?es para prover uma voltagem de sa?da para a pluralidade de atuadores de freio el?trico de aeronave que compreende a soma das voltagens caracter?sticas dos conversores CC-CC que s?o habilitados em determinado instante. Um controlador manipula um arranjo de comutadores interconectados com o arranjo de conversores CC-CC, de tal forma que o controlador pode seletivamente habilitar ou inibir as alguns dos conversores CC-CC selecionados, conforme desejado. Consequentemente, voltagens diferentes podems er disponibilizados para o atuadores de freio el?trico dependendo da atividade da aeronave, como aterrissagem, taxiamento, estacionamento ou voo. A inven??o reduz o tamanho, peso, custo e ac?mulo de calor associado dos sistemas ateriores de convers?o e distribui??o de pot?ncia
Dennis M. Ciccone, Michael J. Suponcic
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente de número 102012000497, depositada pela Meggitt Aircraft Braking Systems Corporation, descreve um sistema inovador de conversão e distribuição de potência destinado a atuadores elétricos e sistemas de freios elétricos em aeronaves. O sistema utiliza uma série de conversores CC-CC que são interligados para permitir diferentes níveis de tensão de saída, dependendo das necessidades operacionais da aeronave, como durante a decolagem, aterrissagem, taxiamento e estacionamento.

Esse design modular e controlado contribui para uma redução significativa em termos de tamanho, peso, custo e dissipação de calor em comparação com sistemas anteriores. A capacidade de ajustar a tensão disponível para os atuadores de freio conforme a situação operacional é uma melhoria significativa que pode impactar a eficiência e a segurança dos sistemas de controle da aeronave.

Quanto a prêmios ou destaques recebidos, não não tenho informações atualizadas sobre reconhecimentos específicos relacionados a essa patente em particular. Geralmente, patentes podem não receber prêmios, mas seu impacto e inovação podem ser reconhecidos pela comunidade de engenharia e aviação, especialmente se resultarem em avanços significativos na tecnologia aeronáutica.

Para obter informações mais detalhadas, como prêmios ou reconhecimentos específicos, recomenda-se consultar registros de patentes, publicações da indústria de aviação ou comunicados de imprensa da Meggitt e de suas inovações tecnológicas.
102012000524
Electrolux do Brasil S.A. (BR/PR)
SISTEMA PARA DIAGN?STICO DE PELO MENOS UM APARELHO ELETRODOM?STICO, E, APARELHO ELETRODOM?STICO
A presente inven??o est? relacionada a um sistema bastante simples para diagn?stico de eletrodom?sticos atrav?s de um dispositivo port?til (6) leve e de f?cil manuseio, simplificando assim o procedimento de manuten??o do referido aparelho no domic?lio do usu?rio. Para tal, a presente inven??o prov? um sistema para diagn?stico de pelo menos um aparelho eletrodom?stico (2), compreedendo um meio de controle (4) para controlar o funcionamento dos componentes de cada um do dito aparelho eletrodom?stico (2), e um dispositivo prot?til (6) conect?vel ao meio de controle (4) para enviar sinais de comando para o meio de controle (4) e para receber informa??es a partir do meio de controle (4) relativos ? realiza??o de testes dos componentes de cada um do dito aparelho eletrodom?stico (2)
Leandro Siqueira Kudla, Jardel M. sprenger, Rafael Alex Lidani, Bruno Shintate
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente com o número 102012000524, depositada pela Electrolux do Brasil S.A., refere-se a um sistema de diagnóstico para eletrodomésticos. A invenção propõe um método simplificado para diagnosticar falhas em aparelhos eletrodomésticos através de um dispositivo portátil leve e de fácil manuseio. Isso facilita o procedimento de manutenção, tornando-o mais acessível para o usuário em sua residência.

O sistema inclui um meio de controle que gerencia o funcionamento dos componentes do eletrodoméstico e um dispositivo portátil que se conecta a esse meio de controle. Esse dispositivo é utilizado para enviar comandos e receber informações sobre o estado dos componentes do aparelho durante a realização dos testes.

Com relação a prêmios ou destaques, não tenho informações específicas sobre se esta patente recebeu algum reconhecimento ou prêmio. Recomendo que você consulte bancos de dados de patentes, sites de premiação de inovações ou o próprio site da Electrolux para verificar se houve alguma menção a prêmios relacionados a essa tecnologia.
102012000539
Messier-Bugatti-Dowty (FR)
ATUADOR DE FRENAGEM PARA FREIO DE AERONAVE, FREIO PARA AERONAVE E DISPOSITIVO DE FRENAGEM PARA AERONAVE
Atuador de frenagem (1) para freio (2) de aeronave (3), compreendendo:- um motor el?trico (13), - um impulsor (14) acionado pelo motor, - um sensor de posi??o (16) da parte m?vel do motor dotado de ?rg?os emissor e receptor. O motor comporta primeiro e segundo excitadores, adaptados para descolar a partr m?vel do motor e adaptados para serem aliemntados independentemente um do outro. O ?rg?o emissor do sensor de posi??o comporta primeiro e segundo emissores adaptados para serem alimentados independentemente, e o ?rg?o rceeptor gera o sinal representativo da posi??o quando ele ? excitado por um pelo menos dos emissores
Julien Thibault, Florent Nierlich
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente 102012000539, depositada pela Messier-Bugatti-Dowty, descreve um atuador de frenagem para freios de aeronaves, que possui um motor elétrico e um sistema de sensores para monitorar a posição da parte móvel do motor. Este sistema inclui emissores e receptores que operam de forma independente, permitindo um controle mais preciso e eficaz dos freios da aeronave.

Em relação ao reconhecimento ou prêmios recebidos, não tenho informações específicas sobre se essa patente em particular recebeu algum prêmio ou destaque. Normalmente, patentes podem ser reconhecidas em conferências ou exposições de tecnologia, mas isso varia muito dependendo do contexto e da indústria. Para obter detalhes sobre prêmios ou reconhecimentos específicos, seria útil consultar bancos de dados de patentes, publicações da indústria ou notícias relacionadas à Messier-Bugatti-Dowty e suas inovações.
102012000592
CNH AMERICA LLC (US)
SISTEMA PARA PROTE??O DE UM M?DULO DE ALGOD?O
Um sistema e um m?todo para aplica??o de uma camada protetora em um m?dulo de algod?o, de algod?o compactado, que se move em uma dire??o de descarga a partir de um estruturador de m?dulo de algod?o atrav?s de uma extremidade de abertura deste ao longo de uma superf?cie de descarga, o sistema incluindo um aparelho de aplica??o tendo pelo menos um aplicador em comunica??o fluida com pelo menos um tanque para aplica??o de um fluido contido em pelo menos um tanque a pelo menos uma superf?cie superior do m?dulo de algod?o, o fluido sendo aplicado em uma parte externa do m?dulo de algod?o em um estado fluido e solidificado em uma camada de resist?ncia ? ?gua antes da permea??o significativa ? parte externa do m?dulo, de modo a ser capaz de ser removida deste antes do processamento do m?dulo
CHAD D. AERTS, IMANTS EKIS, JOHN H. POSSELIUS, JOSSE H. ORSBORN
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente mencionada (número 102012000592) pertence à CNH America LLC e se refere a um sistema e método para aplicar uma camada protetora em um módulo de algodão. O intuito desse sistema é proteger o algodão compactado durante o transporte e armazenamento, aplicando um fluido que solidifica e cria uma barreira resistente à umidade.

Embora eu não tenha informações específicas sobre prêmios ou destaques que esta patente tenha recebido, inovações nesse campo geralmente são reconhecidas pelo seu impacto na eficiência e na qualidade do produto final. Patentes dessa natureza podem ser avaliadas favoravelmente em contextos industriais e agrícolas, especialmente se resultarem em melhorias significativas no manejo e na preservação do algodão.

Para informações detalhadas sobre prêmios, reconhecimentos ou o impacto dessa patente, você pode consultar bancos de dados de patentes, sites de instituições que promovem inovações agrícolas ou publicações da própria CNH America LLC.
102012000593
Wonderland Nurserygoods Company Limited (CN)
ASSENTO DE SEGURAN?A PARA CRIAN?A E CORREIA DO MESMO
Trata-se de um assento de seguran?a para crian?as que compreendem um encosto, uma por??o de assento conectada uma por??o de extremidade inferior do encosto, e uma correira que inclui uma faixa fixada com o assento de seguran?a para crian?as, e um membro resiliente montado coma faixa. O membro resiliente e a faxia t?m elasticidades diferentes, e a ta??o da faixa causa a deforma??o do membro resiliente. Quando o ve?culo est? sujeito auma colis?o frontal ou parada brusca, o membro resiliente pode deformar para amortecer a for?a de reten??o aplicada pela correia, que pdoe reduzir o risco de ferimentos
Kenny Cheng
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente 102012000593, depositada pela Wonderland Nurserygoods Company Limited, descreve um assento de segurança para crianças projetado para melhorar a proteção em casos de colisões ou paradas bruscas. A invenção se destaca por incluir um membro resiliente que, quando acionado pela força de retenção da correia, deforma-se para amortecer essa força. Essa característica visa reduzir o risco de ferimentos em crianças durante um acidente.

Até onde sei, não há informações específicas sobre se essa patente recebeu algum prêmio ou destaque significativo. Patentes como essa geralmente são publicadas para proteger inovações no campo de produtos de segurança infantil e podem ser um avanço importante em termos de segurança. Para informações mais detalhadas sobre prêmios ou reconhecimentos, seria necessário consultar bancos de dados de patentes especializados ou publicações específicas do setor de segurança infantil.
102012000721
F.I.S. Fabbrica Italiana Sintetici S.P.A. (IT)
PROCESSO PARA PREPARAR 1-(6-METILPIRIDIN-3-IL)-2-[4-(METILSULFONIL)FENIL]ETANONA, UM INTERMEDI?RIO DE ETORICOXIB , USO DE UM CATALISADOR DE PAL?DIO E USO DE UM LIGANTE XANTPHOS
PROCESSO MELHORADO PARA PREPARAR 1-(6-METILPIRIDIN-3-IL)-2-[4-(METILSULFONIL)FENIL]ETANONA, UM INTERMEDI?RIO DE ETORICOXIB. A presente inven??o refere-se a um processo para preparar 1-(6-metilpiridin-3-il)-2-[4-(metilsulfonil)fenil]etanona, um intermedi?rio da s?ntese de Etoricoxib. A s?ntese dos intermedi?rios ?teis para tal prepara??o tamb?m ? descrita
Andrea Castellin, Paolo Stabile
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente 102012000721, depositada pela F.I.S. Fabbrica Italiana Sintetici S.P.A., refere-se a um processo para a preparação de 1-(6-metilpiridin-3-il)-2-[4-(metilsulfonil)fenil]etanona, que é um intermediário na síntese do medicamento Etoricoxib, um anti-inflamatório não esteroidal (AINE) que é utilizado para tratar condições como artrite.

Conforme o resumo da patente, a invenção apresenta um processo melhorado para a síntese deste composto, utilizando um catalisador de paládio e um ligante chamado Xantphos, que é conhecido por melhorar a eficiência e a seletividade nas reações de acilo. A patente destaca não apenas a síntese do intermediário em si, mas também os intermediários utilizados nesta preparação, o que pode contribuir para uma produção mais eficiente e econômica do Etoricoxib.

Quanto a prêmios ou destaques relacionados a essa patente, não há informações facilmente acessíveis que indiquem se recebeu algum prêmio específico ou destaque em conferências ou publicações científicas. Patentes em si não costumam receber prêmios da mesma forma que produtos ou tecnologias, mas podem ser citadas em trabalhos acadêmicos ou reconhecidas na indústria se forem consideradas inovadoras ou impactantes. Para informações mais específicas sobre prêmios ou a popularidade da patente, seria necessário consultar bases de dados de propriedade intelectual ou publicações acadêmicas que discutem inovações farmacêuticas.
102012000726
DANCA COM. E MONTAGEM DE EQUIPAMENTOS ELETR?NICOS LTDA (BR/SP)
SISTEMA PARA CONTROLE DE UMIDADE EM FORNOS INDUSTRIAIS
Idealizada por um sistema para o controle de umidade em fornos industrias, sobretudo nos processos de coc??o de produtos aliment?cios em geral, pertencente ao campo dos equipamentos industriais, nos processos atuais o controle de umidade em fornos industriais ? efetuado por vapor re-circulante, o qual ? produzido por meio de resist?ncias el?tricas, cujo incoveniente se deve ao elevado consumo de energia el?trica ocasionado na gera??o do vapor, al?m do fato da re-circula??o do vapor causar contamina??o do processo de fabrica??o, diferentemenre desses processos, o objeto do presente pedido de patente, refere-se a um sistema para controle de umidade em fornos industriais, cuja novidade ? o fato de utilizar uma n?voa gerada por meio de um equipamento nabulizador ultrass?nico, dita n?voa ? direcionada ao interior do forno industrial por meio de um sistema tubular dotado de ventilador ou turbina
DANILO HENRIQUE MALANCHINO
--

D:\Users\abrantes\InstallAnaconda\envs\langchain_mysql\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.openai.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

A patente com o número 102012000726, depositada pela empresa Danca Comércio e Montagem de Equipamentos Eletrônicos Ltda, se destaca por apresentar um sistema inovador para o controle de umidade em fornos industriais, particularmente em processos de cocção de produtos alimentícios. O sistema inovador utiliza uma névoa gerada por um equipamento nebulizador ultrassônico, em contraste com os métodos tradicionais que dependem da recirculação de vapor gerado por resistências elétricas.

Esse novo método não só promete reduzir o consumo de energia elétrica, mas também evita contaminações associadas à recirculação do vapor, potencializando a segurança e a qualidade dos produtos fabricados.

Em relação a prêmios ou reconhecimentos, não possuo informações específicas sobre essa patente ter recebido algum destaque ou prêmio, visto que esses dados podem não estar amplamente disponíveis em fontes públicas ou atualizadas. É recomendado consultar bases de patentes, publicações industriais, ou até mesmo a própria empresa depositante para informações mais detalhadas sobre reconhecimentos relacionados a essa invenção.
102012000731

IndexError: list index out of range

Agrigenetics, INC. (US)
M?TODOS DE FAZER SILAGEM DE MILHO N?O TRANSG?NICO E PARA IDENTIFICAR UMA PLANTA DE MILHO N?O TRANSG?NICA COMPREENDENDO UM GENE DE ?LCOOL CINAM?LICO DESIDROGENASE 2 (CAD2) MUTANTE
GENE E VARIA??ES ASSOCIADAS COM O FEN?TIPO BM1, MARCADORES MOLECULARES, E SEU USO. Esta inven??o diz respeito a genes CAD2 de milho mutantes de ocorr?ncia natural espec?ficos, cujos genes alterados contribuem para o fen?tipo de milho bm1 em linhagens particulares de milho. Em algumas modalidades, composi??es e m?todos s?o fornecidos que utilizam uma mol?cula de ?cido nucleico compreendendo um gene CAD2 mutante, e/ou marcadores ligados a um gene CAD2 mutante
Wei Chen, Nathan J. Vanopdorp, Siva P. Kumpatla, Peizhong Zheng, Peter D. Friedemann, Thomas W. Greene, Dennis Fitzl
--
Encontre alguma matéria na internet (exceto site do inpi, googlepatents, freepatentsonline.com ou patents.justia.com) que trate desta patente: 102012000116Depositante: Agrigenetics, INC. (US) Título: M?TODOS DE FAZER SILAGEM DE MILHO N?O TRANSG?NICO E PARA IDENTIFICAR UMA PLANTA DE MILHO N?O TRANSG?NICA COMPREENDENDO UM GENE DE ?LCOOL CINAM?LICO DESIDROGENASE 2 (CAD2) MUTANTEResumo: GENE E VARIA??ES ASSOCIADAS COM O FEN?TIPO BM1, MARCADORES MOLECULARES, E SEU USO. Esta inven??o diz respeito a genes CAD2 de milho mutantes de ocorr?ncia natural espec?ficos, cujos genes alterados contribuem para o fen?tipo de milho bm1 em linhagens particulares de milho. Em algumas modalidades, composi??es e m?todos s?o fornecidos que utilizam uma mol?cula de ?cido nucleico compreendendo um gene CAD2 mutante, e/ou marcadores ligados a um gene CAD2 mutanteInventores: Wei Chen, Nathan J. Vanopdorp, Siva P. Kumpatla, Peizhong Zheng, Peter D. Friedemann, Thomas W. Greene, Dennis Fitzl
102012000131
DT ENGENHARIA DE EMPREENDIMENTOS LTDA. (BR/SP)
CORTINA MODULAR SEPARADORA DE CORPOS D ?GUA DE RESERVAT?RIOS, REPRESAS, LAGOAS OU BA?AS
Que se refere a uma cortina modular destinada a separa??o de corpos d?gua contidas em reservat?rios, represas, lagoas ou ba?as, dentre outros, no intuito de separar os corpos d?gua originados de fontes direfentes e que se unem em um reservat?rio comum, tendo como principal intuito da presente patente evitar que ?guas provenientes de mananciais se misturem com ?guas provenientes de vias receptoras de ?guas contaminadas com esgoto dom?stico, comercial e/ou industrial, oriundos dos centros urbanos, permitindo os usos m?ltiplos dos corpos d?gua com o monitoramento e controle de fluxos, vaz?es, e da qualidade das ?guas
JO?O CARLOS GOMES DE OLIVEIRA, FELIPE GOMES DE OLIVEIRA, PROC?PIO GOMES DE OLIVEIRA NETO
--
Encontre alguma matéria na internet (exceto site do inpi, googlepatents, freepatentsonline.com ou patents.justia.com) que trate desta patente: 102012000131Depositante: DT ENGENHARIA DE EMPREENDIMENTOS LTDA. (BR/SP) Título: CORTINA MODULAR SEPARADORA DE CORPOS D ?GUA DE RESERVAT?RIOS, REPRESAS, LAGOAS OU BA?ASResumo: Que se refere a uma cortina modular destinada a separa??o de corpos d?gua contidas em reservat?rios, represas, lagoas ou ba?as, dentre outros, no intuito de separar os corpos d?gua originados de fontes direfentes e que se unem em um reservat?rio comum, tendo como principal intuito da presente patente evitar que ?guas provenientes de mananciais se misturem com ?guas provenientes de vias receptoras de ?guas contaminadas com esgoto dom?stico, comercial e/ou industrial, oriundos dos centros urbanos, permitindo os usos m?ltiplos dos corpos d?gua com o monitoramento e controle de fluxos, vaz?es, e da qualidade das ?guasInventores: JO?O CARLOS GOMES DE OLIVEIRA, FELIPE GOMES DE OLIVEIRA, PROC?PIO GOMES DE OLIVEIRA NETO
102012000232
Mitsuba Corporation (JP)
MOTOR DE LIMPADOR
Em um motor de limpador incluindo uma unidade de motor tendo um eixo de rota??o, e uma unidade de engrenagem tendo um mecanismo de redu??o de velocidade para reduzir e produzir como sa?da a rota??o reduzida em velocidade, uma primeira engrenagem de redu??o de velocidade formando um mecanismo de redu??o de velocidade ? provida em um lado de extremidade de um eixo de rota??o, um magneto de sensor ? fixado ao outro lado de extremidade do eixo de rota??o, uma placa de controle ? provida de modo a se voltar para o outro lado de extremidade do eixo de rota??o a partir da dire??o axial do eixo de rota??o, um sensor MR para detectar um estado rotacional do eixo de rota??o ? provido para uma por??o de frente da placa de controle para o maneto de sensor, e por??es de extremidade de bobina de bobinas configuradas para gerar uma for?a eletromagn?tica para rodar o eixo de rota??o com base na alimenta??o de corrente de acionamento da placa de controle s?o eletricamente conectadas ? placa de controle
Toshiyuki Amagasa
--
Encontre alguma matéria na internet (exceto site do inpi, googlepatents, freepatentsonline.com ou patents.justia.com) que trate desta patente: 102012000232Depositante: Mitsuba Corporation (JP) Título: MOTOR DE LIMPADORResumo: Em um motor de limpador incluindo uma unidade de motor tendo um eixo de rota??o, e uma unidade de engrenagem tendo um mecanismo de redu??o de velocidade para reduzir e produzir como sa?da a rota??o reduzida em velocidade, uma primeira engrenagem de redu??o de velocidade formando um mecanismo de redu??o de velocidade ? provida em um lado de extremidade de um eixo de rota??o, um magneto de sensor ? fixado ao outro lado de extremidade do eixo de rota??o, uma placa de controle ? provida de modo a se voltar para o outro lado de extremidade do eixo de rota??o a partir da dire??o axial do eixo de rota??o, um sensor MR para detectar um estado rotacional do eixo de rota??o ? provido para uma por??o de frente da placa de controle para o maneto de sensor, e por??es de extremidade de bobina de bobinas configuradas para gerar uma for?a eletromagn?tica para rodar o eixo de rota??o com base na alimenta??o de corrente de acionamento da placa de controle s?o eletricamente conectadas ? placa de controleInventores: Toshiyuki Amagasa
102012000249
Hypred (FR)
DISPOSITIVO DE CONEX?O DE CUBAS DE ARMAZENAGEM E PROCESSO DE ADMINISTRA??O DA CONEX?O DE UMA CUBA DE ARMAZENAGEM
Pedido de patente de inven??o para DISPOSITIVO DE CONEX?O DE CtJBAS DE ARMAZENAGEM E PROCESSO DE ADMINISTRA??O DA CONEX?O DE UMA CUBA DE ARMAZENAGEM O dispositivo compreende uma tubula??o (18) que tem uma entrada (18A) capaz de ser conectada ? alimenta??o e uma sa?da (18B) capaz de ser conectada ? cuba de armazenagem (10), bem como uma c?mera de reten??o (20) que ? bifurcada da tubula??o (18) e que ? equipada com uma v?lvula de amostragem (24). A tubula??o compreende uma v?lvula para carga (22) localizacla entre a c?mera de reten??o e a sa?da da tubula??o. Depois que o produto originado da alimenta??o ? transportado para a c?mera de reten??o (20), e a amostra da mistura do produto presente na c?mera de reten??o (20) ? retirada para verilicar a informa??o referente ao tipo desta mistura, e caso a informa??o verificada corresponda ? informa??o esperada, a v?lvula para carga (22) ? aberta para estabelecer a liga??o da sa?da da tubula??o (18) com a cuba (10)
R?gis Galland
--
Encontre alguma matéria na internet (exceto site do inpi, googlepatents, freepatentsonline.com ou patents.justia.com) que trate desta patente: 102012000249Depositante: Hypred (FR) Título: DISPOSITIVO DE CONEX?O DE CUBAS DE ARMAZENAGEM E PROCESSO DE ADMINISTRA??O DA CONEX?O DE UMA CUBA DE ARMAZENAGEMResumo: Pedido de patente de inven??o para DISPOSITIVO DE CONEX?O DE CtJBAS DE ARMAZENAGEM E PROCESSO DE ADMINISTRA??O DA CONEX?O DE UMA CUBA DE ARMAZENAGEM O dispositivo compreende uma tubula??o (18) que tem uma entrada (18A) capaz de ser conectada ? alimenta??o e uma sa?da (18B) capaz de ser conectada ? cuba de armazenagem (10), bem como uma c?mera de reten??o (20) que ? bifurcada da tubula??o (18) e que ? equipada com uma v?lvula de amostragem (24). A tubula??o compreende uma v?lvula para carga (22) localizacla entre a c?mera de reten??o e a sa?da da tubula??o. Depois que o produto originado da alimenta??o ? transportado para a c?mera de reten??o (20), e a amostra da mistura do produto presente na c?mera de reten??o (20) ? retirada para verilicar a informa??o referente ao tipo desta mistura, e caso a informa??o verificada corresponda ? informa??o esperada, a v?lvula para carga (22) ? aberta para estabelecer a liga??o da sa?da da tubula??o (18) com a cuba (10)Inventores: R?gis Galland
102012000289

Hughes Network Systems, LLC (US)
SISTEMA DE COMUNICA??ES DO SAT?LITE DE ALTA CAPACIDADE E M?TODO PARA UM SISTEMA DE COMUNICA??ES DO SAT?LITE DE ALTA CAPACIDADE
SISTEMA DE COMUNICA??ES POR SAT?LITE DE ALTA CAPACIDADE. A presente inven??o refere-se a um sistema de comunica??es por sat?lite de alta capacidade incluindo um sat?lite com um feixe para uma liga??o descendente avan?ada, focada em um ?rea geogr?fica para a qual maior capacidade desproporcional ? desejada, um concentrador localizado em uma ?rea geogr?fica para a qual a menor capacidade desproporcional ? desejada, comparado ? localiza??o de um VSAT, no VSAT localizado na ?rea onde um feixe para uma liga??o descendente avan?ada recebido pelo VSAT a partir do sat?lite n?o se sobrep?em com um feixe para uma liga??o descendente de retorno recebido pelo concentrador a partir de um sat?lite
Dave Ross, Stanley Kay, Adrian Morris
--
Encontre alguma matéria na internet (exceto site do inpi, googlepatents, freepatentsonline.com ou patents.justia.com) que trate desta patente: 102012000289Depositante: Hughes Network Systems, LLC (US) Título: SISTEMA DE COMUNICA??ES DO SAT?LITE DE ALTA CAPACIDADE E M?TODO PARA UM SISTEMA DE COMUNICA??ES DO SAT?LITE DE ALTA CAPACIDADEResumo: SISTEMA DE COMUNICA??ES POR SAT?LITE DE ALTA CAPACIDADE. A presente inven??o refere-se a um sistema de comunica??es por sat?lite de alta capacidade incluindo um sat?lite com um feixe para uma liga??o descendente avan?ada, focada em um ?rea geogr?fica para a qual maior capacidade desproporcional ? desejada, um concentrador localizado em uma ?rea geogr?fica para a qual a menor capacidade desproporcional ? desejada, comparado ? localiza??o de um VSAT, no VSAT localizado na ?rea onde um feixe para uma liga??o descendente avan?ada recebido pelo VSAT a partir do sat?lite n?o se sobrep?em com um feixe para uma liga??o descendente de retorno recebido pelo concentrador a partir de um sat?liteInventores: Dave Ross, Stanley Kay, Adrian Morris
102012000290
IFP ENERGIES NOUVELLES (FR)
PROCESSO DE PREPARA??O DE UM CATALISADOR COMPREENDENDO UMA ZE?LITA DESALUMINADA USY E PROCESSO DE HIDROCRAQUEAMENTO E/OU DE HIDROTRATAMENTO DE CARGAS DE HIDROCARBONETO
PROCESSO DE HIDROCRAQUEAMENTO, UTILIZANDO UM CATALISADOR ZEOLITICO, CONTENDO DUAS FUN??ES HIDROGENANTES DISTINTAS. A inven??o refere-se a um processo de hidrocraqueamento e/ou de hidrotratamento de cargas hidrocarbonadas utilizando-se um catalisador que compreende pelo menos um elemento hidrodesidrogenante escolhido no grupo formado pelos elementos do grupo VIB e do grupo VIII n?o nobre considerado sozinho ou em mistura da classifica??o peri?dica, e um suporte compreendendo pelo menos uma matriz mineral porosa e pelo menos uma zeolita desaluminada USY que apresenta uma rela??o at?mica global de sil?cio sobre alum?nio compreendida entre 2,5 e 10, uma fra??o ponderal de ?tomo de alum?nio extra-rede superior a 10 %, em rela??o ? massa total do alum?nio presente na zeolita, um volume mesoporoso medido por porosimetria ao nitrog?nio superior a 0,07 ml.g , e um par?metro cristalino a0 da malha elementar superior a 24,28 ?, no qual uma quantidade de elemento n?quel compreendida entre 0,5 e 3 % em peso em rela??o ? massa total da zeolita ? depositada sobre essa zeolita USY e no qual esse catalisador est? sob a forma sulfurada
JEREMY FRANCIS, NICOLAS BATS, CHRISTOPHE PICHON, LAURENT SIMON, EMMANUELLE GUILLON, AVELINO CORMA
--
Encontre alguma matéria na internet (exceto site do inpi, googlepatents, freepatentsonline.com ou patents.justia.com) que trate desta patente: 102012000290Depositante: IFP ENERGIES NOUVELLES (FR) Título: PROCESSO DE PREPARA??O DE UM CATALISADOR COMPREENDENDO UMA ZE?LITA DESALUMINADA USY E PROCESSO DE HIDROCRAQUEAMENTO E/OU DE HIDROTRATAMENTO DE CARGAS DE HIDROCARBONETOResumo: PROCESSO DE HIDROCRAQUEAMENTO, UTILIZANDO UM CATALISADOR ZEOLITICO, CONTENDO DUAS FUN??ES HIDROGENANTES DISTINTAS. A inven??o refere-se a um processo de hidrocraqueamento e/ou de hidrotratamento de cargas hidrocarbonadas utilizando-se um catalisador que compreende pelo menos um elemento hidrodesidrogenante escolhido no grupo formado pelos elementos do grupo VIB e do grupo VIII n?o nobre considerado sozinho ou em mistura da classifica??o peri?dica, e um suporte compreendendo pelo menos uma matriz mineral porosa e pelo menos uma zeolita desaluminada USY que apresenta uma rela??o at?mica global de sil?cio sobre alum?nio compreendida entre 2,5 e 10, uma fra??o ponderal de ?tomo de alum?nio extra-rede superior a 10 %, em rela??o ? massa total do alum?nio presente na zeolita, um volume mesoporoso medido por porosimetria ao nitrog?nio superior a 0,07 ml.g , e um par?metro cristalino a0 da malha elementar superior a 24,28 ?, no qual uma quantidade de elemento n?quel compreendida entre 0,5 e 3 % em peso em rela??o ? massa total da zeolita ? depositada sobre essa zeolita USY e no qual esse catalisador est? sob a forma sulfuradaInventores: JEREMY FRANCIS, NICOLAS BATS, CHRISTOPHE PICHON, LAURENT SIMON, EMMANUELLE GUILLON, AVELINO CORMA

In [4]:
import requests



# 2024 = 2295 cartas patentes de nacionais
comando = f"select * from arquivados where despacho='16.1' and anulado=0 and year(data)=2024 and numero in (select numero from publicados where depositante like '%(BR%')"
cursor.execute(comando)
resultado = cursor.fetchall()
df = pd.DataFrame(resultado)
# print(resultado)
prosseguir = False
total = 0
for linha in resultado:
    total = total + 1
    numero = linha[2]
    #if (numero=='102012019427'): 
    prosseguir = True
        
    if (prosseguir):
        print(f"{numero} de {total}/2295")
        texto = numero
        comando = f"select * from publicados where numero={numero}"
        cursor.execute(comando)
        resultado2 = cursor.fetchall()
        #print(resultado2[0][2])
        texto = texto + ', Depositante: ' + resultado2[0][2]
        
        comando = f"select * from titulo where numero={numero}"
        cursor.execute(comando)
        resultado2 = cursor.fetchall()
    
        if not resultado2:     # se vazio, pula
            print("Sem registro em título — pulando.")
            continue
    
        #print(resultado2[0][5])
        #print(resultado2[0][6])
        if resultado2:  # verifica se não está vazio
            texto = texto + ', Título: ' + resultado2[0][5]
            texto = texto + ', Resumo: ' + resultado2[0][6]
        else:
            texto = texto + ', Resumo/Título: N/A'  # ou algum valor padrão
    
        comando = f"select * from revistas4 where numero like '{numero}%' and inid='72'"
        cursor.execute(comando)
        resultado2 = cursor.fetchall()
        #print(resultado2[0][3])
        if resultado2:  # verifica se não está vazio
            texto = texto + ', Inventores: ' + resultado2[0][3]
        else:
            texto = texto + ', Inventores: N/A'  # ou algum valor padrão
    
        #print("--")
        
        query = f"Identifique páginas na internet sobre a patente: {texto}"
        print(query)
        
        url = "https://api.openai.com/v1/chat/completions"
        data_json = {
            "model": "gpt-4o-mini",  # Use o modelo desejado, como 'gpt-4'
            "messages": [
                {"role": "user", "content": query}
            ]
        }
        headers = {
            "Authorization": f"Bearer {openai_api_key}",
            "Content-Type": "application/json"
        }
        # response = requests.post(url, headers=headers, json=data_json, verify=False)
        response = None
        if response is None:
            print('##################')
        elif response.status_code == 200:
            resposta = response.json()
            resumo = resposta['choices'][0]['message']['content']
            resumo = resumo.replace("'","")
            if "não encontrei" in resumo.lower():
                print("Não encontrei nada sobre esta patente na internet.")
            else:        
                print(resumo)
        else:
            print(f"Erro {response.status_code}: {response.text}")

102012012322 de 1/2295
Identifique páginas na internet sobre a patente: 102012012322, Depositante: VGBIO BIOLUBRIFICANTES LTDA (BR/SP) , Título: GRAXA BIOLUBRIFICANTE DE BASE VEGETAL E PROCESSO DE PRODU??O, Resumo: , consiste em uma pasta lubrificante composta de ?cidos graxos derivados de ?leoas vegetais de mamona, nabo forrageiro e soja, e seu m?todo de produ??o, Inventores: JOS? DOMINGOS POLVERE
##################
102012014252 de 2/2295
Identifique páginas na internet sobre a patente: 102012014252, Depositante: Profilatica Produtos Odonto Medico Hospitalares Ltda (BR/PR) , Título: DOSADOR AUTOM?TICO DE ALTA PRECIS?O PARA DILUI??O DE L?QUIDOS, PROCESSO E SISTEMA DE FUNCIONAMENTO, Resumo: A presente inven??o tem por objetivo um equipamento para realizar a dilui??o de produtos l?quidos concentrados, de forma cont?nua, e em concentra??es e quantidades variadas. Tal equipamento possui ainda um processo hidr?ulico para realizar a dilui??o, e um sistema de controle em um circuito PCI, que controla o equipamento e realiza o c?lculo da dosagem, com base em informa??es de sensores de temperatura, condutividade, fluxo e sensor qu?mico. A dilui??o ocorre em um misturador e, depois de misturado, obt?m-se o produto protno para uso em um recipiente. O equipamento disp?e de uma impressora que permite a impress?o dos dados da dilui??o realizada, Inventores: Fausto Fernando Hilario Gomes, Renato Polinari de Araujo
##################
102012018421 de 3/2295
Identifique páginas na internet sobre a patente: 102012018421, Depositante: QU?MICA SERVI?OS E SOLU??ES AMBIENTAIS LTDA. (BR/MG) , Título: PROCESSO PARA RECUPERA??O DE SAIS DE FERRO OU ALUM?NIO A PARTIR DE LODO ORIGINADO EM ESTA??ES DE TRATAMENTO DE ?GUA (ETAS), AO MESMO TEMPO EM QUE SE OBT?M UMA REDU??O DO VOLUME DE LODO FINAL, Resumo: , BEM COMO OS DITOS SAIS OBTIDOS A PARTIR DO REFERIDO PROCESSO. A presente inven??o refere-se a um processo para recupera??o de sais de ferro ou alum?nio a partir de lodo originado em ETAs, ao mesmo tempo em que se obt?m uma redu??o do volume de lodo final, compreendendo as seguintes etapas: (a) prepara??o do lodo a ser processado atrav?s da adi??o de ?gua de reciclo para equalizar a consist?ncia do lodo at? a faixa de 12 a 25% de teor de s?lidos, (b) ataque ?cidos da suspens?o de lodo preparada na etapa (a) por meio de adi??o de ?cido sulf?rico ou ?cido clor?drico quantificado via c?lculo estequim?trico, (c) decanta??o do produto integral obtido na etapa (b), gerando uma fase l?quida l?mpida contendo os sais de ferro ou de alum?nio recuperados e um precipitado, (d) armazenamento da fase l?quida obtida na etapa (c) que constitui o produto final, (e) processamento do precipitado obtido na etapa (c) em filtro prensa, gerando um filtrado e uma torta, (f) armazenamento do filtrado obtido na etapa (e) em um tanque de ?guas de lavagem, e (g) reciclo da ?gua de lavagem contida no tanque de ?guas de lavagem a etapa (a) para equaliza??o do lodo. A presente inven??o refere-se ainda aos sais de ferro ou alum?nio obtidos atrav?s do processo de acordo com a presente inven??o, Inventores: EDUARDO DA GAMA CAMARA, LUIZ SERGIO VIEIRA, MARCO AUR?LIO VENDITTI
##################
102012026433 de 4/2295
Identifique páginas na internet sobre a patente: 102012026433, Depositante: Universidade Estadual do Centro Oeste - Unicentro (BR/PR) , Título: PROCESSO DE PRODU??O DE G?S HIDROG?NIO EM METAIS IMERSOS EM MEIO ?CIDO CONTENDO BENZOTRIAZOL, Resumo: . O processo de produ??o de g?s hidrog?nio utilizando-se de t?nicas eletroqu?micas com diferentes metais, com e sem tratamento das superf?cies met?licas como a?o inoxid?vel tipo AISI 304 e 316, liga de tit?nio, imersas em solu??es de ?cido f?rmico de 0,1 a 27 mol L-1 contendo: Benzotriazol (BTAH) de 1 a 10-10 mol L-1 ou composto org?nico contendo o hetero?tomo de nitrog?nio ou grupo organicos da familia de azois. O referente processo leva a maior efici?ncia na gera??o de hidrog?nio para aplica??o energ?tica, principalmente para c?lulas combust?veis. O uso do BTAH ou de composto org?nico similar atua na cat?lise de rea??o de hidrog?nio, via adsor?o do composto na superf?cie met?lica criando ?reas ativas e n?o ativas na superf?cie met?lica, o que ocasiona acelera??o na produ??o de g?s hidrog?nio e consequentemente maior gera??o, permitindo economicidade energ?tica para a gera??o do g?s hidrog?nio, Inventores: Paulo Rog?rio Pinto Rodrigues, Andr? Lazarin Gallina, Bianca Vanjura Dias
##################
102012026965 de 5/2295
Identifique páginas na internet sobre a patente: 102012026965, Depositante: TECVAN INFORM?TICA LTDA. (BR/BA) , Título: SISTEMA DE SEGURAN?A PARA A PROTE??O MEC?NICA E ELETR?NICA DE EQUIPAMENTOS PARA TRANSA??O DE VALORES, Resumo: , pertencente ao campo dos artigos banc?rios, compreende uma novo sistema construtivo que proporciona prote??o eletr?nica e mec?nica de circuitos eletr?nicos sens?veis, utilizados em Equipamentos Seguros, contra a invas?o, aquisi??o e modifica??o n?o autorizada dos circuitos e dos dados contidos em seu interior, mais exatamente a inova??o proposta no presente relat?rio est? na disposi??o das placas de circuito impresso (1), componentes e cicuitos flex?veis (2), configuradas de modo a criar um nicho seguro, um local dentro do Equipamento Seguro totalmente reservado, cercado por placas de cicuito impresso (1) e tamb?m por circuitos flex?veis (2), mantendo-o completamente fechado, esta regi?o do Equipamento Seguro (3) passa a ser ent?o uma zona ? prova de tentativas de invas?o, aquisi??o e modifica??o n?o autorizada dos componentes no seu interior e das informa??es armazenadas e manipuladas por estes componentes, Inventores: JORGE RIBEIRO PEREIRA
##################
102012027122 de 6/2295
Identifique páginas na internet sobre a patente: 102012027122, Depositante: Universidade Federal do Esp?rito Santo -UFES (BR/ES) , Instituto Capixaba de Pesquisa, Assist?ncia T?cnica e Extens?o Rural -INCAPER (BR/ES) , Título: PROCESSO DE PURIFICA??O DE BROMELINA, BROMELINA PURIFICADA E USOS DE ENZIMA PURIFICADA, Resumo: A modalidade de inven??o proposta trata de um processo de purifica??o de enzima proteol?tica, a enzima purificada e seus usos. ? proposto um m?todo para a purifica??o da enzima em quest?o, mas especificamente a bromelina, a partir de produtos org?nios, em especial res?duos agr?colas do abacaxizeiro (Ananas comosus var. comosus). O extrato vegetal ? filtrado e centrifugado, obtendo-se um sobrenadante, que ? aplicado em uma coluna de troca i?nica. As fra??es obtidas s?o submetidas a colunas de exclus?o, obtendo-se a protease purificada, com baixo custo e aproveitamento de res?duos. O processo proposto permite a manuten??o da atividade biol?gica da bromelina, permitindo a esta uma vasta aplica??o biotecnol?gica, de interesse para ind?stria farmac?utica, cosm?tica, aliment?cia e de bebidas, Inventores: Helbert Barcellos da Costa, Jos? Aires Ventura, Patricia Machado Bueno Fernandes
##################
102012030520 de 7/2295
Identifique páginas na internet sobre a patente: 102012030520, Depositante: Petroleo Brasileiro S.A. - Petrobras (BR/RJ) , Universidade Federal de S?o Carlos - UFSCAR (BR/SP) , Título: SISTEMA REFRAT?RIO NANOESTRUTURADO DE ELEVADA RESIST?NCIA ? EROS?O E AO CHOQUE T?RMICO, Resumo: A presente inven??o faz refer?ncia a um sistema refrat?rio nanoestruturado de elevada resist?ncia ? eros?o, compreendendo agentes ligantes coloidais, tais como s?lica ou alumina, e aditivos sinterizantes. A combina??o da maior reatividade das part?culas nanom?tricas dos ligantes com a capacidade de sinteriza??o em baixa temperatura permite a produ??o de materiais de elevada resist?ncia ? eros?o quando expostos a temperaturas at? 1000<198>C, Inventores: Victor Carlos Pandolfelli, Eduardo Prestes, Mariana de Albuquerque Lima Braulio, Jorivaldo Medeiros, Daniel Telhado Gomes, Jordana Luiza da Costa Veiga
##################
102012031380 de 8/2295
Identifique páginas na internet sobre a patente: 102012031380, Depositante: Funda??o Universidade Federal de S?o Carlos (BR/SP) , Universidade Federal do Paran? (BR/PR) , Universidade Estadual Paulista (BR/SP) , Título: PROCESSO DE PREPARA??O DE COMPLEXOS MET?LICOS DE HESPERIDINA E HESPERITINA, COMPLEXOS MET?LICOS E COMPOSI??ES INSETICIDAS PARA O CONTROLE DE INSETOS PRAGAS URBANOS, DA AGRICULTURA E DA SILVICULTURA, Resumo: ? descrito um processo de prepara??o de complexos met?licos de hesperidina e hesperitina, que compreende prover os complexos [Mn (L-L)m), onde n e m s?o 1 ou 2, M compreende um metal selecionado dentre Ru(II), Mg(ll), Co(ll/lll), Cu(ll/llI), Mn(II/III), Fe(ll/Ill), Zn(ll) e Ca(II)e (L-L) ? um ligante polipirid?nico, prover uma flavanona (L) selecionada dentre hesperidina e hesperitina desprotonada, combinar o complexo [Mn(LL)m] e a flavanona desprotonada sob condi??es reacionais para obter os complexos a metais (Mn(L)k(L-L)m)?+, onde k ? 1 ou 2, precipitar os complexos por adi??o de compostos selecionados dentre NH4PF6, Na(CH3COO) e NaCI, separar e lavar, obtendo os complexos met?licos [Mn(L)k(LL)m] (PF6)~, (Mn(L)k(LL)m] [AcO] e [Mn(L)k(L~L)m] (Cl)x. S?o tamb?m descritos os complexos obtidos e as composi??es inseticidas ? base dos complexos met?licos da inven??o, Inventores: Jo?o Batista Fernandes, Maria F?tima das Gra?as Fernandes da Silva, Paulo Cesar Vieira, Rose Maria Carlos, Arlene Gon?alves Correa, Moacir Rossi Forim, Andr? L?cio Franceschini Sarria, Liliane Nebo, Andr?ia Pereira Matos, Ana Paula Terezan, Francisco de Assis Marques, Mario Antonio Navarro da Silva, Eduardo Novaes Ramires, Vin?cius Annies, L?gia Moraes Barizon de Souza, Odair Corr?a Bueno, Fernando Carlos Pagnocca, Regina Maria Mendes de Oliveira
##################
102012032977 de 9/2295
Identifique páginas na internet sobre a patente: 102012032977, Depositante: Funda??o Universidade de Caxias Do Sul - UCS (BR/RS) , Título: PROCESSO DE OBTEN??O DE MEMBRANAS DE PVDF, MEMBRANAS, E, USO DAS MEMBRANAS DE PVDF PARA ULTRAFILTRA??O E NANOFILTRA??O, Resumo: A presente inven??o pertence ao processo de produ??o de membranas de poli (fluoreto de vinilideno) (PVDF), assim?tricasa e obtidas pelo processo de invers?o de fases utilizando ?gua, etanol e SDS como n?o solvente. As membranas s?o manom?ricas (2-4 nm) as membranas obtidas com precipitante ?gua e etanol e semi-perme?vel obtidas com o precipirante SDS. As membranas de PVDF assim?tricas preparadas por processos de invers?o de fases apresentam seletividade ? gases, como C0~ 2~/N~ 2~, Inventores: Mara Zeni Andrade, M?nica Beatriz Th?rmer, Patr?cia Poletto
##################
102012033503 de 10/2295
Identifique páginas na internet sobre a patente: 102012033503, Depositante: EMBRAPA - Empresa Brasileira de Pesquisa Agropecuaria (BR/DF) , Katholieke Universiteit Leuven (KU Leuven) (BE) , Título: PROMOTOR DERIVADO DE GENES RELATIVOS ? RAB, COMPOSI??ES E M?TODOS DE APLICA??O, Resumo: A presente inven??o se refere a uma sequ?ncia de polinuceot?deos capaz de modificar a express?o de forma eficiente de um ou mais genes de interesse em plantas, particularmente do g?nero Musa, bem como as ferramentas para obten??o de plantas geneticamente modificadas utilizando tal sequ?ncia e uso da mesma. As possibilidades de uso da inven??o s?o amplas, destaca a cria??o de novas cultivares nutricionalmente mais enriquecidas, mais adaptadas e/ou mais resistentes, como por exemplo, a express?o de genes em plantas para conferir resist?ncia a pat?genos, como o Mycosphaerella fijiensis, Inventores: Manoel Teixeira Souza J?nior, Leandro Eugenio Cardamone Diniz, Janay Almeida dos Santos Serejo, Rony Swennen, Serge Remy
##################
102012033540 de 11/2295
Identifique páginas na internet sobre a patente: 102012033540, Depositante: Universidade Federal de Lavras (BR/MG) , Funda??o de Amparo ? Pesquisa do Estado de Minas Gerais - FAPEMIG (BR/MG) , Título: PRODU??O DE MATERIAIS CARBON?CEOS COM ?REA DESENVOLVIDA E ATIVIDADE CATAL?TICA: ATIVA??O QU?MICA COMBINADA CR/ZN PARA OBTEN??O DE CARV?O ATIVADO CONTENDO CR COMO CATALISADOR PARA DECLORINA??O DE COMPOSTOS DE INTERESSE AMBIENTAL, Resumo: A presente inven??o trata da s?ntese de catalisadores suportados em carv?o ativado proveniente de res?duo de biomassa para a oxida??o de contaminantes de interesse ambiental. A s?ntese envolve uma ?nica etapa que consiste em passo com fun??es combinadas de desenvolvimento de ?rea espec?fica na matriz carb?nica e, paralelamente, forma??o da fase ativa de cromo. O material obtido poder? ser utilizado em aplica??es de interesse industrial, com possibilidade de ser empregado devido ? facilidade de s?ntese, baixa periculosidade j? que o n?o h? lixivia??o do metal, e custo acess?vel, Inventores: M?rio C?sar Guerreiro, Aline Auxiliadora Tireli, Iara do Ros?rio Guimar?es, Andr? Labegalini
##################
102013000665 de 12/2295
Identifique páginas na internet sobre a patente: 102013000665, Depositante: Jorge Luiz Ara?jo de Souza (BR/RJ) , Wiliian Pinto De Abreu (BR/RJ) , Título: COLETOR DE ?LEO RESIDUAL DE SOJA, CANOLA, GIRASSOL E OUTROS DE USO CULIN?RIO COMEST?VEL, COMERCIAL OU INDUSTRIAL ACOPLADO AO BOTIJ?O DE G?S TIPO GLP, Resumo: Patente de inven??o para acondicionar ?leo Redidual de Soja,Granola,Girassol e outros de uso Culin?rio,Comest?vel,Comercial ou Industrial Acoplado ao Butij?o de G?s tipo GLP, consiste em duas pe?as sendo uma no formato semic?rculo, com capacidade de 3 litros, com fenda para passagem de mangueira 1, com orif?cio coletor de ?leo residual 2, com bordas externas superior 3, bordas externas em sua lateral 4, parte interna do reservat?rio acoplada ao botij?o 5, borda de apoio inferior do coletor acoplada ao botij?o 1, borda lateral do coletor externo acoplado ao botij?o 2, tampa coletora de res?duo na sua parte superior 3, outra de forma circular com tampa do coletor de ?leo residual do reservat?rio interno do clique do botij?o 1, borda lateral do coletor interno do clique do botij?o 2, orif?cio central superior do encaixe do clique do coletor interno do clique do botij?o 3, fenda da al?a do coletor interno do botij?o 4, base inferior acoplada ao clique do botij?o do coletor interno do clique do botij?o 1, orif?cio central inferior do encaixo do clique do botij?o (2), lateral do coletor interno do clique do botij?o 3, Inventores: Jorge Luiz Ara?jo de Souza, Wiliiam Pinto de Abreu, Simone Cristina Correa de Abreu
##################
102013002396 de 13/2295
Identifique páginas na internet sobre a patente: 102013002396, Depositante: Maycon Isense Dalpiaz (BR/SP) , Título: PROCESSO DE OBTEN??O DE COMPOSTO SEMIPASTOSO ANTIADERENTE PARA A?O L?QUIDO EM METAL S?LIDO E COMPOSTO SEMIPASTOSO ANTIADERENTE PARA A?O L?QUIDO EM METAL S?LIDO, Resumo: Especialmente de um processo de consecu??o de composto semipastoso e seu produto, cuja composi??o resulta um antiaderente de f?cil aplica??o, resistente a alta temperatura, indicado para prote??o de todo equipamento suscet?vel a contato direto e/ou sofra proje??o de metais liquefeitos como, por exemplo, res?duos de solda de metais em geral, cuja composi??o n?o apresenta adi??o de amon?aco, solventes vegetais e/ou hidrocarbonetos, neste caso, diferenciado por n?o conter nenhum vol?til em sua formula??o e poder ser trabalhado em locais de altas temperaturas ou fonte de igni??o que n?o existe o perigo de inc?ndio e/ou explos?o e sua f?rmula ? neutralizada com um pH 7,2 +- 0,5 n?o causando nenhum problema de ataque a epiderme do aplicador ou qualquer pessoa envolvido na aplica??o, Inventores: Maycon Isense Dalpiaz
##################
102013004317 de 14/2295
Identifique páginas na internet sobre a patente: 102013004317, Depositante: ALVARO M?RCIO MOUTINHO (BR/SP) , Título: SISTEMA DE PERSONALIZA??O DE CORES PARA REJUNTAMENTO ACR?LICO, Resumo: , composto por uma base universal fabricada a partir de cargas minerais classificadas de acordo com sua natureza e granulometria (quartzo e dolomitas), resina estireno, ?gua, biocida, nonilfenol, antiespumante, espessante acr?lico, emuls?o de parafina, trietanolamina, di?xido de tit?nio, pigmentos org?nicos e inorg?nicos dispersos.Seu campo de aplica??o pertence ? ?rea da constru??o civil, Inventores: ALVARO M?RCIO MOUTINHO
##################
102013005036 de 15/2295
Identifique páginas na internet sobre a patente: 102013005036, Depositante: Grendene S.A (BR/CE) , Título: CAL?ADO COM CABEDAL REVERS?VEL E CABEDAL REVERS?VEL, Resumo: A presente inven??o pertence ao campo da ind?stria cal?adista e faz refer?ncia a uma cal?ado com cabedal ?nico e revers?vel, associado ? um solado, possibilitando duas possibilidades de customiza??o em uma ?nica pe?a, possibilitando que o usu?rio alterne seu cal?ado quando assim desejar, sem necessitar possuir um cabedal para cada customiza??o desejada e, ainda, que o cabedal seja disposto em toda a superf?cie superior do p?, Inventores: Edson Matsuo
##################
102013011897 de 16/2295
Identifique páginas na internet sobre a patente: 102013011897, Depositante: Universidade Federal do Rio Grande do Norte (BR/RN) , Título: PROCESSO DE PRODU??O DE HIDR?XI-METIL-FURFURAL (HMF) POR MEIO DE ROTA QU?MICA A PARTIR DA DESIDRATA??O DE A?UCARES UTILIZANDO L?QUIDOS I?NICOS SUPORTADOS EM NANOPART?CULAS DE ZIRC?NIA, Resumo: A. A rea??o de desidrata??o de a??cares ? uma das mais importantes abordagens para transformar biomassa em produtos qu?micos de utilidade. Como o campo de aplica??o desses componentes ? realmente amplo, n?o ? novidade que a pesquisa nesta ?rea, iniciada no fim do s?culo 19, esteja ainda sendo desenvolvida. Entre os v?rios produtos qu?micos derivados de biomassa, o 5-hidroximetilfurfural (HMF) ? um intermedi?rio particularmente valioso para a qu?mica fina e para a ind?stria farmac?utica. O HMF ? um s?lido amarelo de baixo ponto de fus?o e altamente sol?vel em ?gua, sua mol?cula ? constiu?da por um anel de furano contendo os grupos funcionais alde?do e ?lcool. ? identificado em uma ampla variedade de alimentos processados por aquecimento, por exemplo, o mel. A inova??o proposta nesta patente diz respeito a um conjunto de s?ntese com o objetivo de produzir um catalisador ? base de zirc?nia e l?quidos i?nicos para desidrata??o de a??cares e consequente produ??o de HMF (biocombust?vel). ? apresentada a metodologia de s?ntese que consiste na produ??o de nanopart?culas de zirc?nia com superf?cie funcionalizada a partir da ancoragem de dois l?quidos i?nicos distintos, e deste modo, modificando-se e as tornando catalisadores eficientes para produ??o de biocombust?vel a partir de a??cares, Inventores: Rubens Maribondo do Nascimento, Carlos Alberto Paskocimas, Kalpeshkumar Bhikhubhai Sidhpuria, Osvaldo Chiavone Filho, Graziele Lopes de Souza, Daniel Ara?jo de Macedo, Jean Carlos Silva Andrade
##################
102013017530 de 17/2295

ProgrammingError: 1054 (42S22): Unknown column 'MU8601615' in 'where clause'

In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

# https://otimistarj.pythonanywhere.com/chat?numero=PI1101142&doc=US2009077666
# https://patents.google.com/patent/US20090077666A1/en?oq=US2009077666
# https://patents.google.com/patent/US2009077666A1/en?oq=US2009077666

doc = 'US20090077666'
url = f"https://patents.google.com/patent/{doc}A1/en?oq={doc}"
print(url)
html = urlopen(url)
bs = BeautifulSoup(html.read(),'html.parser')
nameList = bs.findAll("section", {"itemprop":"description"})
for name in nameList:
    texto_D1 = name.getText()
print(texto_D1)

https://patents.google.com/patent/US20090077666A1/en?oq=US20090077666

Description

CLAIM OF PRIORITY
   This application claims priority under 35 USC §119(e) to U.S. Patent Application Ser. No. 60/894,431, filed on Mar. 12, 2007, the entire contents of which are hereby incorporated by reference.
 BACKGROUND
   This application relates to information systems, computers and software. In the past three decades, the information technology (IT) has changed and continues to change many aspects of the society. Applications based on computers and software have reshaped the technology landscapes and system capabilities in modern financial systems, communication systems, healthcare systems, military systems, aerospace systems, entertainment systems, and much more. As software becomes a key infrastructure in many domains, software security failure can cause severe damages and losses to system key stakeholders.
    Vulnerabilities can be prioritized by static rankings recommended by authority organizations such Computer Emergency Response Team (CERT), National Institute of Standard Technology (NIST), Microsoft®, and Symantec®. However, these ratings are static and do not take the system stakeholder utilities into account. Measuring Commercial Off-The-Shelf (COTS) security threats and prioritizing vulnerabilities efficiently can be difficult due to lack of effective metrics to measure stakeholder utilities, lack of firm historical data, and the complex and sensitive nature of security.
 SUMMARY
   Techniques, systems and apparatus are disclosed for analyzing security threats associated with software and computer vulnerabilities. In one aspect, analyzing security threats associated with software and computer vulnerabilities includes identifying stakeholder values relevant for a software system. The identified stakeholder values are quantified using a quantitative decision making approach such as Analytical Hierarchy Process (AHP) to prioritize security vulnerabilities of the software system. A Structured Attack Graph is generated to include the quantified stakeholder values to evaluate attack paths in that Structure Attack Graph. Each attack path represents a respective attack scenario. The entire, or at least part of the Structured Attack Graph has a layered architecture. The Structured Attack Graph includes two or more nodes. Each layer in the Structured Attack Graph represents a key entity in security threat modeling, for example, the layers of System Key Stakeholders, Computer Hosts, Commercial Off The Shelf Software, Vulnerabilities, Network Ports, and Attackers, Based on the generated Structured Attack Graph, Structured Attack Paths are identified. The security severity of each Structured Attack Path are measured based on the relevant Stakeholder Values. The security criticalness of each node in the Structured Attack Graph is measured based on the Structured Attack Paths that go through the node. A fast algorithm based on the Structured Attack Graph is developed to efficiently prioritize the vulnerabilities, which makes this method scalable to large and complex software systems.
    Implementations can optionally include one or more of the following features. A quantitative measure of security criticalness of each node in the Structured Attack Graph can be calculated in terms of Threat Key Values that represent security threats. In addition, a recommendation can be provided on a security investment plan including identifying at least one of the attack paths that a security practice can suppress. Identifying the stakeholder values can include identifying values that cannot be quantified in terms of tangible units. Generating the Structured Attack Graph can include generating a structured attack graph that includes two or more layers with each layer including one or more of the nodes. Also, generating the structured attack graph can include generating the structured attack graph that includes at least five layers that represent the identified stakeholder values, the computer host, software installed on the computer host, vulnerabilities of the software that is part of the software system, and possible attackers. Further, quantifying the identified stakeholder values can include quantifying the identified stakeholder values using a quantitative decision making approach that includes analytical hierarchy process. In addition, generating the structured attack graph can include generating a structured attack graph that includes information on one or more communication ports. Also, a quantitative measure of criticalness of each port can be calculated in terms of security threats. A greedy algorithm can be operated to calculate an optimal rule set that balances security and efficiency.
    In another aspect, a system includes a communication network and two or more servers connected to the network to implement a software system and to perform operations. The servers are operable to identify stakeholder values relevant for the software system implemented in the two or more servers; quantify the identified stakeholder values using a quantitative decision making approach to prioritize vulnerabilities of the software system; generate a structured attack graph that includes the quantified stakeholder values to define a scalable framework to evaluate attack scenarios, wherein the structured attack graph includes two or more nodes; and, based on the generated structured attack graph, identify structured attack paths. Each structured attack path represents a respective attack scenario. The subject matter as described in this specification can be implemented as a computer program product, embodied on a computer-readable medium, operable to cause a data processing apparatus to perform operations as described above. In addition, the subject matter as described in this specification can be implemented as one or more systems.
    The subject matter described in this specification potentially can provide one or more of the following advantages. The Threat Modeling Method Based on Attack Path Analysis (T-MAP) can quantify security threats by calculating the total severity weights of relevant attacking paths for Commercial Off The Shelf (COTS) based systems. Further, security economic analysis can be enabled by T-MAP. T-MAP is sensitive to system stakeholder value priorities and organizational information technology (IT) environment. T-MAP can distill the technical details of thousands of relevant software vulnerabilities into management-friendly numbers at a high-level. In addition, T-MAP can systematically establish the traceability and consistency from management-level organizational value propositions to technical-level security threats and corresponding mitigation strategies. For example, in a large IT organization, T-MAP can effectively demonstrate strength in prioritizing and estimating security investment cost-effectiveness and evaluate the security performance of COTS systems. T-MAP can be used to estimate and optimize the cost-effectiveness of security practices such as software patching, user account control and firewall.

BRIEF DESCRIPTION OF THE DRAWINGS
    FIG. 1 shows an example process for providing key components of T-MAP analysis.
     FIG. 2 shows an example scenario of how a successful attack can affect organizational values.
     FIG. 3 shows an example process of implementing T-MAP.
     FIG. 4 shows an example Scheiner's attack tree.
     FIG. 5 shows an example T-MAP structured attack graph.
     FIG. 6 shows an example algorithm to enumerate all structured attack path for a given structured attack graph G.
     FIG. 7 shows an example Unified Modeling Language (UML) model of a structured attack path.
     FIGS. 8 a and 8 b is a table showing descriptions of example class attributes.
     FIG. 9 shows an example process for performing value driven evaluation of attack scenarios.
     FIG. 10 shows examples of estimated labor costs.
     FIG. 11 shows example top-level stakeholders, stakeholder value propositions, and corresponding criteria weights that are relevant to Server X.
     FIG. 12 shows an example calculation of top-level criteria weights.
     FIG. 13 shows example results of a case study.
     FIG. 14 shows example relative group size ratings (A.GS) calculated through Analytical Hierarchy Process (AHP) pair-wise comparison.
     FIG. 15 shows the relative ratings of the A.GS, A.SL, and A.MT for each group can be calculated through AHP.
     FIG. 16 shows an example summary of Attacker Groups' information in an example case study.
     FIG. 17 shows examples of vulnerability technical attribute ratings.
     FIG. 18 shows an example of ThreatKey calculation for a three-layer-attack-graph.
     FIG. 19 shows an example of an algorithm for calculating the ThreatKey of each node.
     FIGS. 20 and 21 show example algorithms that include pseudo-code for calculating BottomUpWeight and TopDownWeight of each node.
     FIG. 22 is an example screen shot from the T-MAP tool.
     FIG. 23 shows example COTS software installed on Server X.
     FIG. 24 shows an example screenshot of attach path calculation results.
     FIG. 25 is a table showing an example suppressing matrix used to summarize the effectiveness of each alternative security investment plan.
     FIG. 26 shows an example screenshot from a T-MAP tool for evaluating the effectiveness of patching Server X.
     FIG. 27 shows a plot of an example optimal security practice plan.
     FIG. 28 shows a graph showing example sweet spots of investment.
     FIG. 29 shows an example component model of a T-MAP tool.
     FIG. 30 shows an example layered software architecture employed by a T-MAP tool.
     FIG. 31 is a process flow diagram showing an example process for measuring inaccuracy of ranking system R in prioritizing n vulnerabilities.
     FIG. 32 shows an example pair-wise matrix.
     FIG. 33 shows an example process for conducting various case studies.
     FIG. 34 shows an example comparison between manual rankings of a security manager and T-MAP rankings.
     FIG. 35 shows example system key stakeholder value propositions.
     FIG. 36 is a table showing example evaluation scores for possible security breach scenarios.
     FIG. 37 is a table showing example COTS components.
     FIG. 38 shows a plot showing example comparison of the system manager's rankings against the T-MAP rankings.
     FIG. 39 shows the system key stakeholder value propositions for Center for Systems and Software Engineering (CSSE) GreenBay case study example.
     FIG. 40 shows derived severity scores for possible security breach scenarios.
     FIG. 41 is a table showing example COTS components.
     FIG. 42 shows an example comparison of the security expert rankings against the T-MAP output.
     FIG. 43 shows an example T-MAP vs. Value Neutral Approaches comparison for a first example case study.
     FIGS. 44 a and 44 b show an example T-MAP vs. Value Neutral Approaches comparison for a second example case study.
     FIG. 45 shows an example T-MAP vs. Value Neutral Approaches comparison for a third example case study.
     FIG. 46 is a table showing example comparisons that compares prioritization performance across T-MAP and other value neutral approaches.
     FIG. 47 shows example box plots of inaccuracy comparison results.
     FIG. 48 shows an example summary of the profiles of security professionals who participated in the example case studies.
     FIGS. 49, 50, 51 and 52 show example summaries for using T-MAP in Boehm's Spiral Model, ISO 15288 System Engineering Life-cycle Model, Royce's Waterfall Model and Boehm's Incremental Commitment Model (ICM) respectively.
     FIG. 53 shows an example distribution of vulnerabilities over network port numbers.
     FIG. 54 shows example effects of Firewall Rules.
     FIG. 55 shows an example process for generating a Firewall rule set.
     FIG. 56 shows an example structured attack graph with network port information.
     FIG. 57 shows an example Greedy Algorithm.
     FIG. 58 shows example system inputs and outputs for Firewall rule generation.
     FIG. 59 shows an example of Netflow data that a T-MAP tool can process.
     FIG. 60 shows an example user interface screenshot specifying enforced port control.
     FIG. 61 shows another example screenshot.
     FIG. 62 shows example number of Firewall rules vs. example umber of exploitable attack paths.
     FIG. 63 shows example number of packets vs. number of exploitable attack paths.

   Like reference symbols and designations in the various drawings indicate like elements.
 DETAILED DESCRIPTION
   Techniques and systems are disclosed for assuring security under IT resource constrains. Assuring security under the existing limited IT resources can be challenging for various modern organizations that heavily relies upon a healthy IT infrastructure. To assure security, threats should be effectively prioritized to optimize resource allocation.
    Vulnerabilities can be prioritized by ratings recommended by authority organizations such Computer Emergency Response Team (CERT), National Institute of Standards and Technology (NIST), Microsoft, and Symantec. However, these ratings tend to be static and may not take the system stakeholder utilities into account. Implementing such static ratings can require additional investigations to determine the criticalness of vulnerabilities under specific system context. Measuring COTS security threats and prioritize vulnerabilities efficiently can be difficult due to lack of effective metrics to measure stakeholder utilities, lack of firm historical data, and the complex and sensitive nature of security.
    Additional difficulties may exist in measuring COTS security threat and prioritizing vulnerabilities. For example, there can be a lack of effective methods/metrics to measure and prioritize security threats from software vulnerabilities under specific stakeholder value/utility context. The vulnerability rating systems by authority organizations such as CERT, Microsoft, NIST, and Symantec are value neutral, static, and not sensitive to stakeholder utility functions. Critical features for security budgeting can include the ability to measure the “composition of forces” of possible thousands of COTS vulnerabilities in IT systems and the effectiveness of security investment. In addition, security assessment may need to be described and reported in a management friendly language.
    These and other difficulties can cause various undesired events. For example, misidentification of critical security vulnerabilities can result in business loss. When the allocation of security resources fails to match the system stakeholder utility priorities, resource abuse can occur. Miscommunication between technical and management can result in security investment decisions based on inaccurate perceptions.
    Techniques and systems described in this specification can be used to provide a set of Software Engineering methodologies, metrics, algorithms, guidelines and automated tools to help organizations balance the tradeoffs between security and resource constraints. Implementations can be applied on optimizing COT based systems, the key building blocks for most IT systems.
    According to the NIST IT Security Guideline, the security impacts of all vulnerabilities can be specified in terms of Confidentiality, Integrity, and Availability (CIA). These security attributes may have very different business indications under different application context. Therefore, vulnerabilities associated with different type of CIA impacts are treated differently based on system stakeholder value context. Furthermore, traceability is established between the stakeholder value propositions and the treatments to vulnerabilities that involve different CIA impacts. As described above, COTS vulnerability ranking or ratings systems by authority organizations such as NIST, Cisco, ISS, Microsoft, SANS, CERT, Symantec/BugTraq, and Qualys are value-neutral and static. In these static rankings a coarse resolution of ranking scales such as “High/Medium/Low” or “Critical/Medium/Moderate/Low” are used to differentiate more than 27,400 known COTS vulnerabilities.
    The techniques and systems described in this specification can implement a stakeholder value sensitive approach to prioritize COTS security vulnerabilities and measure the security threat associated with COTS based systems. In addition, T-MAP is implemented to better prioritize COTS security vulnerabilities than above described value-neutral approaches.
    In this specification, “better” is measured by accuracy/inaccuracy in vulnerability rankings. For a COTS based system as described in this specification, the Confidentiality, Integrity and Availability have different indications to the system stakeholder values. The accuracy of T-MAP rankings are measured by inaccuracy that describes the ratio of the number of clashes between vulnerability priorities and stakeholder value priorities and the total number of comparisons made. A stakeholder value driven approach, namely the Security Threat-Modeling method based on Attacking Path analysis (T-MAP), is provided to inject stakeholder incentives into COTS vulnerability prioritization. The T-MAP analysis also enables the measurement of the cost effectiveness of common security protections such as Firewall, data encryption, and patching for COTS based systems.
     FIG. 1 shows an example process 100 for providing key components of a T-MAP analysis. A systematic framework is devised 110 to capture the stakeholder value priorities through Analytical Hierarchy Process (AHP) analysis and inject the value propositions into COTS vulnerability ranking. Empirical data points/case studies are provided 120 where the value-driven method (i.e., T-MAP) significantly outperforms the value-neutral methods in COTS security vulnerability prioritization. The technical details of thousands of software vulnerabilities are distilled 130 into executive-friendly language at a high-level. The traceability and consistency are systematically established 140 from organizational-level value propositions to technical-level COTS security vulnerabilities and corresponding mitigation strategies.
    An algorithm is developed 150 to calculate the associated threat weight or threat key of vulnerabilities that can considerably increase the method scalability to large COTS based systems. Achieving this scalability may limit the scope of analyses to single-step-exploits. In addition, a metric is designed 160 to measure and compare the accuracy/inaccuracy of security vulnerability ranking systems. The security threat evaluation process is automated 170 using a T-MAP software tool.
    T-MAP tool automates T-MAP to reduce the necessary human effort involved in security assessment. T-MAP tool can enumerate the possible attack scenarios for IT systems based on a vulnerability database that includes the information of more than 27,400 known software vulnerabilities. Each attack scenario can be specified with the following information: (1) the organizational value affected; (2) the vulnerable computer; (3) the vulnerable software; (4) the CVE name of the vulnerability; (5) the impact type of the vulnerability in terms of confidentiality, integrity, and/or availability; and (6) the patch availability of the vulnerability
    Furthermore, T-MAP Tool can provide tangible evidence to assess the effectiveness of common security practices such as Firewall, system patching and hardening, enhancing physical security, creating backup systems, and data encryption.

In [8]:
import requests, json
def conectar_siscap(url,return_json=False):
    headers = {
        "Accept": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    response = requests.get(url,headers=headers,verify=False)
    if response.status_code == 200:
        if return_json:
            data = response.json()
            json_data = json.dumps(data, indent=4)
            return(json_data)
        else:
            return response.text
    else:
        return(f"Erro: {response.status_code}")

In [9]:
from urllib.request import urlopen
numero='PI1101142'
query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM titulo where numero='{numero}'" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
print(url)
#html = urlopen(url)
json_data = conectar_siscap(url,return_json=True)

https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM titulo where numero='PI1101142'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [10]:
data = json.loads(json_data)

In [11]:
if data.get("patents") and len(data["patents"]) > 0:
  resumo_cepit = data["patents"][0].get("resumo_cepit", "Resumo não disponível")
else:
  resumo_cepit = "Nenhum resultado encontrado"
print(resumo_cepit)

De qualquer setor organizacional como, por exemplo, transportes, energia, telecomunicações, água, esgoto, finanças, entre muitos outros. Inicialmente, a infraestrutura é identificada e armazenada na Base de Ativos (11), a partir da qual são identificadas e analisadas as ameaças existentes (2), e caracterizadas as interdependências da infraestrutura com asinfraestruturas relacionadas (4), dando origem à Base de Ameaças Analisadas (21) e à Base de Insumos para Diagnóstico (41), respectivamente. Em seguida é gerado, a partir da Base de Ameaças Analisadas (21), o cenário ideal de controles (:3) para proteção da infraestrutura que é armazenado na Base de Cenário Ideal (31). Por fim, a partir da Base de Cenário Ideal (31) e da Base de Insumos para Diagnóstico (41), é realizado o Diagnóstico (5) da infraestrutura em questão. O diagnóstico compreende a avaliação de impactos (501) e o cálculo de riscos (502) sobre cada ativo crítico da infraestrutura, bem como a análise desses riscos (503) e a geração de recomendações (504) que subsidiam planos de ação para a proteção de infraestruturas críticas, sendo que as informações geradas são disponibilizadas na Base de Diagnóstico (51)

In [25]:
from urllib.request import urlopen
from datetime import datetime

numero='926942360'
query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM IP_PROC where USERDOC_FILE_NBR='{numero}'" + '"'
query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM IP_PROC ip JOIN CF_USERDOC_TYPE cf ON cf.USERDOC_TYP=ip.USERDOC_TYP where ip.USERDOC_FILE_NBR='{numero}'" + '"'

url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
print(url)
json_data = conectar_siscap(url,return_json=True)
data = json.loads(json_data)

if data.get("patents") and len(data["patents"]) > 0:
    protocolo = data["patents"][0].get("DOC_NBR", "Protocolo não disponível")
    data_protocolo = data["patents"][0].get("CREATION_DATE", "Data do Protocolo não disponível")
    data_formatada = datetime.strptime(data_protocolo, "%Y-%m-%d").strftime("%d/%m/%Y")
    userdoc_name = data["patents"][0].get("USERDOC_NAME", "Nome não disponível")
    proc_nbr = data["patents"][0].get("PROC_NBR", "Nome não disponível")
else:
    protocolo = "Nenhum resultado encontrado"

print(f"Protocolo: {protocolo} de {data_formatada}")
print(userdoc_name)

query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM IP_ACTION where PROC_NBR='{proc_nbr}'" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
print(url)
json_data = conectar_siscap(url,return_json=True)
data = json.loads(json_data)

if data.get("patents") and len(data["patents"]) > 0:
    action_typ = data["patents"][0].get("ACTION_TYP", "Tipo não disponível")
    data_action_typ = data["patents"][0].get("JOURNAL_LINKAGE_VALID_DATE", "Data da ação não disponível")
    data_formatada = datetime.strptime(data_action_typ, "%Y-%m-%d").strftime("%d/%m/%Y")
else:
    protocolo = "Nenhum resultado encontrado"

print(f"Ação: {action_typ} de {data_formatada}")

query = '"' + "mysql_query" + '"' ":" + '"' + f" * FROM CF_ACTION_TYPE where ACTION_TYP='{action_typ}'" + '"'
url = f"https://cientistaspatentes.com.br/apiphp/patents/query/?q={query}"
print(url)
json_data = conectar_siscap(url,return_json=True)
data = json.loads(json_data)

if data.get("patents") and len(data["patents"]) > 0:
    action_type_name = data["patents"][0].get("ACTION_TYPE_NAME", "Tipo não disponível")
else:
    action_type_name = "Nenhum resultado encontrado"

print(f"Ação: {action_type_name}")

https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM IP_PROC ip JOIN CF_USERDOC_TYPE cf ON cf.USERDOC_TYP=ip.USERDOC_TYP where ip.USERDOC_FILE_NBR='926942360'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Protocolo: 850240287357 de 12/06/2024
Recurso contra indeferimento de pedido de registro de marca (3000.1)
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM IP_ACTION where PROC_NBR='27888913'"

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Ação: 360 de 23/07/2024
https://cientistaspatentes.com.br/apiphp/patents/query/?q="mysql_query":" * FROM CF_ACTION_TYPE where ACTION_TYP='360'"
Ação: Notificação de recurso

D:\Users\abrantes\InstallAnaconda\envs\python\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cientistaspatentes.com.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(